### ISSUE TITLE
task: Mark Coveralls tasks to continue-on-error

### ISSUE THREAD

**Issue by ogenstad** [opsmill/infrahub#1129]
### Component

CI/CD

### Task Description

Every now and again Coveralls seem to run into issues

Where any task we have like this in the pipeline can result in an HTTP 500 error response from coveralls.io.

```yaml
      - name: "Coveralls : Unit Tests"
        uses: coverallsapp/github-action@v2.0.0
        env:
          COVERALLS_SERVICE_NUMBER: ${{ github.sha }}
        with:
          flag-name: python-sdk-unit
          parallel: true
```

For example this [job](https://github.com/opsmill/infrahub/actions/runs/6249280978/job/16965604810#step:25:79):

```

⠀⠀⠀⠀⠀⠀⣿
⠀⠀⠀⠀⠀⣼⣿⣧⠀⠀⠀⠀⠀⠀⠀ ⣠⣶⣾⣿⡇⢀⣴⣾⣿⣷⣆ ⣿⣿⠀⣰⣿⡟⢸⣿⣿⣿⡇ ⣿⣿⣿⣷⣦⠀⠀⢠⣿⣿⣿⠀⠀⣿⣿⠁⠀⣼⣿⡇⠀⢀⣴⣾⣿⡷
⠶⣶⣶⣶⣾⣿⣿⣿⣷⣶⣶⣶⠶  ⣸⣿⡟ ⠀⢠⣿⣿⠃⠈⣿⣿⠀⣿⣿⢠⣿⡿⠀⣿⣿⣧⣤⠀⢸⣿⡇⣠⣿⡿⠀⢠⣿⡟⣿⣿⠀⢸⣿⡿⠀⠀⣿⣿⠃⠀⢸⣿⣧⣄
⠀⠀⠙⢻⣿⣿⣿⣿⣿⡟⠋⠁⠀⠀ ⣿⣿⡇⠀ ⢸⣿⣿⠀⣸⣿⡟⠀⣿⣿⣾⡿⠁ ⣿⣿⠛⠛⠀⣿⣿⢿⣿⣏⠀⢀⣿⣿⣁⣿⣿⠀⣾⣿⡇⠀⢸⣿⡿⠀⠀⡀⠙⣿⣿⡆
⠀⠀⢠⣿⣿⣿⠿⣿⣿⣿⡄⠀⠀⠀ ⠙⢿⣿⣿⠇⠈⠿⣿⣿⡿⠋⠀⠀⢿⣿⡿⠁⠀⢸⣿⣿⣿⡇⢸⣿⣿⠀⣿⣿⣄⣾⣿⠛⠛⣿⣿⢠⣿⣿⣿ ⣼⣿⣿⣿ ⣿⣿⡿⠋⠀
⠀⢀⣾⠟⠋⠀⠀⠀⠙⠻⣷⡀⠀⠀
 
  v0.6.5

🔍 Detected coverage file: coverage.xml
🔍 Detected coverage file: .coverage
⭐️ Running in parallel mode. You must call the webhook after all jobs finish: `coveralls done --build-number a9d8d667231d570840241cfe367b8b7749422729`
  ·job_flag: infrahubctl-unit
🚀 Posting coverage data to https://coveralls.io/api/v1/jobs
⚠️ Internal server error. Please contact Coveralls team.
Error: Process completed with exit code 1.
```

Unfortunately GitHub Actions doesn't have a proper way to signal that a job completed with failure, so this will hide the error if it starts to always fail.
