### ISSUE TITLE
bug: Python SDK `all()` returns duplicate results

### ISSUE THREAD

**Issue by mngan** [opsmill/infrahub#1160]
### Current Behavior

After loading up some test data, calling: 
```
rack_groups = self.infrahub.all(kind="InfraRackGroup", branch=self.branch)
```
will return multiple instances of the same rack groups. 

```
>>> len(rack_groups)
156
>>> s=set([rg.id for rg in rack_groups])
>>> len(s)
103
>>> [print(rg.id) for rg in rack_groups if rg.patchmanager_id.value==6233204]
17885724-3805-b542-3034-d8ef0d9175c6
17885724-3805-b542-3034-d8ef0d9175c6
```

### Expected Behavior

I would expect that fetching all the objects would return a unique list of all the objects. 

### Steps to Reproduce

Using this schema 
```
generics:
  - name: Patchmanager
    namespace: Infra
    description: "Generic Patchmanager Type"
    attributes:
      - name: patchmanager_id
        kind: Number
        unique: true
        optional: false
nodes:
  - name: RackGroup
    namespace: Infra
    description: "Rack Group"
    label: "Rack Group"
    order_by:
      - name__value
    display_labels:
      - name__value
    inherit_from:
      - InfraPatchmanager
    attributes:
      - name: name
        kind: Text
        optional: false
      - name: slug
        kind: Text
        optional: false
    relationships:
      - name: racks
        peer: InfraRack
        optional: true
        identifier: "rack_group__rack"
        cardinality: many
        kind: Component
      - name: site
        peer: InfraSite
        optional: false
        identifier: "site__rack_group"
        cardinality: one
        kind: Parent
  - name: Rack
    namespace: Infra
    description: "Rack"
    label: "Rack"
    order_by:
      - name__value
    display_labels:
      - name__value
    inherit_from:
      - InfraPatchmanager
    attributes:
      - name: name
        kind: Text
        optional: false
    relationships:
      - name: rack_group
        peer: InfraRackGroup
        optional: false
        kind: Parent
        identifier: "rack_group__rack"
```

loading in some data populating racks into each rack group
query all the rack groups
check to see if the results are unique
