### ISSUE TITLE
task: Split apart exceptions for type hints into smaller components

### ISSUE THREAD

**Issue by ogenstad** [opsmill/infrahub#1366]
### Component

API Server / GraphQL

### Task Description

Within the main pyproject.toml file there are a number of sections dedicated to type hints where we have excluded entire paths from the checks. These are:

```toml
[[tool.mypy.overrides]]
module = "infrahub.api.*"
ignore_errors = true

[[tool.mypy.overrides]]
module = "infrahub.core.*"
ignore_errors = true

[[tool.mypy.overrides]]
module = "infrahub.git_credential.*"
ignore_errors = true

[[tool.mypy.overrides]]
module = "infrahub.graphql.*"
ignore_errors = true

[[tool.mypy.overrides]]
module = "infrahub.message_bus.operations.*"
ignore_errors = true
```

The end goal is that all of these would be deleted so that we have complete type checking throught the code, but getting there will require some amount of work. Before getting there it could be overwhelming to fix everything within the core or everything within the api in one go. We should split any of these sections with a `*` apart and instead include the individual modules. Once that is done we can work on correcting/adding type hints to each file in isolation.
