### ISSUE TITLE
task: Upgrade version of nodejs and possibly npm

### ISSUE THREAD

**Issue by ogenstad** [opsmill/infrahub#1392]
### Task Description

In ./development/Dockerfile we are using node16:

```Dockerfile
FROM docker.io/node:16-slim AS frontend
```

We also pin the version to npm 9, I think there might have been some breaking change in 10. Not sure if we need to perform some action if later versions of node doesn't support this version.

```Dockerfile
RUN npm install -g npm@v9.8.1
```

We also have a few instances of node 16 in the CI in .github/workflows/ci.yml

```yaml
  E2E-testing-neo4j:
    needs: ["frontend-tests", "backend-tests-default", "python-sdk-tests"]
    if: |
      always() && !cancelled() &&
      !contains(needs.*.result, 'failure') &&
      !contains(needs.*.result, 'cancelled')
    runs-on: "runner-ubuntu-8-32"
    timeout-minutes: 40
    env:
      INFRAHUB_DB_TYPE: neo4j
    steps:
      - name: "Check out repository code"
        uses: "actions/checkout@v3"
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 16
```

We should use a supported LTS i.e. long time support version of node. As per https://endoflife.date/nodejs the end of active support for node 18 just expired, though security updates will still be avaiable for some time. For the 16 version that we are using both the active support and security support has expired.

Based on this it seems like we should use 20 (LTS), though I don't know if or what changes might be needed before we get there.
