### ISSUE TITLE
task: Remove repository property for rfiles in .infrahub.yml

### ISSUE THREAD

**Issue by ogenstad** [opsmill/infrahub#1416]
### Component

Git Integration

### Task Description

A typicall .infrahub.yml file located in an external repository can look like this:

```yaml
rfiles:
  - name: device_startup
    description: "Template to generate startup configuration for network devices."
    query: "device_startup_info"
    repository: "self"
    template_path: "templates/device_startup_config.tpl.j2"

  - name: clab_topology
    query: "topology_info"
    repository: "self"
    template_path: "topology/topology.tpl.j2"
```

When importing the rfile we replace this `self` value with the id of the repository within Infrahub. However with the current setup it would also be possible to set this value to that of another repository.

Within the code when evaluating which rfiles to keep in the case that they have been removed from the repository we have some logic that searches for rfiles tied to the current repository:

```python
        LOGGER.debug(f"{self.name} | Importing all RFiles in branch {branch_name} ({commit}) ")

        schema = await self.client.schema.get(kind="CoreRFile", branch=branch_name)

        rfiles_in_graph = {
            rfile.name.value: rfile
            for rfile in await self.client.filters(kind="CoreRFile", branch=branch_name, repository__ids=[str(self.id)])
        }
```

If a user would have used a different value for the repository of a given rfile that rfile wouldn't be included in this list. Also if that other repository got a new commit the rfile would be deleted.

I'd want to remove this key all together and instead always have the importer set the correct repository ID.

Are you ok with that @dgarros?
