### ISSUE TITLE
task: Consider removing INFRAHUB_CHECKS & INFRAHUB_TRANSFORMS variables

### ISSUE THREAD

**Issue by ogenstad** [opsmill/infrahub#1559]
### Component

Git Integration, infrahubctl CLI

### Task Description

In the current codebase you have to specify a list of classes within either a variable called `INFRAHUB_CHECKS` for checks https://github.com/opsmill/infrahub-demo-edge/blob/main/checks/check_backbone_link_redundancy.py#L52 or `INFRAHUB_TRANSFORMS` for transforms https://github.com/opsmill/infrahub-demo-edge/blob/main/transforms/openconfig.py#L106

I think the reasoning behind this might have been that both of these used to be auto imported and that import code needed a deterministic way to find the correct checks. However now we have moved this logic into .infrahub.yml which would let us point to the class name within each section within that file.

Some benefits of this is that the code to manage these classes can be simplified a bit. The other reason is when we use the `infrahubctl` command.

Using `infrahubctl render` let's us specify the name of the rfile to render as it is defined in .infrahub.yml. However with `infrahubctl transform` we can't use a name that is defined within .infrahub.yml instead we use the name of the class. So a user would need to look in different locations.

Instead of having this like we do today:

```yaml
---
check_definitions:
  - file_path: "checks/check_backbone_link_redundancy.py"

python_transforms:
  - file_path: "transforms/openconfig.py"
 ```

I'd suggest that we change this to:

```yaml
check_definitions:
  - name: backbone_link_redundancy
    file_path: "checks/check_backbone_link_redundancy.py"
    class_name: "InfrahubCheckBackboneLinkRedundancy" (can default to "Check" if not specified)

python_transforms:
  - name: oc_interfaces
    file_path: "transforms/openconfig.py"
    class_name: "OCInterfaces"  (can default to "Transform" if not specified)
  - name: oc_bgp_neighbors
    file_path: "transforms/openconfig.py"
    class_name: "OCBGPNeighbors"
 ```

That way a user would be able to run `infrahubctl transform oc_interfaces` without having to first check what the class is called. 

Any thoughts?
