### ISSUE TITLE
bug: A schema with multiple generics with the same attribute of different kinds cause GraphQL API to stop working

### ISSUE THREAD

**Issue by ogenstad** [opsmill/infrahub#1563]
### Component

API Server / GraphQL

### Current Behavior

If you load a schema where an object inherits from multiple generics and both these generics define an attribute that doesn't look exactly the same the GraphQL application stops working and always responds with an error message like this:

```json
{
  "data": null,
  "errors": [
    {
      "message": "Interface field TestStatus.choice expects type NumberAttribute but TestWidget.choice is type TextAttribute."
    }
  ]
}
```

### Expected Behavior

The schema validator should reject a schema like this.

### Steps to Reproduce

Load the following yaml file with `infrahubctl schema load`.

```yaml
---
version: '1.0'
generics:
  - name: Adapter
    namespace: Test
    display_labels:
      - name__value
    order_by:
      - name__value
    attributes:
      - name: name
        kind: Text
      - name: choice
        kind: Text
        optional: true
  - name: Status
    namespace: Test
    display_labels:
      - label__value
    order_by:
      - label__value
    attributes:
      - name: label
        kind: Text
      - name: choice
        kind: Number
        optional: true

nodes:
  - name: Widget
    namespace: Test
    description: "A Circuit endpoint is attached to each end of a circuit"
    attributes:
      - name: widget
        kind: Text
    inherit_from:
      - "TestAdapter"
      - "TestStatus"
```
