### ISSUE TITLE
task: Move infrahub-sync to a separate pyproject.toml file

### ISSUE THREAD

**Issue by ogenstad** [opsmill/infrahub#1587]
### Task Description

Currently we have this poetry group defined within our main pyproject.toml file for Infrahub:

```toml
[tool.poetry.group.sync.dependencies]
dagster = "^1.1.19"
dagit = "^1.1.19"
structlog = "^22.3.0"
pynetbox = "^7.0.1"
pynautobot = "^1.5.0"
diffsync = "^1.8.0"
```

This is holding us back and preventing progress in other parts of the code as diffsync doesn't yet support Pydantic v2.x. The SDK has already been moved into a new location because of this.

As there are some minor changes around how metadata is handled around Pydantic 2.x we have waited with certain steps such as generating documentation based on Pydantic models, and also to avoid duplicated code that might today be defined both as Pydantic v1 models and dictionaries. Also the general performance improvements with Pydantic v2 wouldn't hurt.
