### ISSUE TITLE
bug: Relationship of kind Generic with a cardinality of One is missing the detailed view

### ISSUE THREAD

**Issue by dgarros** [opsmill/infrahub#1740]
### Component

Frontend UI

### Current Behavior

it looks like the relationship of kind `Generic` with a cardinality of `One` aren't displayed in the detailed view. 

Based on the documentation - https://docs.infrahub.app/reference/schema/#relationship-kinds
Relationship of kind `Generic` with a cardinality of `one` should be displayed in the detailed view but not in the list view

In the screenshot below, showing a BGPSession object from the infrastructure_base schema. The relationship `device` is missing.

![Screenshot 2023-12-28 at 14 44 33](https://github.com/opsmill/infrahub/assets/304126/70291696-f278-4cc2-8cfa-c820a761fe2f)

Here is the current schema for the BGPSession model
```yaml
  - name: BGPSession
    namespace: Infra
    description: "A BGP Session represent a point to point connection between two routers"
# [...]
    attributes:
      - name: type
        kind: Text
        enum: [EXTERNAL, INTERNAL]
# [...]
    relationships:
# [...]
      - name: device
        peer: InfraDevice
        optional: true
        cardinality: one
# [...]
```

### Expected Behavior

All relationship if kind `Generic` with a cardinality of `one` should be displayed in the detailed view
