### ISSUE TITLE
bug: Fetching optional cardinalify=one relationships raises error if no relationship exist

### ISSUE THREAD

**Issue by ogenstad** [opsmill/infrahub#1878]
### Component

Python SDK

### Current Behavior

If you have a schema that has an optional cardinality=one relationship and try to query for these objects when one of the objects doesn't have a relationship set the SDK will raise an error.

```python

from infrahub_sdk import InfrahubClient

client = InfrahubClient()

widgets = await client.all(
    kind="TestWidget",
    prefetch_relationships=True,
    populate_store=True,
)

AttributeError                            Traceback (most recent call last)
Cell In[4], line 5
      1 from infrahub_sdk import InfrahubClient
      3 client = InfrahubClient()
----> 5 widgets = await client.all(
      6     kind="TestWidget",
      7     prefetch_relationships=True,
      8     populate_store=True,
      9 )

File ~/Code/opsmill/infrahub/python_sdk/infrahub_sdk/client.py:239, in InfrahubClient.all(self, kind, at, branch, populate_store, offset, limit, include, exclude, fragment, prefetch_relationships)
    209 async def all(
    210     self,
    211     kind: str,
   (...)
    220     prefetch_relationships: bool = False,
    221 ) -> List[InfrahubNode]:
    222     """Retrieve all nodes of a given kind
    223
    224     Args:
   (...)
    237         List[InfrahubNode]: List of Nodes
    238     """
--> 239     return await self.filters(
    240         kind=kind,
    241         at=at,
    242         branch=branch,
    243         populate_store=populate_store,
    244         offset=offset,
    245         limit=limit,
    246         include=include,
    247         exclude=exclude,
    248         fragment=fragment,
    249         prefetch_relationships=prefetch_relationships,
    250     )

File ~/Code/opsmill/infrahub/python_sdk/infrahub_sdk/client.py:346, in InfrahubClient.filters(self, kind, at, branch, populate_store, offset, limit, include, exclude, fragment, prefetch_relationships, **kwargs)
    339 query = Query(query=query_data)
    340 response = await self.execute_graphql(
    341     query=query.render(),
    342     branch_name=branch,
    343     at=at,
    344     tracker=f"query-{str(schema.kind).lower()}-page{page_number}",
    345 )
--> 346 _process_result: ProcessRelationsNode = await self._process_nodes_and_relationships(
    347     response=response,
    348     schema_kind=schema.kind,
    349     branch=branch,
    350     prefetch_relationships=prefetch_relationships,
    351 )
    352 nodes.extend(_process_result["nodes"])
    353 related_nodes.extend(_process_result["related_nodes"])

File ~/Code/opsmill/infrahub/python_sdk/infrahub_sdk/client.py:205, in InfrahubClient._process_nodes_and_relationships(self, response, schema_kind, branch, prefetch_relationships)
    202     nodes.append(node)
    204     if prefetch_relationships:
--> 205         await node._process_relationships(node_data=item, branch=branch, related_nodes=related_nodes)
    207 return ProcessRelationsNode(nodes=nodes, related_nodes=related_nodes)

File ~/Code/opsmill/infrahub/python_sdk/infrahub_sdk/node.py:1235, in InfrahubNode._process_relationships(self, node_data, branch, related_nodes)
   1233 rel = getattr(self, rel_name)
   1234 if rel and isinstance(rel, RelatedNode):
-> 1235     related_node = await InfrahubNode.from_graphql(
   1236         client=self._client, branch=branch, data=node_data["node"].get(rel_name)
   1237     )
   1238     related_nodes.append(related_node)
   1239 elif rel and isinstance(rel, RelationshipManager):

File ~/Code/opsmill/infrahub/python_sdk/infrahub_sdk/node.py:965, in InfrahubNode.from_graphql(cls, client, branch, data, schema)
    956 @classmethod
    957 async def from_graphql(
    958     cls,
   (...)
    962     schema: Optional[Union[NodeSchema, GenericSchema]] = None,
    963 ) -> Self:
    964     if not schema:
--> 965         node_kind = data.get("__typename", None) or data.get("node", {}).get("__typename", None)
    966         if not node_kind:
    967             raise ValueError("Unable to determine the type of the node, __typename not present in data")

AttributeError: 'NoneType' object has no attribute 'get'
```

### Expected Behavior

We should fetch the relationships for instances where they exist and ignore any instance that is missing a relationship.

### Steps to Reproduce

1. Load a schema that looks like this:

```yaml
---
version: '1.0'

nodes:
  - name: Widget
    namespace: Test
    label: "Widget"
    default_filter: name__value
    order_by:
      - name__value
    display_labels:
      - name__value
    attributes:
      - name: name
        kind: Text
        unique: true
    relationships:
      - name: container
        peer: TestContainer
        optional: true
        cardinality: one
        kind: Attribute
  - name: Container
    namespace: Test
    label: "Container"
    default_filter: name__value
    order_by:
      - name__value
    display_labels:
      - name__value
    attributes:
      - name: name
        kind: Text
        unique: true
```

2. Create objects

Create one container object
Create one widget object that has a relationship to the container object
create another widget object that does not have a relationship with the container object.

3. Run the above Python script in ipython

### Additional Information

For refence this is what the database looked like:

```graphql
query MyQuery {
  TestWidget {
    edges {
      node {
        name {
          value
        }
        container {
          node {
            name {
              value
            }
          }
        }
      }
    }
  }
}
```

Response:

```json
{
  "data": {
    "TestWidget": {
      "edges": [
        {
          "node": {
            "name": {
              "value": "hammer"
            },
            "container": {
              "node": {
                "name": {
                  "value": "box"
                }
              }
            }
          }
        },
        {
          "node": {
            "name": {
              "value": "wrench"
            },
            "container": {
              "node": null
            }
          }
        }
      ]
    }
  }
}
```
