### ISSUE TITLE
task: Change issue templates to adhere to our documentation standards

### ISSUE THREAD

**Issue by ogenstad** [opsmill/infrahub#1929]
### Task Description

We should update our issue templates to adhere to our documentation standards with regards to headers and dynamic fields.

This is purely for consistency with how do to it with the docs. In the below example the "API Server" would be "API server", "Additional Information" -> "Additional information".

```yaml
---
name: 💡 Feature Request
description: Suggest a feature for Infrahub
title: 'feature: '
labels: ["type/feature"]
body:
  - type: dropdown
    attributes:
      label: Component
      description: Please indicate which component(s) this feature is associated with (leave blank if unknown)
      multiple: true
      options:
        - Frontend UI
        - API Server / GraphQL
        - Git Integration
        - Python SDK
        - infrahubctl CLI
        - Not Sure
  - type: textarea
    attributes:
      label: Describe the Feature Request
      description: A clear and concise description of what the feature does.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe the Use Case
      description: A clear and concise use case for what problem this feature would solve.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional Information
      description: |
        List any other information that is relevant to your request.
        Stack traces, related issues, suggestions on how to implement, Stack Overflow links, forum links, etc.
```

Another thing is that the above templates created H3 headers, i.e. `###` in markdown. This means that when writing an issue you don't don't have as many header options below the current one. Potentially we could use markdown from (https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-githubs-form-schema). and remove the labels (if that is possible) so that we could control the header types and change these to `##` instead.
