### ISSUE TITLE
task: Dependency management for Infrahub and the Python SDK

### ISSUE THREAD

**Issue by ogenstad** [opsmill/infrahub#1935]
### Component

API Server / GraphQL, Python SDK

### Task Description

We use Python Poetry both for the Infrahub core as well as the Python SDK, however the strategies we use to manage the dependencies should be different.

### Infrahub Core

As a bundled application that will typically run within a Docker container we want to ensure that everything is running on exactly the version that we are testing with to avoid any surprises brought on by breaking changes in any of the libraries that we depend on.

While we shouldn't use more components that are required, and limit the number of third party components when possible it is generally file to install everything defined within the package dependency definitions.

#### Infrahub pyproject groups

Now that the SDK has moved out from the root pyproject.toml we could server group and move those dependencies back into a main group. Potentially we could have one group for server that's specific to the API server and another one that's specific to the Git agents, this would however require us to have two different Docker images which we probably don't want regardless, so it should be fine with a "main" group.

### Infrahub SDK - Python SDK

As a library we want the SDK to be able to be installed as part of Infrahub as it is used in the Git agents, but also on in other environments where customers might use the SDK as part of another solution. In this situation we want the supported third party packages to be as broad as possible. For example with restrictions like this:

```toml
rich = "^13.3"
pendulum = "~3.0"
```

It could be that we'll have customers who will want to run rich 14.x (provided that the API looks the same) and pendulum 3.1.x, and it might be impossible to install the Infrahub SDK due to conflicting requirements in other libraries that the customers want to use. For this reason we should try support as broad a range as possible. 

Another issue is that we are installing a fairly large number of dependencies for the SDK, this is not counting all the dependencies that our primary dependencies require:

```toml
[tool.poetry.dependencies]
python = "^3.8"
httpx = "^0.23"
rich = "^13.3"
pendulum = "~3.0"
typer = "^0.7"
Jinja2 = "^3.1.3"
toml = "^0.10.2"
jsonlines = "^3.1"
deepdiff = "^6.2"
ujson = "^5.7"
pydantic = ">=1.7.4,!=1.8,!=1.8.1,!=2.0.0,!=2.0.1,!=2.1.0,<3.0.0"
pyyaml = "^6.0"
gitpython = "^3.1.41"
pyarrow = "^14.0.1"
numpy = [
    { version = "^1.24.2", python = ">=3.8,<3.12" },
    { version = "^1.26.2", python = ">=3.12" }
]
graphql-core = "^3.2.3"
```

Depending on what a user wants to do all of these might make sense. I.e. infrahubctl would use `rich` and typer `typer`. Where as someone who only wants to use our SDK to communicate with Infrahub would require httpx (for communication) and pydantic (for config), but might not want to install Jinja2, deepdiff, gitpython, numpy etc.

For this reason it would be better if we could group some of these dependencies into an extras section so that it's possible to install both a minimal SDK but also a full version that would include all the command line tools, the rich text support and later pytest for testing.
