### ISSUE TITLE
bug: Order_weight is not used to order attribute and relationships

### ISSUE THREAD

**Issue by BeArchiTek** [opsmill/infrahub#1948]
### Component

Frontend UI

### Current Behavior

The order_weight is honoured for each type but they don't mix
![image](https://github.com/opsmill/infrahub/assets/1334310/761fe7c3-696b-48c3-b56b-8faa4da21902)
![image](https://github.com/opsmill/infrahub/assets/1334310/a321ffbd-66cf-4ae4-8ca5-cc3f4e4f4db4)

### Expected Behavior

Be able to have relationships mix with attribute if I want to :)

### Steps to Reproduce

- Load the base schema
- Load this extra schema :
```yaml
- name: DeviceType
    namespace: Template
    description: "A model of device"
    label: "Device Type"
    icon: "mdi:poll"
    menu_placement: "InfraDevice"
    display_labels:
      - name__value
    order_by:
      - name__value
    attributes:
      - name: name
        kind: Text
        unique: false
        order_weight: 1000
      - name: description
        kind: Text
        optional: true
        order_weight: 1100
      - name: part_number
        label: Part Number
        optional: true
        kind: Text
        order_weight: 1200
      - name: height
        label: "Height (U)"
        optional: true
        kind: Number
        order_weight: 1400
      - name: full_depth
        label: "Full Depth"
        default_value: true
        kind: Boolean
        order_weight: 1500
      - name: weight
        label: "Weight (kg)"
        optional: true
        kind: Number
        order_weight: 1600
    relationships:
      - name: platform
        peer: InfraPlatform
        cardinality: one
        kind: Component
        order_weight: 1300
      - name: tags
        peer: BuiltinTag
        optional: true
        cardinality: many
        kind: Attribute
        order_weight: 2000
```
