### ISSUE TITLE
feature: Add validator to ensure that display_labels is valid

### ISSUE THREAD

**Issue by dgarros** [opsmill/infrahub#195]
### Component

API Server / GraphQL

### Describe the Feature Request

Currently we are not validating the content of `display_labels` on a NodeSchema and as a result we end-up with some error messages when we tried to access an object.

### Describe the Use Case

Improve use experience by catching invalid schema as soon as possible

**Comment by FragmentedPacket** [comment]
I'll start working on this

**Comment by FragmentedPacket** [comment]
I believe this might already be implemented.

Below are the results:

```yaml
---
version: '1.0'
nodes:
  - name: Instance
    namespace: Cloud
    display_labels:
      - "statuses__value"
    attributes:
      - name: name
        kind: Text
      - name: status
        kind: Text
```

```shell
root@9ce2c17a1429:/source# infrahubctl schema load /tmp/schema.yml 
Unable to load the schema:
  CloudInstance.display_labels: statuses__value is invalid on schema CloudInstance
```

and

```yaml
---
version: '1.0'
nodes:
  - name: Instance
    namespace: Cloud
    display_labels:
      - "status__values"
    attributes:
      - name: name
        kind: Text
      - name: status
        kind: Text
```

```shell
root@9ce2c17a1429:/source# infrahubctl schema load /tmp/schema.yml 
Unable to load the schema:
  CloudInstance.display_labels: values is not a valid property of status
```

and

```yaml
---
version: '1.0'
generics:
  - name: Generic
    namespace: Cloud
    display_labels:
      - "status__values"
    attributes:
      - name: "provider"
        kind: Text
nodes:
  - name: Instance
    namespace: Cloud
    attributes:
      - name: name
        kind: Text
      - name: status
        kind: Text
```

```shell
Unable to load the schema:
  CloudGeneric.display_labels: status__values is invalid on schema CloudGeneric
```

https://github.com/opsmill/infrahub/blob/develop/backend/infrahub/core/schema_manager.py#L645-L666
