### ISSUE TITLE
bug: Unable to generate GraphQL mutation for relationships of kind=Component

### ISSUE THREAD

**Issue by ogenstad** [opsmill/infrahub#2006]
### Component

Python SDK

### Current Behavior

If a relationship is defined as a component and you try to save a node using this relationship with the SDK the relationship will be filtered out from the GraphQL mutation and not included.

In the demo data this is related to untagged_vlans in the InterfaceL2 model.

This bug would be due to https://github.com/opsmill/infrahub/blob/d5cd236c62e7c0bc8a9ef5e7b612d78083b82bfa/python_sdk/infrahub_sdk/node.py#L739

### Expected Behavior

All of these relationships should be correctly sent to the API server.

### Steps to Reproduce

1. Load a model as below using infrahubctl schema load

```yaml
---
version: '1.0'
nodes:
  - name: Container
    namespace: Test
    default_filter: name__value
    display_labels:
      - name__value
    order_by:
      - name__value
    attributes:
      - name: name
        label: Name
        kind: Text
  - name: Widget
    namespace: Test
    display_labels:
      - name__value
    order_by:
      - name__value
    attributes:
      - name: name
        label: Name
        kind: Text
    relationships:
      - name: container
        peer: TestContainer
        optional: true
        cardinality: one
        kind: Component
  - name: Wrench
    namespace: Test
    display_labels:
      - name__value
    order_by:
      - name__value
    attributes:
      - name: name
        label: Name
        kind: Text
    relationships:
      - name: container
        peer: TestContainer
        optional: true
        cardinality: one
        kind: Parent
```

2. Run this Python script:

```python
from infrahub_sdk import InfrahubClientSync

client = InfrahubClientSync(address="http://localhost:8000")
container_name = "black-box"
container_data = {
    "name": container_name,
}
container = client.create(kind="TestContainer", data=container_data)
container.save()

widget_data = {
    "name": "widget1",
    "container": container_name
}
widget = client.create(kind="TestWidget", data=widget_data)
widget.save()

wrench_data = {
    "name": "wrench1",
    "container": container_name
}
widget = client.create(kind="TestWrench", data=wrench_data)
widget.save()
```

3. Validate the objects in the database and note that wrench1 has a relationship to the black-box container but widget1 does not.

### Additional Information

#1863 would be nice to fix to troubleshoot issues like this easier.
