### ISSUE TITLE
feature: Show a hierarchical node's parent/child relationship in the frontend

### ISSUE THREAD

**Issue by wvandeun** [opsmill/infrahub#2007]
### Component

Frontend UI

### Describe the Feature Request

When opening the list and/or detailed view of a hierarchical node, the related parent/child nodes are not visible. 

### Describe the Use Case

When using the this schema
```yaml
version: '1.0'
generics:
  - name: Location
    namespace: Test
    description: "TestLocation"
    label: "Location"
    icon: "mingcute:location-line"
    include_in_menu: true
    hierarchical: true
    display_labels:
      - name__value
    order_by:
      - name__value
    attributes:
      - name: name
        kind: Text
      - name: description
        kind: Text
        optional: true

nodes:
  - name: Country
    namespace: Test
    inherit_from:
      - TestLocation
    description: "Country"
    label: "Country"
    parent: ""
    children: "TestSite"
    display_labels:
      - name__value
  - name: Site
    namespace: Test
    inherit_from:
      - TestLocation
    description: "Site"
    parent: "TestCountry"
    children: ""
```
and creating a country node and 5 site nodes, that have the country defined as parent node. 
We should be able to see the 5 child site nodes when going in the detailed view of the country node.
We should be able to see the parent country node when going in the detailed view of each site node.
We could potentially have the parent node available in the list view of the child node as well.

This should make it possible to see the related parent / child nodes of a hierarchical node in the frontend, which is not possible at this stage.
