### ISSUE TITLE
bug: display_labels property defined on a generic is not properly inherited by an inheriting node

### ISSUE THREAD

**Issue by wvandeun** [opsmill/infrahub#2008]
### Component

API Server / GraphQL

### Current Behavior

`display_labels` property defined on a generic does not seem to be properly inherited by a node.
The `display_label` attribute of a node inheriting from such a generic, is a combination of the kind and the id of the node.
This is visible when querying for the `display_label` attribute of a node using GraphQL, or in the UI where the `display_label` attribute of a node is used for some components. 

### Expected Behavior

The `display_labels` property defined on the generic should be inherited by the node that inherits from the generic.

### Steps to Reproduce

1. Load the following schema
```yaml
# yaml-language-server: $schema=https://schema.infrahub.app/develop/schema.schema.json
---
version: '1.0'
generics:
  - name: Location
    namespace: Test
    display_labels:
      - name__value
    attributes:
      - name: name
        kind: Text
nodes:
  - name: Country
    namespace: Test
    inherit_from:
      - TestLocation
    description: "Country"
    label: "Country"
```
2. Create a TestCountry node
3. Execute the following GraphQL node
```
query {
  TestCountry {
    edges {
      node {
        display_label
      }
    }
  }
}
```
4. The result will look like similar to this
```
{
  "data": {
    "TestCountry": {
      "edges": [
        {
          "node": {
            "display_label": "TestCountry(ID: 17acccdb-8b0c-b14e-3727-c516f5f16bb4)"
          }
        }
      ]
    }
  }
}
```
