### ISSUE TITLE
feature: Extend uniqueness constraints in the schema

### ISSUE THREAD

**Issue by dgarros** [opsmill/infrahub#2011]
### Component

API Server / GraphQL

### Describe the Feature Request

Currently it's possible to indicate individual attribute as unique for a given model in the schema. The goal is to extend this feature allow more complex uniqueness constraints beyond a single attribute.

The new uniqueness constraint should move at the node level and allow a list of fields to be provided

In addition to local attributes, it should be possible to use relationship of cardinality one, as long as it's mandatory.
The current attribute `unique` on an attribute should be completely removed to avoid any confusion.

A relationship of cardinality one will be identified by its name.

For example for an interface node, connected to a device, the schema would look like this
```yaml
  - name: Interface
    namespace: Infra
    unique_constraint: ["device", "name__value"]
    attributes:
      - name: name
        kind: Text
    relationships:
      - name: device
        peer: InfraDevice
        optional: false
        cardinality: one
        kind: Parent
```

### Describe the Use Case

Allow more complex uniqueness constraints to be defined, using both local attributes and relationship of cardinality one.
Currently it's not possible to enforce the uniqueness of an interface attached to a device
