### ISSUE TITLE
bug: parent relation not selected in edit form of a hierarchical node

### ISSUE THREAD

**Issue by wvandeun** [opsmill/infrahub#2013]
### Component

Frontend UI

### Current Behavior

When you edit a hierarchical node int the frontend, which has a parent relation defined,  then the parent is not properly selected in the parent dropdown field in the edit form.

### Expected Behavior

The parent dropdown field in the node edit form has the proper parent selected, when you open the edit form for a hierarchical node.

### Steps to Reproduce

1. Load this schema into an Infrahub instance
```yaml
---
version: '1.0'
generics:
  - name: Location
    namespace: Test
    hierarchical: true
    display_labels:
      - name__value
    attributes:
      - name: name
        kind: Text
nodes:
  - name: Country
    namespace: Test
    inherit_from:
      - TestLocation
    description: "Country"
    label: "Country"
    parent: ""
    children: "TestSite"
    display_labels:
      - name__value
  - name: Site
    namespace: Test
    inherit_from:
      - TestLocation
    description: "Site"
    parent: "TestCountry"
    children: ""
    display_labels:
      - name__value
```
2. create a country node
```python
country = client.create(kind="TestCountry", data={"name": "France"})
country.save()
```
3. create a site node, with the country node as parent
```python
site = client.create(kind="TestSite", data={"name": "Paris", "parent": {"id": country.id}})
site.save()
```
4. Open the site node in the UI
5. Click the edit button. The parent dropdown does not have the country selected.
