### ISSUE TITLE
bug: unable to create nodes with a checkbox attribute 

### ISSUE THREAD

**Issue by wvandeun** [opsmill/infrahub#2129]
### Component

API Server / GraphQL

### Current Behavior

Considering this schema
```yaml
---
version: "1.0"
nodes:
  - name: Node
    namespace: Infra
    attributes:
      - name: myattr
        label: InfraNode Attribute
        kind: Checkbox
```

When you try to create a node of this type, using a create mutation with a value for `myattr` specified, you get an error message "myattr is not of type Checkbox at myattr".

```graphql
mutation {
  InfraNodeCreate(data: {myattr: {value: true}}) {
    ok
  }
}
```

### Expected Behavior

The create mutation should succesfully create the node when a value for the `myattr` checkbox attribute is provided. 

### Steps to Reproduce

1. Start a demo environment `inv demo.start`
2. Load the above schema `infrahubctl schema load <path>`
3. Execute this graphql mutation
```graphql
mutation {
  InfraNodeCreate(data: {myattr: {value: true}}) {
    ok
  }
}
```
