### ISSUE TITLE
bug: Form to create a related object isn't working properly

### ISSUE THREAD

**Issue by dgarros** [opsmill/infrahub#2241]
### Component

Frontend UI

### Current Behavior

In the latest 0.11 release the form to create a related object from an object form isn't working properly
Instead of staying on the left side of the main form, it will go over it and it won't close properly

I did a quick video to show the problem
https://www.loom.com/share/a3382a6237bf4286aa6d25c93982050d?sid=9abfe03a-1cb3-4cdb-9fcd-81d145b68e3f

### Steps to Reproduce

- Load the schema below from a default instance of infrahub
- Open a form to add an organization
- Open a form to create a tag within the first form

```
version: '1.0'
nodes:
  - name: Organization
    namespace: Core
    label: Organization
    description: "An organization represent a legal entity, a company"
    default_filter: name__value
    display_labels: [label__value]
    order_by: [name__value]
    icon: mdi:domain
    include_in_menu: true
    attributes:
      - kind: Text
        name: name
        unique: true

    relationships:
      - cardinality: many
        kind: Attribute
        name: tags
        optional: true
        peer: BuiltinTag
```
