### ISSUE TITLE
When loading schema with an attribute named ID, it returns an 500 error

### ISSUE THREAD

**Issue by bilalabbad** [opsmill/infrahub#2347]
### Component

API Server / GraphQL

### Current Behavior

When loading schema with infrahubctl using:
```
    attributes:
      - name: id
        kind: ID
        optional: true
```

it returns:
```
HTTPStatusError: Server error '500 Internal Server Error' for url 'http://localhost:8000/api/schema/load?branch=main'
For more information check: https://httpstatuses.com/500
```

### Expected Behavior

The "id" is always present on a node and shouldn't be specified. The backend should provide a friendlier error. 

### Steps to Reproduce

try to load a schema contains attribute named ID like:
```
    attributes:
      - name: id
        kind: ID
        optional: true
```
