### ISSUE TITLE
bug: HTTP 500 internal server error when loading schema with invalid namespace

### ISSUE THREAD

**Issue by wvandeun** [opsmill/infrahub#2462]
### Component

API Server / GraphQL

### Current Behavior

The rest api endpoint /schema/load returns an HTTP 500 status code when loading a schema with an invalid namepsace for a node.

### Expected Behavior

The API server should return a client side error (422?) when an invalid schema is provided. 

### Steps to Reproduce

- create the following schema file
```yaml
# yaml-language-server: $schema=https://schema.infrahub.app/develop/schema.schema.json
---
version: '1.0'
nodes:
  - name: Test
    namespace: TwoWords
    label: "Test"
    include_in_menu: true
    attributes:
      - name: "name"
        kind: "Text"
        unique: true
      - name: description
        kind: Text
        optional: true
```
- try to load the schema `infrahubctl schema load /path/to/schema.yml`
