### ISSUE TITLE
bug: multi-element uniqueness constraints doesn't work when an element is an attribute of kind Number

### ISSUE THREAD

**Issue by wvandeun** [opsmill/infrahub#2698]
### Component

API Server / GraphQL

### Current Behavior

When you define a multi-element uniqueness constraint on a node, for which one of the elements is an attribute of kind Number, then the uniqueness constraint doesn't seem to be enforced. The same uniqueness constraint does work when you change the kind of the attribute to Text.

### Expected Behavior

You should be able to define multi-element uniqueness constraint on a node for which one of the elements is an attribute of kind Number. 

### Steps to Reproduce

- start a demo environment `inv demo.start`
- load this schema
```yaml
---
version: "1.0"
nodes:
  - name: Policy
    namespace: Infra
    attributes:
      - name: name
        unique: true
        kind: Text
        optional: false
    relationships:
      - name: rules
        peer: InfraPolicyRule
        kind: Component
        cardinality: many

  - name: PolicyRule
    namespace: Infra
    uniqueness_constraints:
      - ["policy", "index__value"]
    attributes:
      - name: index
        kind: Number
        optional: false
    relationships:
      - name: policy
        peer: InfraPolicy
        kind: Parent
        cardinality: one
```
- run this script
```python
from infrahub_sdk import InfrahubClientSync

client = InfrahubClientSync.init()

policy = client.create("InfraPolicy", name="ABC")
policy.save()

policy_rule_1 = client.create("InfraPolicyRule", index=0, policy=policy)
policy_rule_1.save()

policy_rule_2 = client.create("InfraPolicyRule", index=0, policy=policy)
policy_rule_2.save()

rules = client.filters("InfraPolicyRule", policy__name__value="ABC", index__value=0)
print(f"Found {len(rules)} rules with index=0 and policy=ABC")
```
- running the script will not fail because the unique constraint is not enforced (or working)
- change the kind of the index attribute to "Text"
- change the python script (index argument on for create method should now be a string)
- running the script will fail because the unique constraint is violated
