### ISSUE TITLE
task: Remove unused labels in Github for CTL and PY-SDK

### ISSUE THREAD

**Issue by dgarros** [opsmill/infrahub#2758]
### Component

CI/CD

### Task Description

The 6 labels below were created initially to differentiate the issues related to the Python SDK or the infrahubctl commands but they aren't used anymore because a lot of things have changed in the project.

We should migrate all existings issues to their equivalent label and delete these from the project
```yaml
- name: "type/feature/ctl"
- name: "type/bug/ctl"
- name: "type/housekeeping/ctl"
- name: "type/feature/py-sdk"
- name: "type/bug/py-sdk"
- name: "type/housekeeping/py-sdk"
```
