### ISSUE TITLE
feature: complex constraints for required attributes / relationships of a node

### ISSUE THREAD

**Issue by wvandeun** [opsmill/infrahub#2773]
### Component

API Server / GraphQL

### Describe the Feature Request

We would like to have the ability to define more complex constraints on the required attributes or nodes of a relationship.
- "OR" constraint between the required constraint of 2 (or more) attributes/relationships (indicating one of these attributes or relationships is required)
- "AND" constraint on multiple OR constraints (indicating one of the OR constraint attributes/relationships is required AND something else, potentially another OR constraint

### Describe the Use Case

Today we can define that one or more attributes/relationships of a node are required. However, there are scenarios where constraints on required attributes/relationships are more complex:
1) On a L2 Interface I want to be able to define that a tagged vlan or an untagged vlan must be provided
2) On a firewall rule I want to be able to define that a source address or a source group AND a destination address or destination group must be provided

### Additional Information

A way to express this in the schema file could be:
```yaml
---
version: "1.0"
nodes:
  - name: Test
    namespace: Test
    required:
      - [name, short_name]
      - [other_node, another_node]
    attributes:
      - name: name
        kind: Text
      - name: short_name
        kind: Text
    relationships:
      - name: other_node
        peer: TestOtherNode
        cardinality: one
      - name: another_node
        peer: TestAnotherNode
        cardinality: one
```
