### ISSUE TITLE
bug: metadata is not correctly displayed for the related nodes of a relationship with cardinality many and kind Component

### ISSUE THREAD

**Issue by wvandeun** [opsmill/infrahub#2845]
### Component

Frontend UI

### Current Behavior

The metadata popup is not showing the correct data when you click on the metadata button of a related node of a relationship with cardinality many and kind component.

<img width="1252" alt="image" src="https://github.com/opsmill/infrahub/assets/7521270/2e9f0331-9460-4b48-a110-59cec04c7051">

### Expected Behavior

Metadata should be correctly displayed

### Steps to Reproduce

- Spin up an Infrahub instance
- Load the following schema
```yaml
---
version: "1.0"
nodes:
  - name: Node1
    namespace: Test
    attributes:
      - name: name
        kind: Text
        unique: true
    relationships:
      - name: related_nodes
        kind: Component
        peer: TestNode2
        cardinality: many
  - name: Node2
    namespace: Test
    attributes:
      - name: name
        kind: Text
        unique: true
```
- execute the following python script
```python
client = InfrahubClientSync.init()
admin = client.get("CoreAccount", name__value="admin")

node1 = client.create("TestNode1", name="node1")
node1.save()

node2 = client.create("TestNode2", name="node2")
node2.save()

node1.related_nodes.fetch()
node1.related_nodes.add({"id": node2.id, "is_protected": True, "owner": admin.id})
node1.save()
```
- open the webui
- go to Node1 list view
- got to the detailed view of node1
- click on the Related Nodes tab
- click on the metadata icon of node2
- notice that the update time is `invalid date`, is_protected is false and that no owner is displayed

### Additional Information

When you try to update the metadata on the relation in the UI, and click on the save button, the action never finishes
