### ISSUE TITLE
bug: attribute of kind Number with value 0 is not show properly in the node detail view

### ISSUE THREAD

**Issue by wvandeun** [opsmill/infrahub#2846]
### Component

Frontend UI

### Current Behavior

When you have a node with an attribute of kind Number, for which the value is 0, it will not be properly displayed in the detailed view of that node.
<img width="1245" alt="image" src="https://github.com/opsmill/infrahub/assets/7521270/e9d87c1f-a6c7-4640-aa2f-f70939656a6e">

For other values this does not seem to occur.

### Expected Behavior

The numeric value 0 should be shown

### Steps to Reproduce

- load the following schema
```yaml
---
version: "1.0"
nodes:
  - name: Node
    namespace: Test
    attributes:
      - name: number
        kind: Number
        unique: true
```
- create a TestNode with the number attribute set to 0
- navigate to the TestNode detailed view
- the number attribute will show "-" as value

### Additional Information

When you click on the edit button on the node detailed view, and then click on save, then the value of the value number field will be cleared and error message will be displayed stating that the Numer is required. The field should not be cleared in this case. This also doesn't seem to happen for other values than 0.
