### ISSUE TITLE
bug: Unable to use GraphQL query filter parent/children for hierarchical generics

### ISSUE THREAD

**Issue by gmazoyer** [opsmill/infrahub#2975]
### Component

API Server / GraphQL

### Current Behavior

When a generic is defined as a hierarchy, nodes inheriting from this generic can be filtered using the hierarchy related filters (`parent__*` and `children__*`). Using the same filters with the query generated for the generic fails with a message like "Unknown argument 'parent__ids' on field".

### Expected Behavior

The hierarchy filters should be available on nodes inheriting from the generics as well as the generic itself.

### Steps to Reproduce

Load the following schema after initializing an Infrahub instance.

```yaml
# yaml-language-server: $schema=https://schema.infrahub.app/develop/schema.schema.json
---
version: '1.0'
nodes:
  - name: IPPrefix
    namespace: Ipam
    inherit_from:
      - "BuiltinIPPrefix"
    description: "IPv4 or IPv6 network"
    icon: "mdi:ip-network"
    label: "IP Prefix"
  - name: IPAddress
    namespace: Ipam
    inherit_from:
      - "BuiltinIPAddress"
    description: "IPv4 or IPv6 address"
    icon: "mdi:ip"
    label: "IP Address"
```

Try running the following GraphQL query:

```graphql
query generic_prefixes {
  BuiltinIPPrefix(parent__ids: ["some-id"]) {
    count
  }
}
```
