### ISSUE TITLE
bug: schema migration validator seems to ignore the branch when a uniqueness constraint is defined on a relationship

### ISSUE THREAD

**Issue by wvandeun** [opsmill/infrahub#3211]
### Component

API Server / GraphQL

### Current Behavior

When you modify the schema in a branch,  by adding a uniqueness constraint on the node that references a relationship of that node, it seems that the branch is getting ignored. The validator seems to lookup the schema of the relationship in the main branch instead.

### Expected Behavior

The validator should lookup up the schema of the related node in the same branch as we do the migration.

### Steps to Reproduce

- spin up an instance of Infrahub
- create a branch `test` `infrahubctl branch create test`
- create this schema file
```yaml
---
version: "1.0"
nodes:
  - name: Device
    namespace: Network
    attributes:
      - name: hostname
        kind: Text
      - name: model
        kind: Text
  - name: Interface
    namespace: Network
    attributes:
      - name: name
        kind: Text
        optional: false
    relationships:
      - name: device
        cardinality: one
        kind: Parent
        peer: NetworkDevice
        optional: false
```
- load the schema in the test branch `infrahubctl schema load --branch test /path/to/file.yml`
- update the schema file with this contents
```yaml
---
version: "1.0"
nodes:
  - name: Device
    namespace: Network
    attributes:
      - name: hostname
        kind: Text
      - name: model
        kind: Text
  - name: Interface
    namespace: Network
    uniqueness_constraints:
      - ["device", "name__value"]
    attributes:
      - name: name
        kind: Text
        optional: false
    relationships:
      - name: device
        cardinality: one
        kind: Parent
        peer: NetworkDevice
        optional: false
```
-  load the schema in the test branch `infrahubctl schema load --branch test /path/to/file.yml`
- you receive an error message
```
Unable to load the schema:
  Unable to execute the validator for 'node.uniqueness_constraints.update':
        Unable to find the schema 'NetworkDevice' in the registry
        main | NetworkDevice
```
