### ISSUE TITLE
bug: unable to create a node with a relationship in a branch, if the node kind has uniqueness_constraints and the node and related node only exist in the schema of that branch

### ISSUE THREAD

**Issue by wvandeun** [opsmill/infrahub#3227]
### Component

API Server / GraphQL

### Current Behavior

Unable to create a node with a relationship if the node kind has uniqueness_constraints defined in the schema. The schema of the node and the related node have only been defined in a branch and do not exist in main.

### Expected Behavior

We should be able to create a node with a relationship in a branch, even if they are not defined in the schema of the main branch.

### Steps to Reproduce

- `inv dev.start`
- `infrahubctl branch create test`
- create a file `/tmp/schema.yml` with this content
```yaml
---
version: "1.0"
nodes:
  - name: Device
    namespace: Network
    default_filter: hostname__value
    attributes:
      - name: hostname
        kind: Text
      - name: model
        kind: Text
  - name: Interface
    namespace: Network
    uniqueness_constraints:
      - ["device", "name__value"]
    attributes:
      - name: name
        kind: Text
        optional: false
    relationships:
      - name: device
        cardinality: one
        kind: Parent
        peer: NetworkDevice
        optional: false
```
- `infrahubctl schema load --branch test /tmp/schema.yml`
- execute the following mutation in the test branch
```graphql
mutation {
  NetworkDeviceCreate(data: {hostname: {value: "device"}, model: {value: "switch"}}) {
    ok
  }
  NetworkInterfaceCreate(data: {name: {value: "interface"}, device: {id: "device"}}) {
    ok
  }
}
```
- you get the following error message
```json
{
  "data": {
    "NetworkDeviceCreate": {
      "ok": true
    },
    "NetworkInterfaceCreate": null
  },
  "errors": [
    {
      "message": "Unable to find the schema 'NetworkDevice' in the registry",
      "locations": [
        {
          "line": 5,
          "column": 3
        }
      ],
      "path": [
        "NetworkInterfaceCreate"
      ]
    }
  ]
}
```
