### ISSUE TITLE
bug: update mutation of a node inheritting from BuiltinIPPrefix or BuiltinIPAddress resets the namespace to the default namespace

### ISSUE THREAD

**Issue by wvandeun** [opsmill/infrahub#3241]
### Component

API Server / GraphQL

### Current Behavior

When you perform an update mutation of a Node that inherits from "BuiltinIPPrefix" or "BuiltinIPAddress", that has a mamespace defined, the namespace will be reset to the default namespace.

### Expected Behavior

The namespace should not be modified, unless explicitly requested.

### Steps to Reproduce

- load the following schema
```yaml
---
version: "1.0"
nodes:
  - name: Prefix
    namespace: Ipam
    inherit_from:
      - BuiltinIPPrefix
  - name: Namespace
    namespace: Ipam
    inherit_from:
      - BuiltinIPNamespace
```
- create a namespace and create a prefix in the namespace
```graphql
mutation {
  IpamNamespaceCreate(data: {name: {value: "test"}}) {
    ok
  }
}
```
```graphql
mutation {
  IpamPrefixCreate(data: {prefix: {value: "10.0.0.0/24"}, ip_namespace: {id: "17ccef2d-17fd-1099-35d8-c51a8760d21c"}}) {
    ok
  }
}
```
- perform an update mutation on the prefix object
```graphql
mutation {
  IpamPrefixUpdate(data: {id: "17ccef45-c4b1-c4db-35d4-c51571fdba29", description: {value: "setting a description"}}) {
    ok
  }
}
```
- the namespace of the prefix will have been modified to the default namespace
