### ISSUE TITLE
bug: Type of object for a peer is not checked when adding a relationship

### ISSUE THREAD

**Issue by ogenstad** [opsmill/infrahub#3274]
### Component

API Server / GraphQL

### Current Behavior

When adding a relationship to an object by its uuid we validate that the object exists in the database but not that the peer is correct. This can allow us to create "broken" objects that doesn't follow the constraints of the schema.

### Expected Behavior

We need to validate that a given peer is of the correct type before allowing the mutation.

### Steps to Reproduce

1. Create a BuiltinTag called "sample-tag"
2. Note the uuid of the tag
3. Load the following schema into Infrahub

```yaml
# yaml-language-server: $schema=https://schema.infrahub.app/develop/schema.schema.json
---
version: '1.0'

nodes:
  - name: Widget
    namespace: Test
    label: "Widget"
    default_filter: name__value
    order_by:
      - name__value
    display_labels:
      - name__value
    attributes:
      - name: name
        kind: Text
        unique: true
    relationships:
      - name: container
        peer: TestContainer
        optional: false
        cardinality: one
        kind: Attribute
  - name: Container
    namespace: Test
    label: "Container"
    default_filter: name__value
    order_by:
      - name__value
    display_labels:
      - name__value
    attributes:
      - name: name
        kind: Text
        unique: true
    relationships:
      - name: widgets
        peer: TestWidget
        cardinality: many
        optional: true
```

4. Run the following mutation

Set the `$tag_id` variable to the id of the tag created in step 1.

```graphql
mutation CreateWidget($tag_id: String!) {
  TestWidgetCreate(data:
    	{
        name: {value: "my-invalid-widget"},
        container: {id: $tag_id}
      }) {
    ok
    object {
      name {
        value
      }
      container {
        node {
          name {
            value
          }
        }
      }
    }
  }
}
```

5. Note that a Widget is created without a valid relationship

![Screenshot 2024-05-10 at 10 15 45](https://github.com/opsmill/infrahub/assets/6694669/4ab5af34-f616-4f83-9c63-392ab62844c5)
