### ISSUE TITLE
bug: Attribute kind(Number) and Enum Support

### ISSUE THREAD

**Issue by FragmentedPacket** [opsmill/infrahub#3281]
### Component

API Server / GraphQL

### Current Behavior

I'm attempting to create an attribute of `kind: Number` with enums, but I'm getting an error. Below is the initial attribute definition that is not working.

```yaml
      - name: "phase_one_dh_group"
        kind: "Number"
        default_value: 14
        enum:
          - 2
          - 14
          - 15
          - 16
          - 17
          - 18
          - 19
          - 20
          - 21
          - 22
          - 23
          - 24
```

We see the following error when attempting to create node.
![image](https://github.com/opsmill/infrahub/assets/29315002/4a641382-8c27-445b-87a6-7520ee7d6105)

To try and workaround the issue, I can make the enums strings, but then get a validation error advising 14 or my selection is not in the list of enums since they're strings while the value is an integer. This also doesn't auto-populate the UI with the default value.

```yaml
      - name: "phase_one_dh_group"
        kind: "Number"
        default_value: 14
        enum:
          - "2"
          - "14"
          - "15"
          - "16"
          - "17"
          - "18"
          - "19"
          - "20"
          - "21"
          - "22"
          - "23"
          - "24"
```

<img width="382" alt="image" src="https://github.com/opsmill/infrahub/assets/29315002/4a5b19c8-cd80-415e-8696-ec36bdedfdde">

If I select one of the enums from the dropdown list, I get the following error:

<img width="390" alt="image" src="https://github.com/opsmill/infrahub/assets/29315002/fd72a245-ff2a-4dc4-b35a-aabe0b1c9736">

### Expected Behavior

To be able to declare an attribute of kind `Number` and define enums as the same expected type (`Number`) that allows the frontend to work correctly when creating the node.

### Steps to Reproduce

Here is an example schema that can be loaded into Infrahub:

```yaml
# yaml-language-server: $schema=https://schema.infrahub.app/infrahub/schema/latest.json
version: '1.0'
generics:
  - name: "VPNGeneric"
    namespace: "Network"
    include_in_menu: true
    label: "VPNs"
    attributes:
      - name: "name"
        kind: "Text"
        unique: true
nodes:
  - name: SiteToSite
    namespace: "Network"
    label: "VPN: Site to Site"
    icon: "mdi:vpn"
    inherit_from:
      - "NetworkVPNGeneric"
    menu_placement: "NetworkVPNGeneric"
    include_in_menu: true
    display_labels:
      - "name__value"
    attributes:
      - name: "ike_version"
        kind: "Text"
        default_value: "ikev2"
        enum:
          - "ikev1"
          - "ikev2"
      - name: "remote_ip"
        kind: "IPHost"
      - name: "pre_shared_key"
        kind: "HashedPassword"
        max_length: 64
      - name: "phase_one_dh_group"
        kind: "Number"
        default_value: 14
        enum:
          - 2
          - 14
          - 15
          - 16
          - 17
          - 18
          - 19
          - 20
          - 21
          - 22
          - 23
          - 24
 ```

Navigate to the UI under the VPNs grouping and attempt to create a **Site to Site VPN** by populating the necessary fields. This will yield the original error of `re.findall` expecting a string or bytes-like object.

Follow the other schema changes defined in the current behavior section to replicate the other errors.

### Additional Information

Please let me know if I'm not using the schema correctly. I was able to get this to work using the `Dropdown` kind along with `choices` and that might be the best way to handle this anyways, but the errors seem like potential bugs.

A quick fix would be to convert or attempt to convert the value to a string before attempting to use `re.findall`.
