### ISSUE TITLE
bug: node create/edit form does not display input for relationships of kind Generic/Component with cardinality many

### ISSUE THREAD

**Issue by wvandeun** [opsmill/infrahub#3282]
### Component

Frontend UI

### Current Behavior

When you have a node in your schema that has a relationship of kind Generic or Component and cardinality many, there is no input displayed in the node create/edit form.
When the relationship is optional, the use can still add related nodes after the node was created. 
When the relationship is required, there is no way to create an instance of this node in the frontend. 

### Expected Behavior

The create/edit form should display an input for relationships of kind Generic/Component and cardinality many.

### Steps to Reproduce

- start a dev environment
- load the following schema
```yaml
---
version: "1.0"
nodes:
  - name: Node1
    namespace: Test
    default_filter: name
    display_labels:
      - name__value
    attributes:
      - name: name
        label: Name
        kind: Text
        optional: false
    relationships:
      - name: related_nodes
        label: Related nodes
        cardinality: many
        peer: TestNode2
        optional: false
        kind: Generic
  - name: Node2
    namespace: Test
    default_filter: name
    display_labels:
      - name__value
    attributes:
      - name: name
        label: Name
        kind: Text
        optional: false
```
- in the frontend create a Node2 node
- in the frontend create a Node1 node, notice that there is no input for the related_nodes relationship

### Additional Information

Issue exists on stable and develop.

The backend seems to generate the correct mutations. So a user can still create/edit the node through GraphQL or the python SDK.
