### ISSUE TITLE
feature: deleting a generator target object should delete the created objects of that target 

### ISSUE THREAD

**Issue by wvandeun** [opsmill/infrahub#3289]
### Component

API Server / GraphQL

### Current Behavior

It is not clear how a generator target object should be properly deleted within Infrahub.

- When you delete the target node from the target group, then the generator does not seem to delete all the objects that the generator created as a result of the target.

- When you delete the target node from Infrahub, then the generator will raise an error message.

### Expected Behavior

We should have a clear and defined way to delete generator target nodes and the resulting objects.

### Steps to Reproduce

- load the following schema
```yaml
---
version: "1.0"
nodes:
  - name: TagService
    namespace: Test
    attributes:
      - name: name
        label: Name
        kind: Text
        optional: false
        unique: true
      - name: amount
        label: Amount
        kind: Number
        optional: false
```
- create a group called `tag_services` in Infrahub
- define a generator in an external repository
```yaml
generator_definitions:
  - name: tag_service_generator
    file_path: "test_tag_service.py"
    targets: tag_services
    query: test_tag_service
    class_name: TestTagService
    parameters:
      name: "name__value"
```
```graphql
query TagService($name: String!) {
  TestTagService(name__value: $name) {
    edges {
      node {
	name {
	  value
	}
	amount {
	  value
	}
      }
    }
  }
}
```
```python
from infrahub_sdk.generator import InfrahubGenerator

class TestTagService(InfrahubGenerator):
    async def generate(self, data: dict) -> None:
        service = data["TestTagService"]["edges"][0]["node"]

        name = service["name"]["value"]
        amount = service["amount"]["value"]

        for i in range(amount):
            tag = await self.client.create(kind="BuiltinTag", name=f"{name}-{i+1}")
            await tag.save(allow_upsert=True)
```
- create/syn the external repository in Infrahub
- create a new branch in Infrahub
- create a TestTagService object with name test and amount 3
- add the TestTagService object to the `tag_services` group
- create a proposed change to merge the branch into main
- 3 tags will have been created
- merge the branch
- create a new branch in Infrahub
- delete the TestTagService object from the `tag_services` group
- open a proposed change for the branch
- the generator will run, but it will not delete the tag objects 
- open a new branch in Infrahub
- delete the TestTagService object
- open a proposed change for the branch
- the generator will raise an error message (and the tag object will not have been deleted)
