### ISSUE TITLE
bug: There is not indication of mandatory cardinality=many relationships

### ISSUE THREAD

**Issue by ogenstad** [opsmill/infrahub#3368]
### Component

Frontend UI

### Current Behavior

If an object has a mandatory relationship of cardinality type many there is no indication of this in the frontend and trying to save the object fails without any indication as to why this happens.
<img width="588" alt="Screenshot 2024-05-20 at 14 07 19" src="https://github.com/opsmill/infrahub/assets/6694669/00d06641-ab65-4d91-a1fd-e90579c2594b">

### Expected Behavior

It should be clear to the user if a relationship is required.

### Steps to Reproduce

1. Load the following schema to Infrahub

```yaml
---
version: '1.0'
nodes:
  - name: Thing
    namespace: Test
    label: "Thing"
    default_filter: name__value
    order_by:
      - name__value
    display_labels:
      - name__value
    attributes:
      - name: name
        kind: Text
        unique: true
      - name: description
        kind: Text
        optional: true
    relationships:
      - name: tags
        peer: BuiltinTag
        optional: false
        cardinality: many
        kind: Attribute
```

2. Try to create a "thing" object without specifying any tags.
