### ISSUE TITLE
bug: Updating an object changes relationships of cardinality=one even though no change is expected

### ISSUE THREAD

**Issue by ogenstad** [opsmill/infrahub#3404]
### Component

Frontend UI

### Current Behavior

Changing an unrelated attribute causes relationships of cardinality=one to be reset (also impacted by a bug in the backend.. #3405)

### Expected Behavior

The frontend should only update the fields that have been changed.

### Steps to Reproduce

1. Load the following schema to Infrahub.

```yaml
# yaml-language-server: $schema=https://schema.infrahub.app/develop/schema.schema.json
---
version: '1.0'

nodes:
  - name: Widget
    namespace: Test
    label: "Widget"
    default_filter: name__value
    order_by:
      - name__value
    display_labels:
      - name__value
    attributes:
      - name: name
        kind: Text
        unique: true
      - name: description
        kind: Text
        optional: true
    relationships:
      - name: container
        peer: TestContainer
        optional: false
        cardinality: one
        kind: Attribute
  - name: Container
    namespace: Test
    label: "Container"
    default_filter: name__value
    order_by:
      - name__value
    display_labels:
      - name__value
    attributes:
      - name: name
        kind: Text
        unique: true
    relationships:
      - name: widgets
        peer: TestWidget
        cardinality: many
        optional: true
```

2. Create a container named "chest"
3. Create a widget called Hammer and assign it to the "chest" container, don't enter a description
4. Edit the object and give it the description "My hammer", view the output using the inspect function of the browser
5. Note that this mutation is sent to the backend:

```graphql
mutation TestWidgetUpdate {
  TestWidgetUpdate(
    data: {id: "17d1cb62-3c20-a6e0-58db-1746a23992c5", description: {value: "My hammer"}, container: null}
  ) {
    ok
    __typename
  }
}
```

6. Note that as container is a required field this mutation should also fail in the backend but it also should not be sent in the first place.
