### ISSUE TITLE
bug: Required cardinality=one relationship not validated on update mutations

### ISSUE THREAD

**Issue by ogenstad** [opsmill/infrahub#3405]
### Component

API Server / GraphQL

### Current Behavior

It's possible to update an object using a mutation that removes a required cardinality=one relationship.

### Expected Behavior

The mutation should be rejected

### Steps to Reproduce

1. Load the following schema to Infrahub.

```yaml
# yaml-language-server: $schema=https://schema.infrahub.app/develop/schema.schema.json
---
version: '1.0'

nodes:
  - name: Widget
    namespace: Test
    label: "Widget"
    default_filter: name__value
    order_by:
      - name__value
    display_labels:
      - name__value
    attributes:
      - name: name
        kind: Text
        unique: true
      - name: description
        kind: Text
        optional: true
    relationships:
      - name: container
        peer: TestContainer
        optional: false
        cardinality: one
        kind: Attribute
  - name: Container
    namespace: Test
    label: "Container"
    default_filter: name__value
    order_by:
      - name__value
    display_labels:
      - name__value
    attributes:
      - name: name
        kind: Text
        unique: true
    relationships:
      - name: widgets
        peer: TestWidget
        cardinality: many
        optional: true
```

2. Create a container named "chest"
3. Create a widget called Hammer and assign it to the "chest" container, don't enter a description
4. Send in the following mutation swapping out the ID of the hammer node

```graphql
mutation TestWidgetUpdate {
  TestWidgetUpdate(
    data: {id: "17d1cb62-3c20-a6e0-58db-1746a23992c5", description: {value: "My hammer"}, container: null}
  ) {
    ok
    __typename
  }
}
```

6. Note the mutation succeeds even though it shouldn't and the object is left in an invalid state.
