### ISSUE TITLE
task: Fix file filter for CI job to validate generated documentation

### ISSUE THREAD

**Issue by ogenstad** [opsmill/infrahub#3417]
### Component

CI/CD

### Task Description

Currently we have a job in the CI that validates that the documentation generated from the code is correct and up to date. This works provided that the Python files are edited. However a problem would occur if we edit the generated markdown files directly as it would lead to this job not being triggered for a CI run. As such we need to modify `needs.files-changed.outputs.backend` and introduce a new group that contains the Python files as well as any changes within the ./docs folder.

```yaml

  backend-validate-generated:
    if: |
      always() && !cancelled() &&
      !contains(needs.*.result, 'failure') &&
      !contains(needs.*.result, 'cancelled') &&
      needs.files-changed.outputs.backend == 'true'
    needs: ["files-changed", "yaml-lint", "python-lint"]
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: "Setup environment"
        run: |
          pipx install poetry
          poetry config virtualenvs.prefer-active-python true
          pip install invoke toml
      - name: "Install Package"
        run: "poetry install"
      - name: "Run validator"
        run: "poetry run invoke backend.validate-generated"
```
