### ISSUE TITLE
bug: HFID value of `None` confuses the identifier when assigning from a pool

### ISSUE THREAD

**Issue by ogenstad** [opsmill/infrahub#3422]
### Component

API Server / GraphQL

### Current Behavior

When assigning a prefix (and probably an ip address) from a pool it's possible that the HFID is `None` and if so it will be the same for multiple objects that want to assign a resource from a pool which results in the same resource being returned.

### Expected Behavior

If HFID is `None` it should not be used in this context. 

### Steps to Reproduce

1. Load the default demo schema
2. Load this additional schema:

```yaml
# yaml-language-server: $schema=https://schema.infrahub.app/develop/schema.schema.json
---
version: '1.0'
# This is what typically a end-user would do
nodes:
  - name: MandatoryPrefix
    namespace: Test
    description: "Set mandatory Prefix"
    icon: "mdi:format-list-group"
    label: "Prefix Allocation"
    attributes:
      - name: name
        kind: "Text"
        unique: true
      - name: description
        kind: "Text"
        optional: true
    relationships:
      - name: prefix
        peer: IpamIPPrefix
        kind: Attribute
        optional: false
        cardinality: one
  - name: MandatoryAddress
    namespace: Test
    description: "Set mandatory Address"
    icon: "mdi:format-list-group"
    label: "Address Allocation"
    attributes:
      - name: name
        kind: "Text"
        unique: true
      - name: description
        kind: "Text"
        optional: true
    relationships:
      - name: address
        peer: IpamIPAddress
        kind: Attribute
        optional: false
        cardinality: one
```

3. Create an IP Prefix of type IpamIPPrefix and give it the prefix of 10.0.0.0/8 and the "prefix" member_type

4. Create a Prefix pool CorePrefixPool / CoreIPPrefixPool with name=pool1, default prefix size=24, default prefix type=IpamIPPrefix, assign the 10.0.0.0/8 resource and the default ip namespace

5. Create a Prefix Allocation object (TestMandatoryPrefix) in the frontend, give it the name "prefix1", select to assign the prefix from "pool1".

A sample mutation from the frontend when doing this looks like this:

```graphql
mutation TestMandatoryPrefixCreate {
  TestMandatoryPrefixCreate(
    data: {name: {value: "prefix1"}, prefix: {from_pool: {id: "17d213f5-7dc4-efd0-58d0-174640177652"}}}
  ) {
    object {
      id
      display_label
      __typename
    }
    ok
    __typename
  }
}
```

5. Create a second Prefix Allocation object (TestMandatoryPrefix) in the frontend, give it the name "prefix2", select to assign the prefix from "pool1".

6. Note that both TestMandatoryPrefix objects got related to the same prefix:

![Screenshot 2024-05-23 at 11 30 19](https://github.com/opsmill/infrahub/assets/6694669/119a8e0b-d34b-469d-9ba4-30632d819bdd)

7. Viewing the pool in the resource manager shows the probable cause for this:

![Screenshot 2024-05-23 at 11 32 07](https://github.com/opsmill/infrahub/assets/6694669/d5c3c3d3-1b68-4107-8e01-0dbef389cb82)

The identifier of `hfid=None rel=prefix` was chosen which would have been the same for both of them so the same address was returned from the pool.

### Additional Information

Another issue that can be problematic with this is that it's possible to assign the same prefix or address using a cardinality=one relationship to multiple resources.
