### ISSUE TITLE
bug: It's possible to create a schema where two nodes have a required relationship to each other

### ISSUE THREAD

**Issue by ogenstad** [opsmill/infrahub#3642]
### Component

API Server / GraphQL

### Current Behavior

It's possible to create a schema where two nodes have a required relationship to each other, the problem with this is that after the schema is loaded it's not possible to create the nodes.

### Expected Behavior

The schema loader should complain about this

### Steps to Reproduce

1. Load this schema into Infrahub

```yaml
# yaml-language-server: $schema=https://schema.infrahub.app/infrahub/schema/latest.json
---
version: '1.0'
nodes:
  - name: Husband
    namespace: Fictional
    label: Husband
    display_labels:
      - name__value
    attributes:
      - name: name
        kind: Text
        optional: false
    relationships:
      - name: wife
        peer: FictionalWife
        kind: Attribute
        optional: false
        cardinality: one
  - name: Wife
    namespace: Fictional
    label: Wife
    display_labels:
      - name__value
    attributes:
      - name: name
        kind: Text
        optional: false
    relationships:
      - name: husband
        peer: FictionalHusband
        kind: Attribute
        optional: false
        cardinality: one
```

2. Try to create a married couple
