### ISSUE TITLE
bug: cannot update attributes with name "updated_at"

### ISSUE THREAD

**Issue by fatih-acar** [opsmill/infrahub#3730]
### Component

API Server / GraphQL
Infrahub 0.14.2

### Current Behavior

When using a schema defining nodes that have an attribute named `updated_at`, it is not possible to change the value of this attribute and it is always blank/null.

### Expected Behavior

`updated_at` attributes should be editable as expected

### Steps to Reproduce

Load the following schema:

```yaml
---
version: "1.0"
nodes:
  - name: Country
    namespace: Otterbox
    label: Country
    attributes:
      - name: name
        kind: Text
        unique: true
        optional: false
      - name: created_at
        kind: DateTime
        optional: false
      - name: updated_at
        kind: DateTime
        optional: false
```

Create a new Country node with a name, created_at and updated_at set.
You will see that created_at is correctly set but updated_at is not.
