### ISSUE TITLE
bug: loading a schema with a node using the Core namespace returns HTTP status code 403

### ISSUE THREAD

**Issue by wvandeun** [opsmill/infrahub#3849]
### Component

API Server / GraphQL

### Infrahub version

0.15.0

### Current Behavior

When you load a schema, with a node using the core namespace, the API server returns a HTTP status code 403 with a proper message indicating that the core namespace should not be used.

HTTP status code 403 is probably not the right status code to use in this case. It is supposed to be used when there is an Authorization issues, which is not really the case here. The core namespace is restricted and cannot be used by any user. So in this case the status code is misleading.

### Expected Behavior

A proper HTTP status code should be returned. I think in this scenario 422 would be more appropriate.

### Steps to Reproduce

- spin up a demo environment
- load the following schema using `infrahubctl schema load`
```yaml
---
version: "1.0"
nodes:
  - name: Test
    namespace: Core
    attributes:
      - name: something
        kind: Text
        optional: false
```

### Additional Information

`infrahubctl schema load` does not give us a proper error message when a 403 status code is returned by the Infrahub API server. A end-user will be unable to understand from the error message what exactly is wrong with the request.
