### ISSUE TITLE
bug: infrahubctl doesn't give a proper error message when loading a schema with an invalid namespace

### ISSUE THREAD

**Issue by wvandeun** [opsmill/infrahub#3859]
### Component

infrahubctl CLI

### Infrahub version

0.15.0

### Current Behavior

When loading a schema that has a node that uses an invalid namespace (not matching ^[A-Z][a-z0-9]+$ or incorrect length) you get the error message  "Unable to load the schema: 0".  A user is unable to understand what exactly is wrong.

### Expected Behavior

A proper error message is returned, so that a user would properly understand what is wrong.

### Steps to Reproduce

- create the following schema file, using an invalid namespace OuT
```
---
version: "1.0"
nodes:
  - name: Thing
    namespace: OuT
    attributes:
      - name: thing
        kind: Text
        optional: false
  - name: OtherThing
    namespace: OuT
    attributes:
      - name: thing
        kind: Text
        optional: false
```
- try loading the schema using `infrahubctl schema load`

### Additional Information

Same issue exists for `infrahubctl schema check`

**Comment by wvandeun** [comment]
The same issue seems to occur, when you have some typo in the schema. For example, in this schema we have a typo in the cardinality keyword on a relationship, which results in the same error message:

```yaml
# yaml-language-server: $schema=https://schema.infrahub.app/infrahub/schema/latest.json
---
version: "1.0"
nodes:
  - name: Foo
    namespace: Test
    attributes:
      - name: attr
        kind: Text
    relationships:
      - name: bars
        peer: TestBar
        cardindality: one
  - name: Bar
    namespace: Test
    attributes:
      - name: attr
        kind: Text
```
