### ISSUE TITLE
bug: Confusing diff output when loading multiple times the same schema

### ISSUE THREAD

**Issue by BaptisteGi** [opsmill/infrahub#3892]
### Component

API Server / GraphQL, infrahubctl CLI

### Infrahub version

0.15.0

### Current Behavior

I load a check + load my schema on a brand new branch:
```bash
> infrahubctl schema check --branch test-broken-diff random.yml

schema 'random.yml' is Valid!
diff:
    added:
        RandomSandwich:
            added: {}
            changed: {}
            removed: {}
    changed: {}
    removed: {}


> infrahubctl schema load --branch test-broken-diff random.yml

schema 'random.yml' loaded successfully
1 schema processed in 0.949 seconds.
```

So far it looks good. Now if I try to check + load the exact same schema a second time:
```bash
> infrahubctl schema check --branch test-broken-diff random.yml

schema 'random.yml' is Valid!
diff:
    added: {}
    changed:
        RandomSandwich:
            added: {}
            changed:
                relationships:
                    added:
                        profiles: null
                    changed: {}
                    removed: {}
            removed: {}
    removed: {}


> infrahubctl schema load --branch test-broken-diff random.yml 

schema 'random.yml' loaded successfully
1 schema processed in 0.814 seconds.
```

__Here it computes diff on a "relationship" to "profiles" even tho I haven't changed anything to my schema definition. I believe expected behavior should be "No diff"__

Now I check + load the schema a third time:
```bash
> infrahubctl schema check --branch test-broken-diff random.yml

schema 'random.yml' is Valid!
No diff


> infrahubctl schema load --branch test-broken-diff random.yml 

The schema in Infrahub was is already up to date, no changes were required
1 schema processed in 0.426 seconds.
```

The third time the schema diff computed makes sense.

### Expected Behavior

On the second check+load I expect a "no diff" output (pretty much as the third execution)

### Steps to Reproduce

- Create a branch

- Create a schema
```yaml
# yaml-language-server: $schema=https://schema.infrahub.app/infrahub/schema/latest.json
---
version: "1.0"
nodes:
  - name: Sandwich
    namespace: Random
    description: Random stuff
    default_filter: name__value
    order_by: [name__value]
    display_labels:
      - name__value
    include_in_menu: true
    attributes:
      - name: name
        kind: Text
        unique: true
        order_weight: 1000
```

- Check and load multiple times the same schema on the same branch (as described in the "Current behavior" section)
