### ISSUE TITLE
bug: Incorrect Notation for `human_friendly_id` and `uniqueness_constraints` in Schema are not properly check when loading schema

### ISSUE THREAD

**Issue by BeArchiTek** [opsmill/infrahub#3923]
### Component

API Server / GraphQL, Python SDK

### Infrahub version

0.15.1

### Current Behavior

The schema definitions for `human_friendly_id` and `uniqueness_constraints` are not being properly checked, leading to issues with their notation. The correct and incorrect notations are outlined below.

#### Good Notation
```yaml
  - name: Device
    namespace: Infra
    description: "Generic Device object."
    label: "Device"
    icon: "mdi:server"
    uniqueness_constraints:
      - ["name"]
    human_friendly_id:
      - "name__value"
```

#### Wrong Notation
```yaml
  - name: Device
    namespace: Infra
    description: "Generic Device object."
    label: "Device"
    icon: "mdi:server"
    uniqueness_constraints:
      - ["name__value"]
    human_friendly_id: ["name"]
```

#### Expected Behavior
The schema validation should enforce the correct notation. From the docs : 

> uniqueness_constraints can be composed of N number of attribute or relationship of cardinality one:
> 
> For an attribute, the valid format is <attributename>__value. Currently only value is supported but in the future the plan is to allow additional metadata to be used as well.
> For a relationship, only the name of the relationship should be provided <relationshipname>. Only relationship of cardinality one are supported and the relationship must be mandatory.

#### Actual Behavior
The system does not enforce these rules, allowing incorrect notation which can lead to issues during runtime.

#### Suggested Fix
Implement validation logic to ensure:
- `uniqueness_constraints` follows the correct format.
- `human_friendly_id` is properly structured.

### Expected Behavior

The schema validation should enforce the correct notation:
- `uniqueness_constraints` should be an array of arrays with each inner array containing field names.
- `human_friendly_id` should be an array containing field names concatenated either `__values` or other supported "values" like binary_address

### Steps to Reproduce

1. Define a schema with `human_friendly_id` and `uniqueness_constraints` as shown in the "Wrong Notation" example.
2. Validate or use the schema in the system.
3. Observe that the notation is not properly checked, resulting in potential errors or unexpected behavior.
