### ISSUE TITLE
bug: regex validation doesn't work for list kind attribute

### ISSUE THREAD

**Issue by wvandeun** [opsmill/infrahub#3929]
### Component

API Server / GraphQL

### Infrahub version

0.16.0.dev0

### Current Behavior

Regex validation for list kind attributes doesn't work. It looks like it is trying to validate a string representation of the complete list against the regex.

### Expected Behavior

Regex validation would validate each item in the list against the regex.

### Steps to Reproduce

- load the following schema
```yaml
---
version: "1.0"
nodes:
  - name: Test
    namespace: Testing
    attributes:
      - name: testing
        kind: List
        regex: "abc"
        optional: true
```
- execute the following mutation
```grapqhql
mutation {
  TestingTestCreate(data: {testing: {value: ["abc"]}}) {
    ok
  }
}
```
- mutation will fail with error message :       "message": "['abc'] must be conform with the regex: 'abc' at testing"
