### ISSUE TITLE
task: Update infrahubctl toml example to reflect the actual inputs that are required

### ISSUE THREAD

**Issue by cdean00** [opsmill/infrahub#3944]
### Component

Documentation & Examples

### Task Description

Documentation currently shows this for the example toml config file:
```toml title="infrahubctl.toml"
server_address="http://localhost:8000"
api_token="06438eb2-8019-4776-878c-0941b1f1d1ec"
```

The above errors out when running infrahubctl. It should show this:
```toml title="infrahubctl.toml"
INFRAHUB_ADDRESS="http://localhost:8000"
INFRAHUB_API_TOKEN="06438eb2-8019-4776-878c-0941b1f1d1ec"
```

https://docs.infrahub.app/infrahubctl#infrahubctltoml-file
