### ISSUE TITLE
bug: infrahubctl generator command does not print out any information when target group is empty

### ISSUE THREAD

**Issue by wvandeun** [opsmill/infrahub#3953]
### Component

Python SDK

### Infrahub version

0.12.1

### Current Behavior

When you run a generator using `infrahubctl` and there are no members in the target group, then there is no output at all.
For a user it is hard to figure out what exactly happened or did not happen and why that is the case.

### Expected Behavior

At a minimum we should print out some information that no target objects were found.

Maybe we could even provide more information behind the `--debug` option, for example for which node in the target group we are running. The `--debug` doesn't seem to provide any additional output at all at the moment.

### Steps to Reproduce

- create a group called `testing_targets` in Infrahub
- do not any member to the group
- define a git repository on your file system
- create a `.infrahub.yml` config file with this contents
```yaml
---
generator_definitions:
  - name: "testing"
    file_path: "generators/testing.py"
    class_name: "Generator"
    targets: testing_targets
    query: testing
    parameters:
      name: "name__value"
```
- create a file `generators/testing.py`
```python
from infrahub_sdk.generator import InfrahubGenerator

class Generator(InfrahubGenerator):
    async def generate(self, data: dict) -> None:
        pass
```
- create a file `generators/testing.gql`
```graphql
query testing($name: String!) {
  BuiltinTag(name__value: $name) {
    edges {
      node {
	name {
	  value
	}
      }
    }
  }
}
```
- run `infrahubctl generator testing`
- run `infrahubctl generator --debug testing`
