### ISSUE TITLE
bug: generators should provide more information in the web ui when target group is empty

### ISSUE THREAD

**Issue by wvandeun** [opsmill/infrahub#3954]
### Component

Frontend UI, API Server / GraphQL

### Infrahub version

0.16.0.dev0

### Current Behavior

When you run a generator in Infrahub from an external repository, but the target group contains 0 members, there is no information on this in the Checks tab of the proposed changes.

For a user it is hard to figure out what exactly happened or didn't happen and why.
![image](https://github.com/user-attachments/assets/888768d7-757f-4ad0-9670-d1f644f69872)

### Expected Behavior

There should be information regarding the fact that there is 0 nodes in the target group, hence the generator didn't need to run on the checks page.

There is information on this in the tasks tab already, but this kind of information should be more easily visible in the UI.

### Steps to Reproduce

- create a group called `testing_targets` in Infrahub
- do not any member to the group
- define a git repository on your file system
- create a `.infrahub.yml` config file with this contents
```yaml
---
generator_definitions:
  - name: "testing"
    file_path: "generators/testing.py"
    class_name: "Generator"
    targets: testing_targets
    query: testing
    parameters:
      name: "name__value"
```
- create a file `generators/testing.py`
```python
from infrahub_sdk.generator import InfrahubGenerator

class Generator(InfrahubGenerator):
    async def generate(self, data: dict) -> None:
        pass
```
- create a file `generators/testing.gql`
```graphql
query testing($name: String!) {
  BuiltinTag(name__value: $name) {
    edges {
      node {
	name {
	  value
	}
      }
    }
  }
}
```
- set up the repository as a repository in Infrahub
- create a branch
- create a tag in the branch
- open a PR
