### ISSUE TITLE
feature: Be able to use human_friendly_id (HFID) instead of display_label in form

### ISSUE THREAD

**Issue by BeArchiTek** [opsmill/infrahub#3959]
### Component

Frontend UI, API Server / GraphQL, Python SDK

### Describe the Feature Request

As an user, I would like to be see `human_friendly_id` instead of the `display_label` on my form.
Right now we are using `display_label` and if there is None we fallback on Kind + ID

I would like to have HFID if not -> display_label if not -> Kind + ID

It will help render `display_label` as deprecated as the same time as default_filter, as both would be cover by uniqueness_constraint + HFID

### Describe the Use Case

This interface have a HFID referencing a Device, but contrary to HFID or order_by, device__name__value can't be use in display_label. Resulting on "missing" information in my form

```yaml
- name: Base
    namespace: Interface
    description: "Generic Network Interface"
    label: "Interface"
    icon: "mdi:ethernet"
    menu_placement: "InfraDevice"
    display_labels:
      - name__value
    order_by:
      - device__name__value
      - name__value
    uniqueness_constraints:
      - ["device", "name__value"]
    human_friendly_id:
      - "device__name__value"
      - "name__value""
```

if a HFID is define, we should be able to use as "display_label" on the form.
