### ISSUE TITLE
bug: schema integrity check errors do not have a useful message

### ISSUE THREAD

**Issue by wvandeun** [opsmill/infrahub#3987]
### Component

API Server / GraphQL

### Infrahub version

0.16.0.dev0

### Current Behavior

The error message you receive when you have a schema integrity check failure in a proposed change, is not really useful.
The message is rather cryptic.
![image](https://github.com/user-attachments/assets/5b733b83-e2f4-43d8-ae85-4d5f28ae3258)

### Expected Behavior

The error message better explains what is wrong.
In this case it could be: "schema integrity check is failing because the node {name} does not have a unique name"

### Steps to Reproduce

- create a branch
- load this schema
```yaml
---
version: "1.0"
nodes:
  - name: Device
    namespace: Zorro
    label: "Device"
    display_labels:
      - name__value
    attributes:
      - name: name
        kind: Text
        unique: true
      - name: description
        kind: Text
        optional: true
  - name: Device
    namespace: Infra
    label: "Device"
    display_labels:
      - name__value
    attributes:
      - name: name
        kind: Text
        unique: true
      - name: description
        kind: Text
        optional: true
```
- create a proposed change to merge the branch into main
- schema integrity check will fail
