### ISSUE TITLE
bug: schema does not get in sync between the different workers after starting Infrahub

### ISSUE THREAD

**Issue by wvandeun** [opsmill/infrahub#3994]
### Component

API Server / GraphQL

### Infrahub version

0.15.0-0.16.0.dev0

### Current Behavior

When you start Infrahub, without loading any schema or data into the system, it seems that there is always exactly 1 worker that doesn't seem to pick up the right version of the schema.

If you then load a schema into Infrahub, the workers seem to get in sync again.|

Was not able to reproduce this on 0.14.0.

### Expected Behavior

Infrahub workers should be in sync and using the same schema after the initial start

### Steps to Reproduce

- start infrahub using `inv dev.start` or the curl one liner
- after infrahub has fully started, execute the this GraphQL query
```graphql
query {
  InfrahubStatus {
    summary {
      schema_hash_synced
    }
    workers {
      edges {
        node {
          id
          active
          schema_hash
        }
      }
    }
  }
}
```
the result should show that `schema_hash_synced` is False and that exactly one worker has a different schema_hash
- load a simple schema into Infrahub
```yaml
---
version: "1.0"
nodes:
  - name: Server
    namespace: Infra
    label: "Server"
    state: absent
    display_labels:
      - name__value
    attributes:
      - name: name
        kind: Text
        unique: true
      - name: description
        kind: Text
        optional: true
```
- Execute the above GraphQL query again, `schema_hash_synced` will now be true and all workers will have the same schema _hash value.
