### ISSUE TITLE
bug: schema out of sync between different workers after deleting a node from the schema

### ISSUE THREAD

**Issue by wvandeun** [opsmill/infrahub#3995]
### Component

Frontend UI, API Server / GraphQL

### Infrahub version

0.16.0.dev0

### Current Behavior

When you remove a node from the schema using `state: absent` the schema seems to get out of sync between the different workers.

In the UI the node will still be visible in the menu, and you get error messages indicating that the node is not found in the
registry.

![image](https://github.com/user-attachments/assets/3dae7f9b-15c6-4014-991d-de8f364a3247)

### Expected Behavior

- the node is removed from the schema
- the workers are all using the same version of the schema
- the node does not show up in the menu any longer
- there is no error messages in the UI that indicate that the node cannot be found in the registry

### Steps to Reproduce

- start Infrahub
- load a simple schema
```yaml
---
version: "1.0"
nodes:
  - name: Server
    namespace: Infra
    label: "Server"
    display_labels:
      - name__value
    attributes:
      - name: name
        kind: Text
        unique: true
      - name: description
        kind: Text
        optional: true
```
- verify that the workers are in sync with this graphql query
```graphql
query {
  InfrahubStatus {
    summary {
      schema_hash_synced
    }
 }
```
- load the schema a file (state absent defined on the node)
```yaml
---
version: "1.0"
nodes:
  - name: Server
    namespace: Infra
    label: "Server"
    state: absent
    display_labels:
      - name__value
    attributes:
      - name: name
        kind: Text
        unique: true
      - name: description
        kind: Text
        optional: true
```
- the node will not be removed from the menu in the UI
- the UI will give you error messages indicating it cannot find the node in the schema
- using the above GraphQL query you can see that the schema is not in sync between the different workers
