### ISSUE TITLE
bug: Crashes after loading Schema due to Relationship Mismatch

### ISSUE THREAD

**Issue by BeArchiTek** [opsmill/infrahub#3997]
### Component

API Server / GraphQL

### Infrahub version

0.15.2

### Current Behavior

Infrahub successfully loads the schema but crashes afterward. The logs indicate a type mismatch error between EntityA.relationships and EntityB.relationships. The issue arises because an attempt was made to override an inherited relationship to change the peer.

If the relationships is override with the same peer, everything is ok
If I tried to force the identifier it's still failing so I think it's link to the peer itself

Crash log excerpt:

```python
TypeError: Field RandomGenericA.connections expects type NestedPaginatedRandomGenericB but
RandomSpecificA.connections is type NestedPaginatedRandomSpecificB.

Field argument RandomGenericA.connections(name__value:) expected but
RandomSpecificA.connections does not provide it.

Field argument RandomGenericA.connections(name__values:) expected but
RandomSpecificA.connections does not provide it.

Field argument RandomGenericA.connections(name__source__id:) expected but
RandomSpecificA.connections does not provide it.

Field argument RandomGenericA.connections(name__owner__id:) expected but
RandomSpecificA.connections does not provide it.

Field argument RandomGenericA.connections(name__is_visible:) expected but
RandomSpecificA.connections does not provide it.

Field argument RandomGenericA.connections(name__is_protected:) expected but
RandomSpecificA.connections does not provide it.
```

### Expected Behavior

Either it's not supported and the schema should not be accepted/loaded or it's supported and should not crash

### Steps to Reproduce

- Load the following schema into the Infrahub application:

```yaml
---
version: '1.0'

generics:
  - name: GenericA
    namespace: Random
    attributes:
      - name: name
        kind: Text
        unique: true
    relationships:
      - name: connections
        cardinality: many
        peer: RandomGenericB
        kind: Component

  - name: GenericB
    namespace: Random
    attributes:
      - name: name
        kind: Text


nodes:
  - name: SpecificA
    namespace: Random
    inherit_from:
      - "RandomGenericA"
    attributes:
      - name: version
        kind: Text
    relationships:
      - name: connections
        inherited: true
        cardinality: many
        peer: RandomSpecificB  # Attempt to override the peer
        kind: Component


  - name: SpecificB
    namespace: Random
    attributes:
      - name: version
        kind: Text
```
- Open the UI and try loading the page

**Comment by BeArchiTek** [comment]
Full trace:  https://github.com/user-attachments/files/16471938/traces.log

**Comment by dgarros** [comment]
I think this is related to #4004 and it should be fixed with #4005

**Comment by dgarros** [comment]
@BeArchiTek please can you double check if this bug is still present

**Comment by petercrocker** [comment]
I've just hit this issue on Infrahub 1.0.2. 

Steps to reproduce:

- Load `base/*.yml` schema files from schema library: https://github.com/opsmill/schema-library
- Load this schema extension:

```yaml
extensions:
  nodes:
    - kind: DcimDevice
      relationships:
        - name: location
          label: Location
          peer: "LocationRack"
          optional: true
          kind: Attribute
          cardinality: one
```

Result is:

- gunicorn on 4 x CPUs pegged at 100%
- Non-stop errors on infrahub-server container
- There is a valid message in there, but nearly impossible to find:

```
TypeError: Interface field DcimPhysicalDevice.location expects type NestedEdgedLocationHosting but
DcimDevice.location is type NestedEdgedLocationRack.
```
