### ISSUE TITLE
bug: can't assign a profile when changing a node in the web ui

### ISSUE THREAD

**Issue by wvandeun** [opsmill/infrahub#3999]
### Component

Frontend UI

### Infrahub version

0.16.0.dev0

### Current Behavior

You cannot click on the save button, when you edit an existing node and the only change you make is assigning a profile

### Expected Behavior

You can assign a profile to existing node without making other changes to the node

### Steps to Reproduce

- start infrahub
- load this schema
```yaml
---
version: "1.0"
nodes:
  - name: Device
    namespace: Infra
    label: "Server"
    display_labels:
      - name__value
    attributes:
      - name: name
        kind: Text
        unique: true
      - name: description
        kind: Text
        optional: true
```
- Create a InfraServer node
- Create a InfraServer profile
- Edit the existing InfraServer node in the web ui
- Assign the profile you just created
- You can't click on the save button
