### ISSUE TITLE
bug: profile schema not updated when the schema of node gets updated

### ISSUE THREAD

**Issue by wvandeun** [opsmill/infrahub#4000]
### Component

API Server / GraphQL

### Infrahub version

0.16.0.dev0

### Current Behavior

When you update the schema of an existing node it doesn't seem to update the schema of the related profile

### Expected Behavior

The schema of the profile gets updated to align with the schema updates that happen for the node

### Steps to Reproduce

- start infrahub
- load this schema
```yaml
---
version: "1.0"
nodes:
  - name: Device
    namespace: Infra
    label: "Device"
    display_labels:
      - name__value
    attributes:
      - name: name
        kind: Text
        unique: true
      - name: description
        kind: Text
        optional: true
```
- load updated schema
```yaml
---
version: "1.0"
nodes:
  - name: Device
    namespace: Infra
    label: "Server"
    display_labels:
      - name__value
    attributes:
      - name: name
        kind: Text
        unique: true
      - name: description
        kind: Text
        optional: true
      - name: enabled
        kind: Checkbox
        optional: false
```
- try to create a new Device profile in the UI (or graphql api)
- the newly added attribute `enabled` is not available in the profile

**Comment by ogenstad** [comment]
I've been looking at this and I think it's related to the `optional: false` within the `enabled` attribute.

If I load this schema as the updated version instead both options show up (i.e. `enabled` and `notes`):

```yaml
---
version: "1.0"
nodes:
  - name: Device
    namespace: Infra
    label: "Server"
    display_labels:
      - name__value
    attributes:
      - name: name
        kind: Text
        unique: true
      - name: description
        kind: Text
        optional: true
      - name: enabled
        kind: Checkbox
        optional: true
      - name: notes
        kind: Text
        optional: true
```

Would it be fair to say that this is not a bug per say, just that we don't yet support profiles for mandatory attributes?

**Comment by ogenstad** [comment]
An an update this would also work:

```yaml
---
version: "1.0"
nodes:
  - name: Device
    namespace: Infra
    label: "Server"
    display_labels:
      - name__value
    attributes:
      - name: name
        kind: Text
        unique: true
      - name: description
        kind: Text
        optional: true
      - name: enabled
        kind: Checkbox
        optional: false
        default_value: false
```

I.e. by adding a `default_value: false` to the required attribute.
