### ISSUE TITLE
task: Enable ESLint for Documentation

### ISSUE THREAD

**Issue by lykinsbd** [opsmill/infrahub#4028]
### Component

Documentation & Examples

### Task Description

Currently, in the CI pipeline, ESLint is running to check the Frontent UI, but not for the Documentation directory.

See: https://github.com/opsmill/infrahub/blob/develop/.github/workflows/ci.yml#L90

```yaml
  javascript-lint:
    if: needs.files-changed.outputs.javascript == 'true'
    needs: ["files-changed"]
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: "Check out repository code"
        uses: "actions/checkout@v4"
      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: frontend/app/package-lock.json
      - name: Install frontend dependencies
        working-directory: ./frontend/app
        run: npm install
      - name: Run ESLint
        working-directory: ./frontend/app
        run: npm run eslint
```

The Documentation files should be caught by the existing "Files Changed" check as the file filter for `javascript_all` is `"**/*.[tj]{s,sx}"`: https://github.com/opsmill/infrahub/blob/develop/.github/file-filters.yml#L54

The run of ESLint against the Documentation directory just needs to be added into the JavascriptLint CI step.
