### ISSUE TITLE
bug: cannot update on existing SchemaNode with inheritance from a generic

### ISSUE THREAD

**Issue by wvandeun** [opsmill/infrahub#4051]
### Component

API Server / GraphQL

### Infrahub version

0.16.0.dev0

### Current Behavior

When you have a schema node defined and loaded into Infrahub. You may want to update the schema node during the schema development process with a generic that you want to make it inherit from. 
This doesn't seem to work and raises an error message:
```
Unable to load the schema:
  'not_supported': InfraDevice inherit_from None
1
``` 

### Expected Behavior

The schemanode should be updated and inherit from the generic.

### Steps to Reproduce

- start empty instance of Infrahub
- load this schema
```yaml
---
version: "1.0"
generics:
  - name: Generic
    namespace: Infra
    attributes:
      - name: description
        kind: Text
        optional: true
nodes:
  - name: Device
    namespace: Infra
    label: "Device"
    display_labels:
      - name__value
    attributes:
      - name: name
        kind: Text
        unique: true
    relationships:
      - name: tags
        peer: BuiltinTag
        kind: Attribute
        cardinality: many
        optional: true
```
- load the new version of the schema, note that InfraDevice now inherites from InfraGeneric
```yaml
---
version: "1.0"
generics:
  - name: Generic
    namespace: Infra
    attributes:
      - name: description
        kind: Text
        optional: true
nodes:
  - name: Device
    namespace: Infra
    label: "Device"
    inherit_from:
      - InfraGeneric
    display_labels:
      - name__value
    attributes:
      - name: name
        kind: Text
        unique: true
    relationships:
      - name: tags
        peer: BuiltinTag
        kind: Attribute
        cardinality: many
        optional: true
```
- `infrahubctl` will give you an error message
```
Unable to load the schema:
  'not_supported': InfraDevice inherit_from None
1
```

**Comment by BaptisteGi** [comment]
Hey, I have a very similar issue, assuming I load the following schema:

```yaml
# yaml-language-server: $schema=https://schema.infrahub.app/infrahub/schema/latest.json
---
version: "1.0"
generics:
  - name: Generic
    namespace: Topology
    description: "Generic model for topology."
    label: "Topology"
    icon: "carbon:network-3"
    default_filter: name__value
    display_labels: [name__value]
    order_by: [name__value]
    include_in_menu: true
    attributes:
      - name: name
        kind: Text
        order_weight: 1000
      - name: description
        kind: Text
        order_weight: 1300
        optional: true

nodes:
  - name: MetroTopology
    namespace: Topology
    description: "Represents a topology for a given metro."
    label: "Metro Topology"
    icon: "carbon:network-enterprise"
    menu_placement: "TopologyGeneric"
    inherit_from:
      - TopologyGeneric
 ```

Then in a second time I load the exact same but with one more inheritance:
```yaml
# yaml-language-server: $schema=https://schema.infrahub.app/infrahub/schema/latest.json
---
version: "1.0"
generics:
  - name: Generic
    namespace: Topology
    description: "Generic model for topology."
    label: "Topology"
    icon: "carbon:network-3"
    default_filter: name__value
    display_labels: [name__value]
    order_by: [name__value]
    include_in_menu: true
    attributes:
      - name: name
        kind: Text
        order_weight: 1000
      - name: description
        kind: Text
        order_weight: 1300
        optional: true

nodes:
  - name: MetroTopology
    namespace: Topology
    description: "Represents a topology for a given metro."
    label: "Metro Topology"
    icon: "carbon:network-enterprise"
    menu_placement: "TopologyGeneric"
    inherit_from:
      - TopologyGeneric
      - CoreArtifactTarget # <-- My new inheritance
 ```

Here the second load fails with the same message:
```console
> infrahubctl schema load models/topo.yml
Unable to load the schema:
  'not_supported': TopologyMetroTopology inherit_from None
1
```

@dgarros do you want me to create a separated issue or do you think it falls in the same bucket as this one?
