### ISSUE TITLE
bug: enum number attribute is not using a dropdown component in the frontend

### ISSUE THREAD

**Issue by wvandeun** [opsmill/infrahub#4055]
### Component

Frontend UI

### Infrahub version

0.16.0.dev0

### Current Behavior

When you define an attribute on a node of kind Number, with specific enum variants, it renders as a regular number component in the create/edit forms.

### Expected Behavior

An attribute of kind number with enum variants, should render as a dropdown menu with the specific variants as options. 

### Steps to Reproduce

- load the following schema in infrahub
```yaml
---
version: "1.0"
nodes:
  - name: Device
    namespace: Infra
    label: "Device"
    display_labels:
      - name__value
    attributes:
      - name: name
        kind: Text
        unique: true
      - name: lines
        kind: Number
        enum:
          - 1
          - 2
          - 3
      - name: options
        kind: Text
        enum:
          - "one"
          - "two"
          - "three"
```
- open the add device form in the frontend
- the lines attribute will render as a regular number component
- the options attribute will render a a proper dropdown component
