### ISSUE TITLE
bug: Cannot add option on Number enum

### ISSUE THREAD

**Issue by bilalabbad** [opsmill/infrahub#4085]
### Component

API Server / GraphQL

### Infrahub version

0.16.0

### Current Behavior

It's impossible to add an option to a number enum.

### Expected Behavior

Being able to add option to enum that are not a string.

### Steps to Reproduce

1. load the following schema in infrahub
```yaml
---
version: "1.0"
nodes:
  - name: NumberEnum
    namespace: Demo
    label: "DemoNumberEnum"
    display_labels:
      - name__value
    attributes:
      - name: name
        kind: Text
        unique: true
      - name: lines
        kind: Number
        enum:
          - 1
          - 2
          - 3
      - name: options
        kind: Text
        enum:
          - "one"
          - "two"
          - "three"
```
2. Open the number enum
3. try to add a new number enum

alternative:
2 bis. Run:
```graphql
mutation {
  SchemaEnumAdd(
    data: { kind: "DemoNumberEnum", attribute: "lines", enum: 123 }
  ) {
    ok
    __typename
  }
}
```
