### ISSUE TITLE
bug: API server should return a propper HTTP status code when loading a schema with a schemanode that references a menu_placement that doesn't exist anymore

### ISSUE THREAD

**Issue by wvandeun** [opsmill/infrahub#4089]
### Infrahub version

0.16.0.dev0

### Current Behavior

When you load a schema with a schemanode that defines a menu_placement to a schemanode, that previously existed but has been removed, the API server returns a generic HTTP 500 status code.

In the application server logs you find a proper exception indicating the schemanode referenced in the menu_placement is invalid.

### Expected Behavior

The API server returns a proper status code (client side issue) with an error message that explains what is wrong.
`infrahubctl schema load` should then display the error message properly.

### Steps to Reproduce

- load this schema into Infrahub
```yaml
---
version: "1.0"
nodes:
  - name: ANode
    namespace: Infra
    label: "Anode"
    display_labels:
      - name__value
    attributes:
      - name: name
        kind: Text
        unique: true
  - name: BNode
    namespace: Infra
    menu_placement: "InfraANode"
    label: "BNode"
    display_labels:
      - name__value
    attributes:
      - name: name
        kind: Text
        unique: true
```
- update the schema (ANode with state absent)
```yaml
---
version: "1.0"
nodes:
  - name: ANode
    namespace: Infra
    label: "Anode"
    state: absent
    display_labels:
      - name__value
    attributes:
      - name: name
        kind: Text
        unique: true
  - name: BNode
    namespace: Infra
    menu_placement: "InfraANode"
    label: "BNode"
    display_labels:
      - name__value
    attributes:
      - name: name
        kind: Text
        unique: true
```
- load the schema using infrahubctl
- notice the generic HTTP 500 status code error message
- the application server logs show the following exception
```
--- snip ---
ValueError: InfraBNode: InfraANode is not a valid menu placement
```
