### ISSUE TITLE
bug: schema diff view in the branch detail page is not working

### ISSUE THREAD

**Issue by wvandeun** [opsmill/infrahub#4093]
### Component

Frontend UI, API Server / GraphQL

### Infrahub version

0.16.0.dev0

### Current Behavior

The schema diff view in the branch detail page is now showing schema changes when you made changes to the schema in that branch.

The schema diff view for a proposed change for that same branch will show you the schema diff.

### Expected Behavior

The branch detail page should show the schema diff

### Steps to Reproduce

- spin up instance of infrahub
- create a new branch
- load this schema in that newly created branch
```yaml
---
version: "1.0"
nodes:
  - name: ANode
    namespace: Infra
    label: "ANode"
    display_labels:
      - name__value
    attributes:
      - name: name
        kind: Text
        unique: true
    relationships:
      - name: other_node
        peer: InfraBNode
        kind: Attribute
        cardinality: one
  - name: BNode
    namespace: Infra
    menu_placement: InfraANode
    label: "BNode"
    display_labels:
      - name__value
    attributes:
      - name: name
        kind: Text
        unique: true
```
- in the frontend open the branch detail page, click on diff and open the schema tab

### Additional Information

Tagged the issue for both frontend and backend, didn't look into the details to determine where the issue exactly is.
