### ISSUE TITLE
bug: edit form node shows empty input field for required relationships of cardinality many

### ISSUE THREAD

**Issue by wvandeun** [opsmill/infrahub#4102]
### Component

Frontend UI

### Infrahub version

0.16.0.dev0

### Current Behavior

The node edit form shows an empty input field for a node that has a required relationship of cardinality many, when such relationship to a related node exists.

### Expected Behavior

The related node is properly shown in the node edit form.

### Steps to Reproduce

- spin up infrahub
- load this schema
```yaml
---
version: "1.0"
nodes:
  - name: ANode
    namespace: Infra
    label: "ANode"
    display_labels:
      - name__value
    attributes:
      - name: name
        kind: Text
        unique: true
    relationships:
      - name: other_node
        peer: InfraBNode
        label: Other node
        cardinality: many
        optional: false
  - name: BNode
    namespace: Infra
    menu_placement: InfraANode
    label: "BNode"
    display_labels:
      - name__value
    attributes:
      - name: name
        kind: Text
        unique: true
```
- Create an InfraANode (and create the required relationship to BNode)
- Open the created ANode in the node detailed view
- Click edit object
- The Other node input field will show up as empty
