### ISSUE TITLE
bug: create/edit node form does not jump back to dropdown input field if it is required but no input is provided

### ISSUE THREAD

**Issue by wvandeun** [opsmill/infrahub#4103]
### Component

Frontend UI

### Infrahub version

0.16.0.dev0

### Current Behavior

The create/edit node form has the ability to jump back to a certain input if a mistake was made by the user and the user tries to submit the form (for example a required input is not provided).  However when one of the inputs in the form is a dropdown it doesn't jump back to the dropdown input if it is off screen.  This is confusing to the user as their is no visual to indicate something is wrong and that we expect them to correct something.

### Expected Behavior

The form would jump back to the dropdown input field that has the error, or there is some other visual indication that something is wrong that describes what we expect the user to correct.

### Steps to Reproduce

- spin up Infrahub
- load this schema
```yaml
---
version: "1.0"
nodes:
  - name: ANode
    namespace: Infra
    label: "ANode"
    display_labels:
      - name__value
    attributes:
      - name: name
        kind: Text
        optional: false
      - name: name1
        kind: Text
        optional: false
      - name: name2
        kind: Number
        enum:
          - 1
          - 2
          - 3
        optional: false
      - name: name3
        kind: Text
        optional: false
      - name: name4
        kind: Text
        optional: false
      - name: name5
        kind: Text
        optional: false
      - name: name6
        kind: Text
        optional: false
      - name: name7
        kind: Text
        optional: false
      - name: name8
        kind: Text
        optional: false
      - name: name9
        kind: Text
        optional: false
      - name: name10
        kind: Text
        optional: false
      - name: name11
        kind: Text
        optional: false
      - name: name12
        kind: Text
        optional: false
      - name: name13
        kind: Text
        optional: false
```
- In the frontend create a new ANode object
- Input values for all the attributes, except name2
- Click save to submit the form
- The form will not jump back to the input dropdown for name2
- There is no visual indication of what is wrong until the user scrolls back to the name2 input field
