### ISSUE TITLE
bug: hfid for a schema node is not auto generated when using uniqueness_constraints

### ISSUE THREAD

**Issue by wvandeun** [opsmill/infrahub#4174]
### Component

API Server / GraphQL

### Infrahub version

0.16.0.dev0

### Current Behavior

When you define a single uniqueness_constraint on a schema node, the hfid property of the schema node is not automatically generated.

When you do the same, but instead use the `unique` property on the attribute then the HFID is automatically generated.

### Expected Behavior

The HFID is auto generated for a schema node if the unqiueness constraint is on a single attribute defined using the uniqueness_constraints property.

### Steps to Reproduce

- Start an instance of Infrahub
- Load this schema
```yaml
---
version: "1.0"
nodes:
  - name: Test
    namespace: Testing
    uniqueness_constraints:
      - ["aaa__value"]
    attributes:
      - name: aaa
        kind: Text
      - name: bbb
        kind: Text
```
- run the following python code
```python
from infrahub_sdk import InfrahubClientSync
client = InfrahubClientSync()
node_schema = client.schema.get("TestingTest")
assert node_schema.human_friendly_id is None
```

**Comment by wvandeun** [comment]
additionally when you try to load the following schema:
```yaml
---
version: "1.0"
nodes:
  - name: Test
    namespace: Testing
    human_friendly_id:
      - aaa__value
    uniqueness_constraints:
      - ["aaa__value"]
    attributes:
      - name: aaa
        kind: Text
      - name: bbb
        kind: Text
```
You get the following error message when trying to load it
```
Unable to load the schema:
  At least one attribute must be unique in the human_friendly_id for TestingTest.
```

**Comment by wvandeun** [comment]
in the documentation we state the following

However, when you try to load this schema, it fails with an error message.
```yaml
---
version: "1.0"
nodes:
  - name: Test
    namespace: Testing
    human_friendly_id:
      - aaa__value
    attributes:
      - name: aaa
        kind: Text
      - name: bbb
        kind: Text
```
```
Unable to load the schema:
  At least one attribute must be unique in the human_friendly_id for TestingTest.
```
