### ISSUE TITLE
bug: cannot define an HFID which is equal to the uniqueness_constraint

### ISSUE THREAD

**Issue by wvandeun** [opsmill/infrahub#4181]
### Component

API Server / GraphQL

### Infrahub version

0.16.0.dev0

### Current Behavior

When you try to load the following schema into Infrahub, you get an error message 

```
Unable to load the schema:
  At least one attribute must be unique in the human_friendly_id for TestingTest.
```

```yaml
---
version: "1.0"
nodes:
  - name: Test
    namespace: Testing
    human_friendly_id:
      - aaa__value
    uniqueness_constraints:
      - ["aaa__value"]
    attributes:
      - name: aaa
        kind: Text
      - name: bbb
        kind: Text
```

This is wrong, we defined a uniqueness_constraint that defines that the value of the `aaa` attribute must be unique, therefor we should be able to use if for the HFID.

### Expected Behavior

I would expect that we can use attributes, defined as unique within the `uniqueness_constraint` option to construct the HFID. 

### Steps to Reproduce

- start an instance of Infrahub
- load the following schema using `infrahubctl`

```yaml
---
version: "1.0"
nodes:
  - name: Test
    namespace: Testing
    human_friendly_id:
      - aaa__value
    uniqueness_constraints:
      - ["aaa__value"]
    attributes:
      - name: aaa
        kind: Text
      - name: bbb
        kind: Text
```
