### ISSUE TITLE
bug: attribute that is defined as unique is not listed as a uniqueness_constraint in the schema detailed view

### ISSUE THREAD

**Issue by wvandeun** [opsmill/infrahub#4182]
### Component

API Server / GraphQL

### Infrahub version

0.16.0.dev0

### Current Behavior

When you define an attribute as unique on a node in the schema, it is not listed as a `uniqueness_constraint` in the schema view. 

### Expected Behavior

The attribute that is defined as unique would be listed as one of the uniqueness_constraints

### Steps to Reproduce

- start an instance of Infrahub
- load this schema
```yaml
---
version: "1.0"
nodes:
  - name: Customer
    namespace: Testing
    attributes:
      - name: name
        kind: Text
        optional: false
        unique: true
```
- In the web interface go to schema
- Select the TestinCustomer node
- Unique constraints field will be empty
