### ISSUE TITLE
bug: cannot load a schema with a schema node that defines an HFID on an attribute that is not set as unique

### ISSUE THREAD

**Issue by wvandeun** [opsmill/infrahub#4186]
### Component

API Server / GraphQL

### Infrahub version

0.16.0.dev0

### Current Behavior

You cannot load a schema that contains a schema node with an HFID defined on an attribute, if the attribute is not set as unique.

The documentation states the following in the HFID section of the schema topic:
If a human_friendly_id is defined on a node but no uniqueness_constraints are present, a uniqueness constraints matching the human_friendly_id will be automatically created.

### Expected Behavior

Based on the documentation, I would expect that the schema would load and the proper unique constraint would be generated/applied by Infrahub.

### Steps to Reproduce

- start an instance of Infrahub
- try loading the following schema
```
---
version: "1.0"
nodes:
  - name: Test
    namespace: Testing
    human_friendly_id:
      - aaa__value
    attributes:
      - name: aaa
        kind: Text
      - name: bbb
        kind: Text
```
- you get an error message
```
Unable to load the schema:
  At least one attribute must be unique in the human_friendly_id for TestingTest.
```
