### ISSUE TITLE
bug:  Failure when loading multiple YAML schema files with `extensions`

### ISSUE THREAD

**Issue by BeArchiTek** [opsmill/infrahub#4188]
### Component

API Server / GraphQL

### Infrahub version

0.15.3

### Current Behavior

When loading multiple schema files while using `extensions`, the process can fail due to the order in which the files are loaded.

Since the extensions are processed per file, their dependencies and interactions between files can cause issues if the schemas are not loaded in a specific order.

This behavior can be problematic, especially when managing large or interdependent schema files.

### Expected Behavior

extensions should be load "after" the generics and nodes

### Steps to Reproduce

Giving this 2 schema files

**first.yml**
```yaml
# yaml-language-server: $schema=https://schema.infrahub.app/infrahub/schema/latest.json
---
version: '1.0'

nodes:
  - name: Model
    namespace: Random
    default_filter: name__value
    display_labels:
      - name__value
    order_by:
      - name__value
    human_friendly_id:
      - "name__value"
    attributes:
      - name: name
        kind: Text
        unique: true
      - name: description
        kind: Text
        optional: true
    relationships:
      - name: organization
        peer: RandomOrganization
        identifier: organization__model
        cardinality: one
        kind: Attribute


extensions:
  nodes:
    # Organization Extensions
    - kind: RandomOrganization
      relationships:
        - name: models
          label: "Device Models"
          identifier: organization__model
          peer: RandomModel
          optional: true
          cardinality: many
          kind: Component

```

**second.yml**
```yaml
# yaml-language-server: $schema=https://schema.infrahub.app/infrahub/schema/latest.json
---
version: '1.0'

nodes:
  - name: Organization
    namespace: Random
    attributes:
      - name: name
        kind: Text
        unique: true
      - name: description
        kind: Text
        optional: true

```

- use infrahubctl to load both first.yml and second.yml from a directory
`infrahuctl schema load models/*`

it will failed with 
```console
Unable to load the schema:
  Unable to find the schema 'RandomOrganization' in the registry
```

Rename `second.yml` to `1-second.yml` to load it before first, and it will succeeded 

### Additional Information

I think the issue is in the backend, when loading several files :
https://github.com/opsmill/infrahub/blob/033af52fb93c703b4c5e829dbb939ec6183d1d71/backend/infrahub/api/schema.py#L231

call 
https://github.com/opsmill/infrahub/blob/033af52fb93c703b4c5e829dbb939ec6183d1d71/backend/infrahub/api/schema.py#L118
which call https://github.com/opsmill/infrahub/blob/033af52fb93c703b4c5e829dbb939ec6183d1d71/backend/infrahub/core/schema_manager.py#L446
