### ISSUE TITLE
bug: artifact does not get regenerated when the transformation graphqlquery returns new nodes that are not part of the CoreGraphQLQueryGroup 

### ISSUE THREAD

**Issue by wvandeun** [opsmill/infrahub#4198]
### Component

API Server / GraphQL

### Infrahub version

0.16.0.dev0

### Current Behavior

Given the following schema
```yaml
---
version: "1.0"
nodes:
  - name: Interface
    namespace: Infra
    uniqueness_constraints:
      - ["device", "name__value"]
    attributes:
      - name: name
        kind: Text
        optional: false
    relationships:
      - name: device
        peer: InfraDevice
        optional: false
        cardinality: one
        kind: Parent
  - name: Device
    namespace: Infra
    human_friendly_id:
      - "name__value"
    attributes:
      - name: name
        kind: Text
        unique: true
        optional: false
    relationships:
      - name: interfaces
        peer: InfraInterface
        cardinality: many
        optional: true
        kind: Component
  - name: Server
    namespace: Infra
    attributes:
      - name: name
        kind: Text
        optional: false
        unique: true
```
And the following GraphQLQuery used in a jinja2 transform, for which we have an artifact definition that is imported into Infrahub from a Git repository

```graphql
query device_config($device: String!) {
  InfraDevice(name__value: $device) {
    edges {
      node {
	name {
	  value
	}
	interfaces {
	  edges {
	    node {
	      name {
		value
	      }
	    }
	  }
	}
      }
    }
  }
  InfraServer {
    edges {
      node {
	name {
	  value
	}
      }
    }
  }
}
```

```yaml
---
jinja2_transforms:
  - name: "device_config"
    query: "device_config"
    template_path: "templates/device_config.j2"

queries:
  - name: "device_config"
    file_path: "templates/device_config.gql"

artifact_definitions:
  - name: "Device configuration"
    artifact_name: "device-configuration"
    parameters:
      device: "name__value"
    content_type: "text/plain"
    targets: "devices"
    transformation: "device_config"
```

Assuming we have a generated artifcat for a device in the main branch.

When you create a new branch, and add a new `InfraServer` node, the existing device_config artifact does not get regenerated when you open a proposed change to merge the branch into the main branch.

### Expected Behavior

Since the `InfraServer` nodes are in the scope of the GraphQL query and therefor they affect the artifact for a given target, I would assume that the artifact gets regenerated.

### Steps to Reproduce

- create a new git repository
- define the following `.infrahub.yml` file at the root of the project
```yaml
---
jinja2_transforms:
  - name: "device_config"
    query: "device_config"
    template_path: "templates/device_config.j2"

queries:
  - name: "device_config"
    file_path: "templates/device_config.gql"

artifact_definitions:
  - name: "Device configuration"
    artifact_name: "device-configuration"
    parameters:
      device: "name__value"
    content_type: "text/plain"
    targets: "devices"
    transformation: "device_config"
```
- create a templates directory at the root of the project
- in the templates directory create a file `device_config.gql` with the following contents
```graphql
query device_config($device: String!) {
  InfraDevice(name__value: $device) {
    edges {
      node {
	name {
	  value
	}
	interfaces {
	  edges {
	    node {
	      name {
		value
	      }
	    }
	  }
	}
      }
    }
  }
  InfraServer {
    edges {
      node {
	name {
	  value
	}
      }
    }
  }
}
```
- create a file `device_config.j2` in the templates directory with the following contents
```jinja2
hostname {{ data["InfraDevice"]["edges"][0]["node"]["name"]["value"] }}

{% for interface in
  data["InfraDevice"]["edges"][0]["node"]["interfaces"]["edges"] %}
interface {{ interface["node"]["name"]["value"] }}
{% endfor %}

{% for server in data["InfraServer"]["edges"] %}
server {{ server["node"]["name"]["value"] }}
{% endfor %}
```
- commit changes
- push the repository to a remote on a git server
- spin up an instance of Infrahub
- load the following schema
```yaml
---
version: "1.0"
nodes:
  - name: Interface
    namespace: Infra
    uniqueness_constraints:
      - ["device", "name__value"]
    attributes:
      - name: name
        kind: Text
        optional: false
    relationships:
      - name: device
        peer: InfraDevice
        optional: false
        cardinality: one
        kind: Parent
  - name: Device
    namespace: Infra
    human_friendly_id:
      - "name__value"
    attributes:
      - name: name
        kind: Text
        unique: true
        optional: false
    relationships:
      - name: interfaces
        peer: InfraInterface
        cardinality: many
        optional: true
        kind: Component
  - name: Server
    namespace: Infra
    attributes:
      - name: name
        kind: Text
        optional: false
        unique: true
```
- create a CoreStandardGroup `devices`
- create a `InfraDevice` with name `device`
- add the InfraDevice to the devices group
- create an `InfraInterface` with name `Ethernet1` and add a relationship to InfraDevice `device`
- create an `InfraServer` with name `logging`
- create the repository in Infrahub and let is sync
- verify that you have a `device_config` for `device`
- create a branch `test`
- create a new `InfrasServer` named `tacacs` in the branch
- open a proposed change to merge branch test into main
- the artifact device_config for node device will not be regenerated
