### ISSUE TITLE
feature: Extend schema to support additional parameters per attribute kind

### ISSUE THREAD

**Issue by dgarros** [opsmill/infrahub#4246]
### Component

API Server / GraphQL

### Describe the Feature Request

Currently the definition of an attribute in the schema is done in a flat dictionary and we have multiple options available at the top level that are only applicable for some kind of artifacts like `regex`, `max_length` or `min_length`.

The goal is to extend the format of the current schema to add a new section `spec` or `parameters` that will accept different values depending on the kind of the attribute. As an example, For an attribute of kind `Text` it should be possible to define `regex`, `max_length` or `min_length` and for an attribute of kind number if should be possible to define `min_value` or `max_value` (#2967)

```yaml
      - name: name
        kind: Text
        spec:
           regex: xxx
           max_length: 32
           min_length: 8
```

```yaml
      - name: size
        kind: Number
        spec:
           regex: xxx
           min: 8
           max: 16
```

### Describe the Use Case

Improve the capabilities of the schema and provide the constraints available per attribute.

### Additional Information

to ease the migration to the new format, we need to continue supporting the existing field for the time being and at some point we'll need to mark them as deprecated #4245
