### ISSUE TITLE
bug: prefix and address attribute filters are not available in the SDK for nodes inheriting from BuiltinIPPrefix or BuiltinIPAddress 

### ISSUE THREAD

**Issue by wvandeun** [opsmill/infrahub#4270]
### Component

Python SDK

### Infrahub version

0.12.4

### Current Behavior

In the SDK it is not possible to use the attribute filters for the prefix attribute of a node that inherits from BuiltinIPPrefix.
Similarly you can use the attribute filters for the address attribute of a node that inherits from BuiltinIPAddress.

The attribute filters are available and working when using a GraphQL.

### Expected Behavior

We can use the prefix/address attribute filters in the SDK.

### Steps to Reproduce

- start an Infrahub instance
- load this schema
```yaml
---
version: "1.0"
nodes:
  - name: IPPrefix
    namespace: Ipam
    include_in_menu: false
    inherit_from:
      - "BuiltinIPPrefix"
    description: "IPv4 or IPv6 network"
    label: "IP Prefix"
  - name: IPAddress
    namespace: Ipam
    include_in_menu: false
    inherit_from:
      - "BuiltinIPAddress"
    description: "IP Address"
    label: "IP Address"
```
- Create an IP Prefix '10.0.0.0/16' and and IP Address '10.0.0.1/32' using the frontend
- Spin up a Python interpreter
- Execute the following statements
``` python
from infrahub_sdk import InfrahubClientSync
client = InfrahubClientSync()
client.get("IpamIPPrefix", prefix__value="10.0.0.0/16")
client.get("IpamIPAddress", prefix__value="10.0.0.1/32")
```
- When you check the available filters in the schema using the SDK, they don't seem to be available
```python
for filter in client.schema.get("IpamIPPrefix").filters:
    print(filter.name)
```
