### ISSUE TITLE
bug: showing members of a group displays an error message when the member has an attribute named `type` which is used for the `display_label` of the node

### ISSUE THREAD

**Issue by wvandeun** [opsmill/infrahub#4289]
### Component

API Server / GraphQL

### Infrahub version

0.16.0.dev0

### Current Behavior

You are unable to see the members of a CoreStandardGroup in the front end, when one of the members has an attribute with the name `type` and that attribute is used for the `display_label` of the node.

### Expected Behavior

We should be able to see the members of the group in the front end.

### Steps to Reproduce

- start instance of Infrahub
- load the following schema
```yaml
---
version: "1.0"
nodes:
  - name: Thing
    namespace: Infra
    label: Test
    display_labels:
      - type__value
    attributes:
      - name: type
        kind: Text
        optional: false
```
- create an instance of an InfraThing node
- create a new standard group
- add the InfraThing instance to the group
- open the group detail view
- click on the members tab
- you will get an error message
<img width="347" alt="image" src="https://github.com/user-attachments/assets/9b59be93-b827-4421-b51c-260eebffe2fa">

### Additional Information

Using the following GraphQL Query we can to the same result
```graphql
query {
  CoreStandardGroup {
    edges {
      node {
        name {
          value
        }
        members {
          edges {
            node {
              id
              display_label
            }
          }
        }
      }
    }
  }
}
```

However querying for the node and its display_label just works

```graphql
query {
  InfraThing {
    edges {
      node {
        display_label
      }
    }
  }
}
```
