### ISSUE TITLE
bug: removing a relationship from a generic does not remove the relationship from the nodes inheriting from the generic

### ISSUE THREAD

**Issue by wvandeun** [opsmill/infrahub#4301]
### Component

API Server / GraphQL

### Infrahub version

0.16.0.dev0

### Current Behavior

When you delete a relationship from a generic in the schema, the relationship does not get removed from the nodes in the schema that inherit from the generic.

### Expected Behavior

The relationship would be removed from the nodes inheriting from the generic

### Steps to Reproduce

- start Infrahub instance
- load this schema
```yaml
---
version: "1.0"
generics:
  - name: Generic
    namespace: Infra
    attributes:
      - name: description
        kind: Text
        optional: true
    relationships:
      - name: other_thing
        peer: InfraOtherThing
        kind: Attribute
        cardinality: one
        optional: true
nodes:
  - name: Thing
    namespace: Infra
    label: Thing
    inherit_from:
      - InfraGeneric
    attributes:
      - name: name
        label: Name
        kind: Text
        optional: false
        unique: true
  - name: OtherThing
    namespace: Infra
    label: OtherThing
    attributes:
      - name: name
        label: Name
        kind: Text
        optional: false
        unique: true
```
- once the schema is loaded, load this schema which removed the relationship from the generic
```yaml
---
version: "1.0"
generics:
  - name: Generic
    namespace: Infra
    attributes:
      - name: description
        kind: Text
        optional: true
    relationships:
      - name: other_thing
        peer: InfraOtherThing
        kind: Attribute
        state: absent
        cardinality: one
        optional: true
nodes:
  - name: Thing
    namespace: Infra
    label: Thing
    inherit_from:
      - InfraGeneric
    attributes:
      - name: name
        label: Name
        kind: Text
        optional: false
        unique: true
  - name: OtherThing
    namespace: Infra
    label: OtherThing
    attributes:
      - name: name
        label: Name
        kind: Text
        optional: false
        unique: true
```
- check the schema of the generic, the relationship will have been removed
- check the schema of the InfraThing node, the relationship will still exist
