### ISSUE TITLE
bug: loading a schema that has a relationship with state absent property defined will still create the relationship if the node does not exist

### ISSUE THREAD

**Issue by wvandeun** [opsmill/infrahub#4302]
### Component

API Server / GraphQL

### Infrahub version

0.16.0.dev0

### Current Behavior

When you load a schema, that defines a new node, which has a relationship defined with the `state: absent` property, then the relationship will be created on the node.

This is a situation that could happen when someone loads existing schema files into a new instance of Infrahub.

### Expected Behavior

Since the relationship is defined with the `state: absent` property, it should not be created.

### Steps to Reproduce

- start an instance of Infrahub
- load this schema
```yaml
---
version: "1.0"
nodes:
  - name: Thing
    namespace: Infra
    label: Thing
    attributes:
      - name: name
        label: Name
        kind: Text
        optional: false
        unique: true
    relationships:
      - name: other_thing
        peer: InfraOtherThing
        kind: Attribute
        state: absent
        cardinality: one
        optional: true
  - name: OtherThing
    namespace: Infra
    label: OtherThing
    attributes:
      - name: name
        label: Name
        kind: Text
        optional: false
        unique: true
```
- check the `InfraThing` schema, you will see that the `other_thing` relationship has been defined
- load the schema file a second time
- the relationship will have been removed

**Comment by BaptisteGi** [comment]
Very similar behavior with Nodes as well:

```yml
# yaml-language-server: $schema=https://schema.infrahub.app/infrahub/schema/latest.json
---
version: "1.0"

nodes:
  - name: Stuff
    namespace: Random
    state: absent
    description: Random stuff
    attributes:
      - name: first
        kind: Text
        unique: true
        order_weight: 1000
      - name: second
        kind: Text
        unique: true
        order_weight: 2000
```

When loading the above schema in a blank infrahub instance I expect nothing to be created as state is set to absent. However node is still created.
