### ISSUE TITLE
bug: Number Resource Pool Skips Increment After Object Creation Fails

### ISSUE THREAD

**Issue by BeArchiTek** [opsmill/infrahub#4303]
### Component

API Server / GraphQL

### Infrahub version

0.16.0

### Current Behavior

When attempting to create a `DummyNumber` object with a Number Resource Pool, if the creation fails for a reason unrelated to the number pool (such as a validation error or missing required fields), the next number generated from the pool increments by the number of failed attempts instead of only incrementing by 1.

### Expected Behavior

- The number generated from the Number Resource Pool should only increment by 1 after each successful creation.
- If object creation fails, the number from the pool should not be incremented, and the same number should be attempted again until the creation is successful.

### Steps to Reproduce

- Start an instance of Infrahub
- Load this schema

```yaml
version: "1.0"

nodes:
  - name: Number
    namespace: Dummy
    description: "A dummy model to demonstrate number resource pool."
    label: "Dummy Number"
    icon: mdi:numeric
    attributes:
      - name: name
        kind: Text
        unique: true
      - name: random
        kind: Number
        description: "A number generated from the number pool."
```

- Create a new Number Resource Pool
```graphql
mutation AddNumberPool {
  CoreNumberPoolCreate(
    data: {
      name: {value: "dummy-number-pool"},
      node: {value: "DummyNumber"},
      node_attribute: {value: "random"},
      start_range: {value: 1},
      end_range: {value: 100}
    }
  ) {
    ok
    object {
      hfid
    }
  }
}
```

- Create a new DummyNumber with this query
```graphql
mutation DummyNumberCreate {
  InfraDummyNumberCreate(
    data: {
      name: {value: "tmp"}
      random: {from_pool: {id: "YOUR_POOL_ID"}},
    }
  ) {
    ok
    object {
      hfid
    }
  }
}
```

- Re-run the same query a second time to get a fail (due to unicity of the name)
- Re-run the query with another `name` like tmp1 or tmp2
- Check the Number used
