### ISSUE TITLE
bug: UI error due to incorrect `order_by` Field in Schema

### ISSUE THREAD

**Issue by BeArchiTek** [opsmill/infrahub#4323]
### Component

Frontend UI, Python SDK

### Infrahub version

0.16

### Current Behavior

```yaml
version: '1.0'
nodes:
  - name: FaultyModel
    namespace: Dummy
    description: "A dummy model with incorrect order_by"
    label: "Faulty Model"
    order_by:
      - name  # Incorrect, should be 'name__value'
    display_labels:
      - name__value
    attributes:
      - name: name
        kind: Text
        description: "The name of the model"
        unique: true
      - name: description
        kind: Text
        description: "Optional description of the model"
        optional: true
```

When loading this schema in infrahuctl, everything works fine, but the UI breaks when trying to access the model page. The issue stems from an incorrect order_by field in the schema. Specifically, the field lacks the required __value suffix.

### Expected Behavior

Schema should not be load 

### Steps to Reproduce

- Load the schema with infrahuctl.
- Access the UI page for the model.
- Observe the UI crash.
