### ISSUE TITLE
bug: wrong display_label when using an enum attribute 

### ISSUE THREAD

**Issue by wvandeun** [opsmill/infrahub#4382]
### Component

API Server / GraphQL

### Infrahub version

0.16.0

### Current Behavior

When you defined `display_labels` that references an enum attribute, it renders the display_label as `<attr_name>Enum.<variant>`, where attr_name is the name of the attribute and variant is the value. 

### Expected Behavior

The display label should use the string version of the enum variant for the attribute that we defined in the schema.

### Steps to Reproduce

- start an instance of Infrahub
- load the following schema
```yaml
---
version: "1.0"
nodes:
  - name: Node
    namespace: Infra
    display_labels:
      - test__value
    attributes:
      - name: test
        kind: Text
        optional: false
        enum:
          - one
          - two
```
- create a InfraNode instance, pick `one` as the value for the test attribute
- execute the following graphql query
```graphql
query {
  InfraNode {
    edges {
      node {
        display_label
      }
    }
  }
}
```
- the `display_label` will be rendered as `TestEnum.ONE`
