### ISSUE TITLE
bug: cannot save a node with required boolean attribute

### ISSUE THREAD

**Issue by fatih-acar** [opsmill/infrahub#4418]
### Component

Frontend UI

### Infrahub version

0.16.0

### Current Behavior

When trying to save a node that has a an required boolean value, we get this error:

![image](https://github.com/user-attachments/assets/f8ab0812-086a-44c5-afc1-07e262e40023)

### Expected Behavior

We should be able to save a node with the checkbox unchecked (set to false).

### Steps to Reproduce

Create a schema with a node with required boolean attribute.
Try to create that node without checking the checkbox.

**Comment by dgarros** [comment]
look similar to https://github.com/opsmill/infrahub/issues/823
Could it be a regression introduced by the refactoring of the form ?

**Comment by ogenstad** [comment]
Is the headline correct here? Looking at the screenshot it looks like "Is public" is a required value and not an optional one?

However there can still be a problem as `false` would be a valid response here. Not sure how it would look in the UI but a problem might be that if we don't set a default_value in the schema just setting the form to `false` is in itself a choice and on some forms it should perhaps default to a `null` value to indicate that nothing has been chosen. However if the user wants to set this to `false ` they shouldn't be required to first check it and then uncheck it..

**Comment by fatih-acar** [comment]
Yes sorry, I actually meant required...
And yes, the user should not need to check and uncheck the box to complete the form...

**Comment by bilalabbad** [comment]
Can you share the schema please?

**Comment by fatih-acar** [comment]
```
# yaml-language-server: $schema=https://schema.infrahub.app/infrahub/schema/latest.json
---
version: '1.0'
generics:
  - name: BackupLocation
    namespace: Cloud
    description: "Backup location"
    label: "Backup location"
    display_labels:
      - name__value
    attributes:
      - name: name
        kind: Text
      - name: prefix
        kind: Text
        optional: true
      - name: is_public
        kind: Boolean
      - name: created_at
        kind: DateTime
      - name: updated_at
        kind: DateTime
      - name: organization_id
        kind: Text
nodes:
  - name: S3BackupLocation
    namespace: Cloud
    description: "S3 Backup location"
    label: "S3 Backup location"
    inherit_from:
      - CloudBackupLocation
    display_labels:
      - name__value
    attributes:
      - name: endpoint
        kind: URL
      - name: region
        kind: Text
        optional: true
      - name: access_key_id
        kind: Text
      - name: secret_access_key
        kind: Password
```
