### ISSUE TITLE
bug: upsert mutation for a node fails when the HFID is using an Number attribute 

### ISSUE THREAD

**Issue by wvandeun** [opsmill/infrahub#4460]
### Component

API Server / GraphQL

### Infrahub version

0.16.1

### Current Behavior

A GraphQL upsert mutation for a node that has an HFID that contains an attribute of kind Number, fails with the following error mesage:
```
{
  "data": {
    "TestNodeUpsert": null
  },
  "errors": [
    {
      "message": "sequence item 0: expected str instance, int found",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "TestNodeUpsert"
      ]
    }
  ]
}
```

### Expected Behavior

We should be able to use a number attribute as part of the HFID.

In 0.16.1 we introduced a feature that constructs the HFID of a node for an upsert mutation, if it was not provided as part of the mutation. In that code we don't seem to consider the fact that an attribute could be something else than a string.

### Steps to Reproduce

- spin up instance of Infrahub
- load this schema
```yaml
---
version: "1.0"
nodes:
 - name: Node
   namespace: Test
   human_friendly_id:
     - node_id__value
   attributes:
     - name: node_id
       kind: Number
       optional: false
```
- execute the following mutation
```graphql
mutation {
  TestNodeUpsert(data: {node_id: {value: 1}}) {
    ok
  }
}
```
