### ISSUE TITLE
bug: uniqueness constraints are not ensured on concurrent create/update

### ISSUE THREAD

**Issue by fatih-acar** [opsmill/infrahub#4503]
### Component

API Server / GraphQL

### Infrahub version

0.16.1

### Current Behavior

Creating nodes currently that use the same value for an unique attribute is allowed and we end up with duplicate entries.

### Expected Behavior

Running the above script should create only one node and subsequent creations should fail.

### Steps to Reproduce

Using the following schema:

```
nodes:
  - name: Service
    namespace: Cloud
    display_labels:
     - name__value
    attributes:
      - name: name
        kind: Text
        unique: true
```

If you run the following script that creates multiple nodes with the same `name` attribute:

```
#!/usr/bin/env python3

import threading
import time
from infrahub_sdk import InfrahubClientSync

def create_node():
    client = InfrahubClientSync()
    node = client.create(kind="CloudService", data={"name": "Unique"})
    node.save()

for i in range(10):
    threading.Thread(name=f"t{i}", target=create_node).start()

time.sleep(2)
```

You end up with many nodes.

### Additional Information

Might be related to #3272
