### ISSUE TITLE
bug: Unable to reach the detailed view of a Node when there is no attribute

### ISSUE THREAD

**Issue by BeArchiTek** [opsmill/infrahub#4538]
### Component

Frontend UI

### Infrahub version

0.16.2

### Current Behavior

When a node doesn't have any attribute, and is only composed of relationships, all the fields send me the related objects. 
So I cannot click on it in the list view and reach the detailed view of the object. 

A loom explaining the test: https://www.loom.com/share/dda3ca8b846547d2b71a660c241b6157

### Expected Behavior

I am able to see the detailled view of the node

### Steps to Reproduce

Using this schema
```yaml
---
version: '1.0'

nodes:
  - name: Test
    namespace: Demo
    description: "A test node with no attributes, only a relationship to tags."
    relationships:
      - name: tags
        peer: BuiltinTag
        cardinality: many
        kind: Attribute

  - name: Random
    namespace: Demo
    description: "Another test node with no attributes, only a relationship to tags."
    relationships:
      - name: tests
        peer: DemoTest
        cardinality: one
        kind: Component
      - name: tags
        label: Tags
        peer: BuiltinTag
        cardinality: many
        kind: Attribute
```

- create a new tag
- create a new node of DemoTest, try to click on it
- create a new node of DemoRandom, try to click on it
