### ISSUE TITLE
bug: unable to set a value for an attribute on a node that existed before the attribute was deleted from the schema and then was added back to the schema

### ISSUE THREAD

**Issue by wvandeun** [opsmill/infrahub#4727]
### Component

API Server / GraphQL

### Infrahub version

0.16.4

### Current Behavior

When you delete an attribute of a schemanode and later on recreate it, you are unable to set a value for that attribute on nodes that existed prior to deletion of the attribute from the schemanode.

You can set a value for the attribute for nodes that were created after the deletion of the attribute from the schemanode.

### Expected Behavior

You should be able to set an attribute value for a node that existed prior to the deletion of the attribute from the schemanode.

### Steps to Reproduce

- spin up instance of Infrahub
- load the following schema
```yaml
---
version: "1.0"
nodes:
  - name: Node
    namespace: Some
    attributes:
      - name: name
        kind: Text
        optional: false
        unique: true
      - name: node_type
        kind: Dropdown
        choices:
          - name: type_one
          - name: type_two
        optional: true
```
- create an instance of SomeNode
- load the following schema to delete the `node_type` attribute
```yaml
---
version: "1.0"
nodes:
  - name: Node
    namespace: Some
    attributes:
      - name: name
        kind: Text
        optional: false
        unique: true
      - name: node_type
        kind: Dropdown
        state: "absent"
        choices:
          - name: type_one
          - name: type_two
        optional: true
```
- load the following schema, which recreates the node_type attribute
```yaml
---
version: "1.0"
nodes:
  - name: Node
    namespace: Some
    attributes:
      - name: name
        kind: Text
        optional: false
        unique: true
      - name: node_type
        kind: Dropdown
        choices:
          - name: type_one
          - name: type_two
        optional: true
```
- set a value for the node_type attribute on the node you created before, the attribute value will not show in the UI or when you query the node using GraphQL
- create a new SomeNode node, the attribute value will be properly saved for the new node
