### ISSUE TITLE
bug: HFID is not generated for a profile

### ISSUE THREAD

**Issue by wvandeun** [opsmill/infrahub#4758]
### Component

API Server / GraphQL

### Infrahub version

1.0.0.dev.0

### Current Behavior

Infrahub does not seem to generate an HFID for a profile of a given node.

### Expected Behavior

A profile has a unique attribute, the profile_name, which we should be able to use as the HFID of the profile.

### Steps to Reproduce

- spin up instance of Infrahub
- load the following schema
```yaml
---
version: "1.0"
nodes:
  - name: Interface
    namespace: Infra
    description: "Network Interface"
    label: "Interface"
    include_in_menu: true
    display_labels:
      - name__value
    order_by:
      - name__value
    uniqueness_constraints:
    attributes:
      - name: name
        kind: Text
        optional: false
        unique: true
      - name: description
        kind: Text
        optional: true
      - name: speed
        kind: Number
        optional: true
      - name: auto_negotiation
        kind: Boolean
        default_value: false
      - name: mtu
        label: MTU
        kind: Number
        default_value: 1500
      - name: enabled
        kind: Boolean
        default_value: false
      - name: untagged_vlan
        label: Untagged VLAN
        kind: Number
        optional: true
      - name: mode
        kind: Dropdown
        default_value: access
        choices:
          - name: access
            label: Access
          - name: trunk
            label: Trunk
      - name: status
        kind: Dropdown
        optional: true
        choices:
          - name: active
            label: Active
            description: "Fully operational and currently in service"
            color: "#7fbf7f"
          - name: provisioning
            label: Provisioning
            description: "In the process of being set up and configured"
            color: "#ffff7f"
          - name: maintenance
            label: Maintenance
            description: "Undergoing routine maintenance or repairs"
            color: "#ffd27f"
          - name: drained
            label: Drained
            description: "Temporarily taken out of service"
            color: "#bfbfbf"
      - name: role
        kind: Dropdown
        optional: true
        choices:
          - name: uplink
            label: Uplink
            description: "Interface connected to other network device"
            color: "#9090de"
          - name: end_user
            label: End user
            description: "Interface to connect end-user devices"
            color: "#ffa07a"
          - name: server
            label: Server
            description: "Interfaces to connect to servers"
            color: "#98b2d1"
```
- in the UI navigate to the schema page
- open the ProfileInterface, hfid will is set to `null`
