### ISSUE TITLE
bug: cannot view resource pool details in front end when it references resources of a kind that is not defined in the main branch

### ISSUE THREAD

**Issue by wvandeun** [opsmill/infrahub#4761]
### Component

Frontend UI

### Infrahub version

1.0.0.dev.0

### Current Behavior

When you open the resource pool detailed page for a resource pool that contains resources, for which the kind of the resource is not yet defined in the main branch, then opening the detailed page will fail with an error message:
![image](https://github.com/user-attachments/assets/a7a76cf9-76b5-4446-a5f5-4f10725db05d)

### Expected Behavior

We can open the resource pool detailed view

### Steps to Reproduce

- load an instance of infrahub
- create a branch
- load the following schema in the branch
```yaml
---
version: "1.0"
nodes:
  - name: IPPrefix
    namespace: Ipam
    include_in_menu: false
    inherit_from:
      - "BuiltinIPPrefix"
    description: "IPv4 or IPv6 network"
    label: "IP Prefix"
  - name: IPAddress
    namespace: Ipam
    include_in_menu: false
    inherit_from:
      - "BuiltinIPAddress"
    description: "IP Address"
    label: "IP Address"
  - name: Device
    namespace: Infra
    description: "A Device"
    icon: "mdi:server"
    label: "Device"
    attributes:
      - name: name
        kind: Text
        label: Name
        optional: false
    relationships:
      - name: primary_ip
        label: "Primary IP Address"
        peer: IpamIPAddress
        optional: false
        kind: Attribute
        cardinality: one
```
- in the branch, create a new IpamIPPrefix
- in the branch, create a new CoreIPAddressPool, referencing the IP prefix as resource
- in the UI, in the branch navigate to CoreIPAddressPool list view
- open the newly create pool
