### ISSUE TITLE
bug: cannot delete a parent node when it inherits a component relationship from a generic

### ISSUE THREAD

**Issue by wvandeun** [opsmill/infrahub#4780]
### Component

API Server / GraphQL

### Infrahub version

1.0.0.dev.0

### Current Behavior

If you have a schemanode that inherits from a generic that defines a relationship of kind "Component". Then you will be unable to delete the parent node.
You are unable to delete the parent node because it seems that the cascading delete of related nodes doesn't seem to properly work in this case. Hence we violate the requirement of the parent relationship in the other direction.

### Expected Behavior

You are able to delete nodes, that inherit component relationships from a generic

### Steps to Reproduce

- load instance of Infrahub
- load this schema
```yaml
---
version: "1.0"
generics:
  - name: InterfaceHolder
    namespace: Infra
    relationships:
      - name: interfaces
        kind: Component
        cardinality: many
        optional: true
        peer: InfraInterface
nodes:
  - name: Device
    namespace: Infra
    inherit_from:
      - InfraInterfaceHolder
    attributes:
      - name: name
        kind: Text
        optional: false
        unique: true
  - name: Interface
    namespace: Infra
    attributes:
      - name: name
        kind: Text
        unique: true
        optional: false
    relationships:
      - name: device
        kind: Parent
        peer: InfraDevice
        optional: false
        cardinality: one
```
- create a device node
- create an interface node, set device to the previously created device node
- try to remove the device node
