### ISSUE TITLE
bug: Error during a menu load when `Parent` referenced a Kind instead of a 

### ISSUE THREAD

**Issue by BeArchiTek** [opsmill/infrahub#4826]
### Infrahub version

1.0.0

### Current Behavior

When attempting to add VLANs to the IPAM using the BuiltinIPAM menu item in infrahubctl, the following error appears:

```console
['CoreMenuItemUpsert'] Unable to find the node BuiltinIPAM / CoreMenu in the database.
```

This occurs when setting BuiltinIPAM as the parent in the menu YAML file, as shown below:

```yaml
---
apiVersion: infrahub.app/v1
kind: Menu
spec:
  data:
    # Adding VLANs to IPAM
    - name: VLAN
      namespace: Infra
      label: VLANs
      icon: "mdi:lan-pending"
      kind: InfraVLAN
      parent: BuiltinIPAM
```
However, using a different structure for `parent` as an array, like ["Builtin", "IPAM"], appears to work without errors:

```yaml
    # Adding VLANs to IPAM
    - name: VLAN
      namespace: Infra
      label: VLANs
      icon: "mdi:lan-pending"
      kind: InfraVLAN
      parent: ["Builtin", "IPAM"]
```

### Expected Behavior

According to the documentation, the parent field should accept a string in the format of concatenated namespace + name, meaning BuiltinIPAM should work as the value without requiring an array format. The parent field should recognize BuiltinIPAM directly, aligning with the documented behavior.

Documentation Reference: https://docs.infrahub.app/reference/menu

> parent string: a parent menu item (concatenated namespace + name)

### Steps to Reproduce

1. Create a YAML file (file.yml) with the menu configuration:

```yaml
apiVersion: infrahub.app/v1
kind: Menu
spec:
  data:
    - name: VLAN
      namespace: Infra
      label: VLANs
      icon: "mdi:lan-pending"
      kind: InfraVLAN
      parent: BuiltinIPAM
```

2. Attempt to load the menu using:

```shell
infrahubctl menu load file.yml
```
3. Observe the error:

```console
['CoreMenuItemUpsert'] Unable to find the node BuiltinIPAM / CoreMenu in the database.
```
4. Update the parent field to use the array format:

```yaml
      parent: ["Builtin", "IPAM"]
```
5. Reload the menu and note that it works without errors.
