### ISSUE TITLE
bug: schema out of sync on workers after deleting a node from the schema 

### ISSUE THREAD

**Issue by wvandeun** [opsmill/infrahub#4836]
### Component

API Server / GraphQL

### Infrahub version

1.0.1

### Current Behavior

The schema between different workers goes out of sync, when you delete an existing schema node from the schema.

### Expected Behavior

All the workers load the new schema and the schema is in sync between them.

### Steps to Reproduce

- load an instance of `infrahub`
- load this schema
```yaml
---
version: "1.0"
nodes:
  - name: Device
    namespace: Network
    human_friendly_id: ['hostname__value']
    attributes:
      - name: hostname
        kind: Text
        unique: true
      - name: model
        kind: Text
  - name: Interface
    namespace: Network
    attributes:
      - name: name
        kind: Text
      - name: description
        kind: Text
        optional: true
```
- execute this GraphQL query, the schema has should be in sync, take note of the hash of one of the nodes
```graphql
query {
  InfrahubStatus {
    summary {
      schema_hash_synced
    }
    workers {
      edges {
        node {
          schema_hash
        }
      }
    }
  }  
}
```
- load this schema, the NetworkInterface should be deleted from the schema
```yaml
---
version: "1.0"
nodes:
  - name: Device
    namespace: Network
    human_friendly_id: ['hostname__value']
    attributes:
      - name: hostname
        kind: Text
        unique: true
      - name: model
        kind: Text
  - name: Interface
    namespace: Network
    state: absent
    attributes:
      - name: name
        kind: Text
      - name: description
        kind: Text
        optional: true
```
- execute the following Graphql query
```graphql
```graphql
query {
  InfrahubStatus {
    summary {
      schema_hash_synced
    }
    workers {
      edges {
        node {
          schema_hash
        }
      }
    }
  }  
}
```
The workers are now not in sync anymore. Only 1 worker will have a new schema hash, the other workers still have the old hash from the previous step.
