### ISSUE TITLE
bug: API server returns confusing error message when loading a schema that has a generic defined with the same name of an existing node

### ISSUE THREAD

**Issue by wvandeun** [opsmill/infrahub#4837]
### Component

API Server / GraphQL

### Infrahub version

1.0.1

### Current Behavior

When you load a schema that defines a generic with a name that already exists in the current schema of Infrahub as a node, you get an error message returned by the API server:
```json
{
    "data": null,
    "errors": [
        {
            "extensions": {
                "code": 422
            },
            "message": "\"NodeSchema\" object has no field \"hierarchical\""
        }
    ]
}
```

### Expected Behavior

The error message should clearly describe what is wrong with the schema that we are trying to load. In this case it should mention that the generic `NetworkInterface` already exists as a node in the schema.

### Steps to Reproduce

- load instance of Infrahub
- load this schema
```yaml
---
version: "1.0"
nodes:
  - name: Device
    namespace: Network
    human_friendly_id: ['hostname__value']
    attributes:
      - name: hostname
        kind: Text
        unique: true
      - name: model
        kind: Text
  - name: Interface
    namespace: Network
    attributes:
      - name: name
        kind: Text
      - name: description
        kind: Text
        optional: true
```
- next, load this schema
```yaml
---
version: "1.0"
generics:
  - name: Interface
    namespace: Network
    attributes:
      - name: name
        kind: Text
      - name: description
        kind: Text
        optional: true
    relationships:
      - name: device
        cardinality: one
        peer: NetworkDevice
        kind: Parent
        optional: false
nodes:
  - name: Device
    namespace: Network
    human_friendly_id: ['hostname__value']
    attributes:
      - name: hostname
        kind: Text
        unique: true
      - name: model
        kind: Text
    relationships:
      - name: interfaces
        cardinality: many
        peer: NetworkInterface
        kind: Component
  - name: PhysicalInterface
    namespace: Network
    inherit_from:
      - NetworkInterface
    attributes:
      - name: speed
        kind: Number
  - name: LogicalInterface
    namespace: Network
    inherit_from:
      - NetworkInterface
```
