### ISSUE TITLE
bug: when inserting a schema node into an existing hierarchy the wrong `peer` gets defined on the parent relationship on the inserted node 

### ISSUE THREAD

**Issue by wvandeun** [opsmill/infrahub#4838]
### Component

API Server / GraphQL

### Infrahub version

1.0.1

### Current Behavior

When you insert a schema node into an existing hierarchy, the parent relationship on the inserted schema node seems to be set to the generic implementing the hierarchy rather than the specific peer.

### Expected Behavior

The peer of the parent relationship of the inserted node in the hierarchy, gets set to the proper kind of the parent node.

### Steps to Reproduce

- load an instance of Infrahub
- load the following schema
```yaml
---
version: "1.0"
generics:
  - name: Generic
    namespace: Location
    hierarchical: true
    attributes:
      - name: name
        kind: Text
        optional: false
        unique: true
nodes:
  - namespace: Location
    name: Country
    inherit_from:
      - LocationGeneric
    parent: ""
    children: "LocationSite"
  - namespace: Location
    name: Site
    inherit_from:
      - LocationGeneric
    parent: "LocationCountry"
    children: ""
```
- next load the following schema
```yaml
---
version: "1.0"
generics:
  - name: Generic
    namespace: Location
    hierarchical: true
    attributes:
      - name: name
        kind: Text
        optional: false
        unique: true
nodes:
  - namespace: Location
    name: Country
    inherit_from:
      - LocationGeneric
    parent: ""
    children: "LocationMetro"
  - namespace: Location
    name: Metro
    inherit_from:
      - LocationGeneric
    parent: "LocationCountry"
    children: "LocationSite"
  - namespace: Location
    name: Site
    inherit_from:
      - LocationGeneric
    parent: "LocationMetro"
    children: ""
```
- navigate to the schema page in the UI
- open the LocatioMetro schema node
- open the relationships tab
- expand the parent relationship
- the peer will be set to `LocationGeneric` instead of `LocationCountry`
