### ISSUE TITLE
bug: when inserting a schema node into an existing hierarchy the `peer` of the parent relationship of the new node's child does not get updated

### ISSUE THREAD

**Issue by wvandeun** [opsmill/infrahub#4839]
### Component

API Server / GraphQL

### Infrahub version

1.0.1

### Current Behavior

When you insert a new schema node into an existing hierarchy, the parent relationship `peer` property of the node that points to the newly inserted schema node will not have been updated. 

### Expected Behavior

The peer property of the parent relationship points to the new parent, which is the newly inserted node in the hierarchy.

### Steps to Reproduce

- load an instance of Infrahub
- load the following schema
```yaml
---
version: "1.0"
generics:
  - name: Generic
    namespace: Location
    hierarchical: true
    attributes:
      - name: name
        kind: Text
        optional: false
        unique: true
nodes:
  - namespace: Location
    name: Country
    inherit_from:
      - LocationGeneric
    parent: ""
    children: "LocationSite"
  - namespace: Location
    name: Site
    inherit_from:
      - LocationGeneric
    parent: "LocationCountry"
    children: ""
```
- next load the following schema
```yaml
---
version: "1.0"
generics:
  - name: Generic
    namespace: Location
    hierarchical: true
    attributes:
      - name: name
        kind: Text
        optional: false
        unique: true
nodes:
  - namespace: Location
    name: Country
    inherit_from:
      - LocationGeneric
    parent: ""
    children: "LocationMetro"
  - namespace: Location
    name: Metro
    inherit_from:
      - LocationGeneric
    parent: "LocationCountry"
    children: "LocationSite"
  - namespace: Location
    name: Site
    inherit_from:
      - LocationGeneric
    parent: "LocationMetro"
    children: ""
```
- in the UI navigate to schema
- open the `LocationSite` schema node
- go to relationships tab
- expand the parent relation
- the `peer` of the relationship is still set to `LocationCountry`
