### ISSUE TITLE
bug: Overriding `Optional` between Generic and Node crash server

### ISSUE THREAD

**Issue by BeArchiTek** [opsmill/infrahub#4936]
### Component

API Server / GraphQL

### Infrahub version

1.0.4

### Current Behavior

When loading a schema and having the same attribute in both the Generic and the node inheriting from it, it's possible to load the schema, *BUT* if the `optional` data of the attribute changes, the server will loop on the TypeError.

### Expected Behavior

Schema should be refuse if the `inherited: true` is not present

### Steps to Reproduce

1. Start infrahub `1.0.4` and load this schema :
```yaml
# yaml-language-server: $schema=https://schema.infrahub.app/infrahub/schema/latest.json
---
version: '1.0'

generics:
  - name: Sandwich
    namespace: Meal
    attributes:
      - name: description
        kind: Text
        optional: false

nodes:
  - name: Grilled
    namespace: Sandwich
    inherit_from:
      - MealSandwich
    attributes:
      - name: description
        kind: Text
        optional: true

```
2. Check the log of the server, you should see
```console
2024-11-14 14:56:04 TypeError: Interface field MealSandwich.description expects type TextAttribute! but 
2024-11-14 14:56:04 SandwichGrilled.description is type TextAttribute.
```
