### ISSUE TITLE
feature: Be able to click on a `URL` kind Attribute

### ISSUE THREAD

**Issue by BeArchiTek** [opsmill/infrahub#5005]
### Component

Frontend UI

### Describe the Feature Request

An attribute can be of the Kind `URL`, as a user I would expect this to be "clickable" and be use in a similar way as Netbox custom link.

### Describe the Use Case

With the computed attribute I could create a custom link depending on the node. I would then use this URL attribute to click on the link

### Additional Information

Example of schema
```
# yaml-language-server: $schema=https://schema.infrahub.app/infrahub/schema/latest.json
---
version: '1.0'

nodes:
  - name: Template
    namespace: Random
    attributes:
      - name: custom_link
        kind: URL
        optional: true

```
