### ISSUE TITLE
bug: Resource Manager `allocate_next_*`  Error message is not explicit

### ISSUE THREAD

**Issue by BeArchiTek** [opsmill/infrahub#5006]
### Component

API Server / GraphQL

### Infrahub version

1.0.5 and 1.0.6

### Current Behavior

When creating a node (IP Address or IP Prefix) using a  Resource Pool, if some of the mandatory attributes are not given with the `allocate_next_ip_prefix` or `allocate_next_ip_address` we get a generic 
> "['IPPrefixPoolGetResource'] An unknown error occurred."

### Expected Behavior

We should be able to indicate which attribute is missing 

### Steps to Reproduce

1. Load this schema into infrahub
```yaml
# yaml-language-server: $schema=https://schema.infrahub.app/infrahub/schema/latest.json
---
version: '1.0'
nodes:
  # --------------------  IPAM (VLAN, IP Address)  --------------------
  - name: Prefix
    namespace: Ipam
    description: "IPv4 or IPv6 network (with mask)"
    icon: "mdi:ip-network"
    include_in_menu: false
    label: "Prefix"
    default_filter: prefix__value
    order_by:
      - prefix__value
    display_labels:
      - prefix__value
    inherit_from:
      - BuiltinIPPrefix
    uniqueness_constraints:
      - ["ip_namespace", "prefix__value"]
    human_friendly_id: ["prefix__value", "ip_namespace__name__value"]
    attributes:
      - name: status
        kind: Dropdown
        choices:
          - name: active
            label: Active
          - name: deprecated
            label: Deprecated
          - name: reserved
            label: Reserved
```
2. Create a Prefix and a Resource Pool `mgmt_pool` with a prefix
```
from infrahub_sdk import InfrahubClient, Config

client = InfrahubClient(address="http://localhost:8000", config=Config(api_token="06438eb2-8019-4776-878c-0941b1f1d1ec",timeout=30,default_branch="main"),)

prefix = await client.create(kind="IpamPrefix", prefix="10.0.0.0/8", status="reserved")
await prefix.save()
mgmt_pool = await client.create(kind="CoreIPPrefixPool", name="mgmt_pool2", resources=[prefix], ip_namespace="default", default_member_type="IpamPrefix", default_prefix_length=32)
await mgmt_pool.save()

```

3. Try allocating a new prefix from the pool
```python
from infrahub_sdk import InfrahubClient, Config

client = InfrahubClient(address="http://localhost:8000", config=Config(api_token="06438eb2-8019-4776-878c-0941b1f1d1ec",timeout=30,default_branch="main"),)

mgmt_pool = await client.get(kind="CoreIPPrefixPool", name__value="mgmt_pool2", raise_when_missing=True)
mgmt_net = await client.allocate_next_ip_prefix(
             resource_pool=mgmt_pool,
             kind="InfraPrefix",
             branch="main",
             identifier=f"mgmt-test",
             )
```
