### ISSUE TITLE
bug: Error when querying an attribute after changing the `Kind` of it

### ISSUE THREAD

**Issue by BeArchiTek** [opsmill/infrahub#5059]
### Infrahub version

1.0.7

### Current Behavior

After changing an attribute from`Number`  to `Text` in a schema,  the system encounters errors when attempting to query either the attribute or the HFID (if the attribute is part of it) It happened with both the UI and GraphQL API.

UI Error: "Something went wrong when fetching list."
GraphQL API Error: "An unknown error occurred."

### Expected Behavior

Either this update is not authorized and we should get an error when changing the schema, or it should not break later on.

### Steps to Reproduce

1. Load the schema below
```yaml
# yaml-language-server: $schema=https://schema.infrahub.app/infrahub/schema/latest.json
---
version: "1.0"

nodes:
  - name: Person
    namespace: Random
    include_in_menu: true
    uniqueness_constraints:
      - ["name__value"]
      - ["tax_number__value"]
    human_friendly_id:
      - name__value
      - tax_number__value
    display_labels:
      - name__value
    order_by:
      - name__value
    attributes:
      - name: name
        kind: Text
        optional: false
      - name: tax_number
        kind: Number
        optional: false
```

2. Create a person in the UI

3. Change the **tax_number** kind from `Number` to`Text` and reload the schema.

4. Query the tax_number field or the HFID in:
- The UI
- The GraphQL API

### Additional Information

The issue is present only where there is some data into the attribute changed, my guess is that we do not convert the data when updating the Kind.
