### ISSUE TITLE
bug: Unexpected Application Error when filtering list view on list attribute

### ISSUE THREAD

**Issue by wvandeun** [opsmill/infrahub#5090]
# 
## 
### Component

Frontend UI

# 
## 
### Infrahub version

1.0.7

# 
## 
### Current Behavior

When you try to filter the list view of a node on an attribute of kind list, you get the following error message:

<img width="835" alt="image" src="[https://github.com/user-attachments/assets/c5e1931f-1b30-4cdb-bc57-ca8baf2fceb1|https://github.com/user-attachments/assets/c5e1931f-1b30-4cdb-bc57-ca8baf2fceb1]">

# 
## 
### Expected Behavior

Filtering on the list attribute gets properly applied.

# 
## 
### Steps to Reproduce

* spin up instance of Infrahub
* load this schema
```yaml
—
version: "1.0"
nodes:
* name: Device
    namespace: Testing
    attributes:
* name: hostname
        kind: Text
        optional: false
* name: components
        kind: List
        optional: true
```
* create a new TestDevice node, and add a components list item
* in the TestDevice list view, click on filter icon
* set a filter on the components attribute
* click Apply Filters

# 
##
