### ISSUE TITLE
bug: GraphQL filter for an attribute of kind List doesn't work

### ISSUE THREAD

**Issue by wvandeun** [opsmill/infrahub#5091]
### Component

API Server / GraphQL

### Infrahub version

1.0.7

### Current Behavior

You are unable to use a filter in a GraphQL query for an attribute of kind List. 
```yaml
---
version: "1.0"
nodes:
  - name: Device
    namespace: Testing
    attributes:
      - name: hostname
        kind: Text
        optional: false
      - name: components
        kind: List
        optional: true
```
Tested with the following filters, they all return an empty result.
```graphql
query {
  TestingDevice(components__values: ["abc"]) {
    edges {
      node {
        name {
          value
        }
        components {
          value
        }
      }
    }
  }
}

query {
  TestingDevice(components__value: "abc") {
    edges {
      node {
        name {
          value
        }
        components {
          value
        }
      }
    }
  }
}

query {
  TestingDevice(components__value: ["abc"]) {
    edges {
      node {
        name {
          value
        }
        components {
          value
        }
      }
    }
  }
}
```
Per the suggestion of @dgarros , using a partial match does seem to work, however this is only a partial solution.
```graphql
query {
  TestingDevice(components__value: "one", partial_match: true) {
    edges {
      node {
        id
	    hostname {
          value
        }
      }
    }
  }
}
```

### Expected Behavior

Filters for attributes of kind list should work as expected.

### Steps to Reproduce

- load instance of Infrahub
- load this schema
```yaml
---
version: "1.0"
nodes:
  - name: Device
    namespace: Testing
    attributes:
      - name: hostname
        kind: Text
        optional: false
      - name: components
        kind: List
        optional: true
```
- create a TestingDevice node and provide a string value "abc" for the components list
- execute one of the above GraphQL queries, they will return 0 results
