### ISSUE TITLE
bug: schema out of sync between workers when creating a new branch

### ISSUE THREAD

**Issue by wvandeun** [opsmill/infrahub#5130]
# 
## 
### Component

API Server / GraphQL

# 
## 
### Infrahub version

stable

# 
## 
### Current Behavior

When you create a new branch, and in that branch query for the schema_has_synced status you will see that the status is false. One of the workers reports a `null` value for the schema_hash.

# 
## 
### Expected Behavior

The schema is in sync between the different workers after a branch has been created.

# 
## 
### Steps to Reproduce

* load instance of Infrahub
* load a schema
```yaml
—
version: "1.0"
nodes:
* name: Device
    namespace: Infra
    attributes:
* name: hostname
        kind: Text
        optional: false
* name: flash_size
        kind: Text
        optional: false
```
* create a branch `infrahubctl branch create test`
* in the branch execute the following GraphQL query
```graphql
query {
  InfrahubStatus {
    summary {
      schema_hash_synced
    }
    workers {
      edges {
        node {
          id
          schema_hash
        }
      }
    }
  }
}
```

# 
## 
### Additional Information

* the issue does not seem to occur on 1.0.7
* schema hash is in sync between the different workers for the main branch
* restarting the workers seems to be solving the issue
* loading a new schema in the branch seems to solve the issue
