### ISSUE TITLE
bug: attribute kind of a node in a branch is not changed when the attribute kind was changed in main and you rebased the branch

### ISSUE THREAD

**Issue by wvandeun** [opsmill/infrahub#5131]
### Component

API Server / GraphQL

### Infrahub version

1.0.7 and stable

### Current Behavior

You make a change to an attribute kind in the main branch. You have an older branch (pre attribute kind change in main), in which you want to get the same change, so you rebase the branch. After rebasing the change will not be relfected in the branch.

### Expected Behavior

The attribute kind would have changed after rebasing the brach

### Steps to Reproduce

* load an instance of Infrahub
* load this schema
```yaml
—
version: "1.0"
nodes:
* name: Device
    namespace: Infra
    attributes:
* name: hostname
        kind: Text
        optional: false
* name: flash_size
        kind: Text
        optional: false
```
* create a branch named test
* in main load this schema (attribute kind for flash_size changes to Number)
```yaml
—
version: "1.0"
nodes:
* name: Device
    namespace: Infra
    attributes:
* name: hostname
        kind: Text
        optional: false
* name: flash_size
        kind: Number
        optional: false
```
* rebase the test branch
* execute the following curl commands:
```bash
curl [http://localhost:8000/api/schema/InfraDevice?branch=test|http://localhost:8000/api/schema/InfraDevice?branch=test] | jq '.attributes[] | select(.name=="flash_size") | .kind'
curl [http://localhost:8000/api/schema/InfraDevice?branch=main|http://localhost:8000/api/schema/InfraDevice?branch=main] | jq '.attributes[] | select(.name=="flash_size") | .kind'
```
* you will notice that test still reports the attribute kind to be Text, main will report a Number attribute kind
* open a proposed change for the test branch
* no schema diff will have been detected
