### ISSUE TITLE
bug: you can load a schema with a node that contains a number attribute that has a boolean `default_value`

### ISSUE THREAD

**Issue by wvandeun** [opsmill/infrahub#5221]
### Component

API Server / GraphQL

### Infrahub version

1.0.8

### Current Behavior

Infrahub allows you to load a schema that defines a schemanode with an attribute of kind Number, that has a boolean `default_value`.

You can then create such a node , without specifying a value for the number attribute. The value of  the attribute will then be 0 when the default_value was set to False, or 1 if the default_value was set to True.

When you create such  a node (leveraging the default value for the attribute) in branch, then you will not be able to merge the branch and get an error message:
```
could not convert string to float: 'False'
``` 

### Expected Behavior

Infrahub should not accept a schema with an attribute of kind Number and a boolean `default_value`

### Steps to Reproduce

- load an instance of Infrahub
- load this schema
```yaml
---
version: "1.0"
nodes:
  - name: Node
    namespace: Testing
    attributes:
      - name: number
        kind: Number
        default_value: true
        optional: false
```
- create a new branch
- create a new TestingNode in the newly created branch, without providing a value for the number attribute
```graphql
mutation {
  TestingNodeCreate(data: {}) {
    object {number { value }}
  }
}
```
- query for the node, notice the value of the number attribute
```graphql
query {
  TestingNode {
    edges {
      node {
        number {
          value
        }
      }
    }
  }
}
```
- try merging the branch
