### ISSUE TITLE
bug: JSON attributes not properly populated using profiles

### ISSUE THREAD

**Issue by BaptisteGi** [opsmill/infrahub#5276]
### Component

Frontend UI

### Infrahub version

1.0.9

### Current Behavior

I have a node that has a JSON kind of attribute. I created a profile attached to it that contains a value for my JSON attribute. When I create an instance of my node the JSON field remains empty + I don't have the small component that tells the value comes from a profile. Apparently it's a frontend issue because after saving the value is indeed populated.

### Expected Behavior

I expect to have the same experience as regular Text attribute (value populated + small frontend component)

<img width="953" alt="image" src="https://github.com/user-attachments/assets/775a8d91-3c2b-4600-aa20-4e3b429c4260" />

### Steps to Reproduce

- invoke demo.start
- Load this schema

```yaml
---
# yaml-language-server: $schema=https://schema.infrahub.app/infrahub/schema/latest.json

version: "1.0"

nodes:
  - name: Profile
    namespace: Broken
    include_in_menu: true
    attributes:
      - name: name
        kind: Text
        unique: true
        order_weight: 900
      - name: some_json
        kind: JSON
        optional: true
        order_weight: 1000
      - name: some_text
        kind: Text
        optional: true
        order_weight: 1000
```

- Create a profile with a JSON value
- Try to create an instance of "BrokenProfile" node

### Additional Information

Maybe other attribute kinds are impacted as well
