### ISSUE TITLE
bug: Profile doesn't want me to update values for new attributes

### ISSUE THREAD

**Issue by BaptisteGi** [opsmill/infrahub#5277]
### Component

API Server / GraphQL

### Infrahub version

1.0.9

### Current Behavior

I create a node using a schema. I then create a profile for that particular node. Then I add a new attribute to my node and so edit the corresponding profile to get this new attribute populated as well. Here Infahub accepts my new value (I have the green popup and so on) but doesn't save it (field remains empty in my profile ...)

### Expected Behavior

Either my value isn't correct and I have a red popup explaining why or it's valid and it gets saved.

### Steps to Reproduce

- invoke demo.start
- load schema

```yaml
---
# yaml-language-server: $schema=https://schema.infrahub.app/infrahub/schema/latest.json

version: "1.0"

nodes:
  - name: Itis
    namespace: Broken
    include_in_menu: true
    attributes:
      - name: name
        kind: Text
        unique: true
        order_weight: 900
      - name: some_number
        kind: Number
        optional: true
        order_weight: 1000
```

- create a profile for this node
- load this schema

```yaml
---
# yaml-language-server: $schema=https://schema.infrahub.app/infrahub/schema/latest.json

version: "1.0"

nodes:
  - name: Itis
    namespace: Broken
    include_in_menu: true
    attributes:
      - name: name
        kind: Text
        unique: true
        order_weight: 900
      - name: some_number
        kind: Number
        optional: true
        order_weight: 1000
      - name: some_text
        kind: Text
        optional: true
        order_weight: 1000
```

- edit the profile created previously to put a value inside "some_text"
- hit save
- from the detailed profile view the "some_text" is empty
