### ISSUE TITLE
feature: support nested GraphQL fragments for queries on schemanodes that inherit from a generic

### ISSUE THREAD

**Issue by wvandeun** [opsmill/infrahub#5322]
### Component

API Server / GraphQL

### Describe the Feature Request

This feature would allow us to use GraphQL fragments in a nested way on queries for Infrahub schemanodes that inherit from a generic.

### Describe the Use Case

We would like to use nested GraphQL fragments for queries on schemanodes that inherit form Infrahub generics. This allows to keep the query relatively simple to write and allows us not to repeat ourselves.

### Additional Information

An example scenario where this currently doesn't work
Schema
```yaml
---
version: "1.0"
generics:
  - name: Generic
    namespace: Location
    hierarchical: true
    attributes:
      - name: name
        optional: false
        kind: Text
    relationships:
      - name: devices
        peer: InfraDevice
        cardinality: many
        optional: true
      - name: tag
        peer: BuiltinTag
        cardinality: one
        direction: outbound
        optional: false
nodes:
  - name: Device
    namespace: Infra
    attributes:
      - name: name
        kind: Text
        optional: false
    relationships:
      - name: location
        peer: LocationGeneric
        optional: false
        cardinality: one
  - name: Site
    namespace: Location
    inherit_from:
      - LocationGeneric
    attributes:
      - name: description
        optional: false
        kind: Text
```

Create some data
```python
from infrahub_sdk import InfrahubClientSync

client = InfrahubClientSync()
tag = client.create("BuiltinTag", name="My Tag")
tag.save()
site1 = client.create("LocationSite", name="site1", description="test", tag=tag)
site1.save()

device1 = client.create("InfraDevice", name="device1", location=site1)
device1.save()
device2 = client.create("InfraDevice", name="device2", location=site1)
device2.save()

```

Execute the following GraphQL query
```graphql
fragment DeviceData on InfraDevice {
  name {
    value
  }
}

fragment LocationData on LocationSite {
  name {
    value
  }
  devices {
    edges {
      node {
        ...DeviceData
      }
    }
  }
}

query {
  LocationSite {
    edges {
      node {
        ...LocationData
      }
    }
  }
}
```
You will see that the devices relation is empty.
