### ISSUE TITLE
bug: unable to remove a relationship to a generic from a schema extension when the generic is removed simulteanously

### ISSUE THREAD

**Issue by wvandeun** [opsmill/infrahub#5384]
### Component

API Server / GraphQL

### Infrahub version

1.1.1

### Current Behavior

When you try to delete a relationship from a schema extension, that references a generic that also gets removed during the same schema load, then the API server returns a HTTP404 status message without a proper error.
No additional logs seem to have been generated.

### Expected Behavior

The generic is removed together with the relationship defined in the schema extension.

### Steps to Reproduce

- spin up instance of Infrahub
- load these 2 schema files
```yaml
---
version: "1.0"
nodes:
  - name: SomeNode
    namespace: Testing
    attributes:
      - name: name
        kind: Text
        optional: false
        unique: true
```
```yaml
---
version: "1.0"
generics:
  - name: OtherNode
    namespace: Testing
    attributes:
      - name: name
        kind: Text
        optional: false
        unique: true
extensions:
  nodes:
    - kind: TestingSomeNode
      relationships:
        - name: other_nodes
          peer: TestingOtherNode
          optional: false
          cardinality: many
          kind: Attribute
```
- then load the following schema file, removing the generic + the relationship defined on the extension
```yaml
version: "1.0"
generics:
  - name: OtherNode
    namespace: Testing
    state: absent
    attributes:
      - name: name
        kind: Text
        optional: false
        unique: true
extensions:
  nodes:
    - kind: TestingSomeNode
      relationships:
        - name: other_nodes
          peer: TestingOtherNode
          state: absent
          optional: false
          cardinality: many
          kind: Attribute
```
