### ISSUE TITLE
bug: unable to remove a generic from the schema

### ISSUE THREAD

**Issue by wvandeun** [opsmill/infrahub#5388]
### Component

API Server / GraphQL

### Infrahub version

1.1.1

### Current Behavior

You get a HTTP 404 response when you try to delete a generic from the schema

### Expected Behavior

The generic is removed from the schema

### Steps to Reproduce

- start instance of Infrahub
- load the following schema file
```yaml
---
version: "1.0"
generics:
  - name: SomeNode
    namespace: Testing
    attributes:
      - name: name
        kind: Text
        optional: false
        unique: true
```
- then load this schema file, removing the generic
```yaml
---
version: "1.0"
generics:
  - name: SomeNode
    namespace: Testing
    state: absent
    attributes:
      - name: name
        kind: Text
        optional: false
        unique: true
```

### Additional Information

Not sure about the overlap with #5384
In fact this could be the same issue that we are experiencing
