### ISSUE TITLE
bug: UI - Using a parent of parent filter makes the filter field required, but fails due to "required"

### ISSUE THREAD

**Issue by FragmentedPacket** [opsmill/infrahub#5418]
### Component

Frontend UI

### Infrahub version

1.1.1

### Current Behavior

When attempting to create a node with a parent relationship, which that relationship also has a parent relationship defined, we cannot create the node due to the filter being "required" in the UI.

<img width="395" alt="image" src="https://github.com/user-attachments/assets/ee922c41-71a9-4581-80a6-2726d3ade863" />

This issue does not occur if creating via the SDK.

### Expected Behavior

Ability to save the networkpod while being able to filter the parent (hall) of the fabric.

### Steps to Reproduce

1. Load the following schema.
```yaml
---
version: "1.0"
generics:
  - name: Pod
    namespace: Infra
    attributes:
      - name: name
        kind: Text
        optional: false
        unique: true
    relationships:
      - name: fabric
        peer: InfraFabric
        cardinality: one
        optional: false
        kind: Parent
  - name: Fabric
    namespace: Infra
    attributes:
      - name: name
        kind: Text
        optional: false
        unique: true
    relationships:
      - name: hall
        peer: InfraHall
        kind: Parent
        cardinality: one
        optional: false
      - name: pod
        peer: InfraPod
        cardinality: many
        optional: true
        kind: Generic
nodes:
  - name: NetworkPod
    namespace: Infra
    inherit_from:
      - InfraPod
  - name: Hall
    namespace: Infra
    attributes:
      - name: name
        kind: Text
        optional: false
        unique: true
    relationships:
      - name: fabrics
        peer: InfraFabric
        cardinality: many
        kind: Component
  - name: NetworkFabric
    namespace: Infra
    inherit_from:
      - InfraFabric
```
2. Create a data hall
3. Create a Networkfabric
4. Attempt to create a networkpod in a fabric and observe the error

To workaround this issue, you can change the `kind` of the relationship on `InfraFabric.hall` to `kind: Generic`, we can save the pod, but no longer can use the filtering.
