### ISSUE TITLE
task: Align query to action binding

### ISSUE THREAD

**Issue by BaptisteGi** [opsmill/infrahub#5483]
### Component

Git Integration

### Task Description

When I link a query to a generator I have the following code in `.infrahub.ynl`:

```yaml
generator_definitions:
  - name: fabric_generator
    query: fabric_info
...
```

For transform->query it's different, it happens in the python file itself:

```python
class StartupConfigTransform(InfrahubTransform):
    query = "device_info"
    url = "startup-config"

    async def transform(self, data):
...
```

Would be great to align this so we have a predictable developer experience. Maybe other action types than transform have the same behavior.
