### ISSUE TITLE
bug: Show computed attribute in Schema Visualizer in UI

### ISSUE THREAD

**Issue by FragmentedPacket** [opsmill/infrahub#5515]
### Component

Frontend UI

### Infrahub version

1.1.4

### Current Behavior

When viewing the schema visualizer in the UI a node that has a computed attribute does not have any indication it is a computed attribute other than `read-only` badge.
<img width="1339" alt="Image" src="https://github.com/user-attachments/assets/923d86f4-97ce-45d5-bb96-ad019269f7a0" />

### Expected Behavior

It should display the computed_attribute details of the schema node and potentially add a `computed attribute` badge on the attribute.

### Steps to Reproduce

1. Load fresh Infrahub instance
2. Load the following schema:
```yaml
---
version: "1.0"
nodes:
  - name: "Rack"
    namespace: "Test"
    attributes:
      - name: "name"
        kind: "Text"
        unique: true
      - name: "facility_id"
        kind: "Text"
        optional: true
        read_only: true
        computed_attribute:
          kind: Jinja2
          jinja2_template: "{{ name__value | upper }}"
```
3. View the schema visualizer and see no indications of the `computed_attribute` in the view for the `TestRack.facility_id` attribute.
