### ISSUE TITLE
bug: The frontend allows users to edit metadata of read_only attributes in some forms

### ISSUE THREAD

**Issue by wvandeun** [opsmill/infrahub#5558]
### Component

API Server / GraphQL

### Infrahub version

1.1.4

### Current Behavior

When you try changing the meta data of a computed attribute, you get an error message:

```
"Field '<attribute name>' is not defined by type '<mutation_name>Input'."
```

### Expected Behavior

We can change the meta data of a computed attribute

### Steps to Reproduce

- start instance of Infrahub
- load the following schema
```yaml
---
version: "1.0"
nodes:
  - name: Node
    namespace: Testing
    attributes:
      - name: name
        kind: Text
        optional: false
        unique: true
      - name: computed_name
        kind: Text
        optional: false
        read_only: true
        computed_attribute:
          kind: Jinja2
          jinja2_template: "computed {{ name__value }}"
```
- Create a new TestingNode
- In the UI open the metadata popup for the computed attribute of the newly created TestingNode
- set `is_visible` to `True` and click save
- you get an error message
```
Field 'computed_name' is not defined by type 'TestinNodeUpdateInput'.
```
- This GraphQL mutation triggered the error
```graphql
mutation TestinNodeUpdate {
  TestinNodeUpdate(
    data: {id: "181d6f81-2664-4087-33be-c5168b6421ec", computed_name: {owner: null, source: null, is_visible: true, is_protected: false}}
  ) {
    ok
    __typename
  }
}
```
