### ISSUE TITLE
task: Message unclear when changing `branch` in schema

### ISSUE THREAD

**Issue by BaptisteGi** [opsmill/infrahub#5637]
### Component

API Server / GraphQL

### Task Description

I am working on the following schema:

```yml
---
# yaml-language-server: $schema=https://schema.infrahub.app/infrahub/schema/latest.json
version: "1.0"

generics:
  - name: Generic
    namespace: Service
    description: Generic service...
    label: Service
    icon: mdi:package-variant
    include_in_menu: true
    branch: aware
    human_friendly_id:
      - service_identifier__value
    order_by:
      - service_identifier__value
    display_labels:
      - service_identifier__value
    attributes:
      - name: service_identifier
        kind: Text
        unique: true
        order_weight: 1000
        optional: false
        branch: agnostic
      - name: account_reference
        kind: Text
        order_weight: 1000
        optional: false
        branch: agnostic

nodes:
  - name: DedicatedInternet
    namespace: Service
    description: This service provides customers with a dedicated physical port, ensuring complete internet connectivity.
    label: Dedicated Internet
    icon: mdi:ethernet
    menu_placement: ServiceGeneric
    inherit_from:
      - ServiceGeneric
    include_in_menu: true
    branch: aware
    attributes:
      - name: status
        kind: Dropdown
        optional: false
        default_value: draft
        order_weight: 1050
        branch: agnostic
        choices:
          - name: draft
            label: Draft
            color: "#D3D3D3"
          - name: in-delivery
            label: In Delivery
            color: "#A8E6A2"
          - name: active
            label: Active
            color: "#66CC66"
          - name: in-decomissioning
            label: In Decomissioning
            color: "#FFAB59"
          - name: decomissioned
            label: Decomissioned
            color: "#FF6B6B"
      - name: bandwidth
        kind: Dropdown
        optional: false
        default_value: "1000"
        order_weight: 1100
        branch: aware
        choices:
          - name: "100"
            label: Hundred Megabits
            description: Provides a 100 Mbps bandwidth.
          - name: "1000"
            label: One Gigabit
            description: Provides a 1 Gbps bandwidth.
          - name: "10000"
            label: Ten Gigabits
            description: Provides a 10 Gbps bandwidth.
      - name: ip_package
        kind: Dropdown
        optional: false
        order_weight: 1120
        default_value: small
        branch: aware
        choices:
          - name: small
            label: Small
            description: Provide customer with 6 IPs.
            color: "#6a5acd"
          - name: medium
            label: Medium
            description: Provide customer with 14 IPs.
            color: "#9090de"
          - name: large
            label: Large
            description: Provide customer with 30 IPs.
            color: "#ffa07a"
```

I loaded the schema once, when I change the `branch` value for my `DedicatedInternet` node and load it again I have the following message: 

```console
Unable to load the schema:
  'not_supported': ServiceDedicatedInternet branch None
```

I assume this sort of operation isn't allowed but the message isn't clear, maybe we could improve it.
