### ISSUE TITLE
bug: Relationship max_count not enforced in UI for relationship kind `Generic`

### ISSUE THREAD

**Issue by FragmentedPacket** [opsmill/infrahub#5661]
### Infrahub version

1.1.6

### Current Behavior

When adding relationships in the UI for a relationship kind of `Generic`, it allows you to add more than the `max_count` defined within the schema.

We can workaround this by changing the relationship's kind from `Generic` to `Attribute`.

### Expected Behavior

Provides error message that the operation cannot happen due to over max count: `Too many relationships, max 2 at child_interfaces`

### Steps to Reproduce

1. Load provided schema
```yaml
# yaml-language-server: $schema=https://schema.infrahub.app/infrahub/schema/latest.json
version: "1.0"
generics:
  - name: GenericDeviceInterface
    namespace: Network
    description: "Device Interface"
    label: "Device Interface"
    icon: "mdi:ethernet"
    order_by:
      - name__value
    display_labels:
      - name__value
    include_in_menu: false
    human_friendly_id:
      - "name__value"
    attributes:
      - name: name
        kind: Text
        label: Name
        description: "Name of the interface"
        unique: false
        optional: false
    relationships:
      - name: sfp
        peer: NetworkSFP
        optional: true
        cardinality: one
        identifier: "sfp__interface"
        kind: Attribute
      - name: breakout_sfp
        peer: NetworkGenericSFP
        optional: true
        cardinality: one
        kind: Attribute
        identifier: "sfp__child_interfaces"
  - name: GenericSFP
    namespace: Network
    description: "Generic SFP Module"
    label: "Generic SFP Module"
    icon: "mdi:ethernet"
    order_by:
      - serial_number__value
    display_labels:
      - serial_number__value
    attributes:
      - name: serial_number
        kind: Text
        label: "Serial Number"
        description: "Serial number of SFP"
        unique: true
        optional: true
nodes:
  - name: Interface
    namespace: Network
    inherit_from:
      - NetworkGenericDeviceInterface
  - name: SFP
    namespace: Network
    inherit_from:
      - "NetworkGenericSFP"
    uniqueness_constraints:
      - ["serial_number__value", "interface"]
    relationships:
      - name: interface
        peer: NetworkGenericDeviceInterface
        cardinality: one
        identifier: "sfp__interface"
        optional: false
  - name: DualSFP
    namespace: Network
    inherit_from:
      - "NetworkGenericSFP"
    attributes:
      - name: breakout_mode
        description: "The selected breakout mode for the SFP."
        label: Breakout Mode
        kind: Dropdown
        regex: "^2x\\d+[G]$"
        optional: true
        choices:
          - name: 2x400G
            label: 2x400G Breakouts
            color: "#009933"
    relationships:
      - name: child_interfaces
        peer: NetworkGenericDeviceInterface
        cardinality: many
        identifier: "sfp__child_interfaces"
        optional: true
        max_count: 2
```
2. Log into the UI and create 3 interfaces (Ethernet1/1-3)
3. Create new Dualsfp (`b1`)
4. Navigate to detail view of `b1` Dualsfp's `Child Interfaces` tab
5. Add all three interfaces to `b1` (NOTE: Should we be able to multi-select on this form as well?)

### Additional Information

Here is the GraphQL sent from the UI:

```
{
    "operationName": "RelationshipAdd",
    "variables": {
        "objectId": "1820c789-6a9e-b643-3be7-106530255db6",
        "relationshipIds": [
            {
                "id": "1820c782-36aa-fbbf-3be0-106513f1ae1f"
            }
        ],
        "relationshipName": "child_interfaces"
    },
    "query": "mutation RelationshipAdd($objectId: String!, $relationshipName: String!, $relationshipIds: [RelatedNodeInput]) {\n  RelationshipAdd(\n    data: {id: $objectId, name: $relationshipName, nodes: $relationshipIds}\n  ) {\n    ok\n    __typename\n  }\n}"
}
```
