### ISSUE TITLE
bug: `order_weight` set in generic isn't updated in the nodes

### ISSUE THREAD

**Issue by BaptisteGi** [opsmill/infrahub#5684]
### Component

API Server / GraphQL

### Infrahub version

1.1.6

### Current Behavior

I have the following schema that I load to infrahub:

```yaml
# yaml-language-server: $schema=https://schema.infrahub.app/infrahub/schema/latest.json
---
version: "1.0"

generics:
  - name: Generic
    namespace: Random
    description: Random stuff
    attributes:
      - name: first
        kind: Text
        unique: true
        order_weight: 1000
      - name: second
        kind: Text
        unique: true
        order_weight: 2000

nodes:
  - name: Stuff
    namespace: Random
    description: Random stuff
    inherit_from:
      - RandomGeneric
```

Everything works fine, I have the attribute called `first` that goes first.

Now I changed my mind and I want the attribute `first` to go second, I update and load the following schema:

```yaml
# yaml-language-server: $schema=https://schema.infrahub.app/infrahub/schema/latest.json
---
version: "1.0"

generics:
  - name: Generic
    namespace: Random
    description: Random stuff
    attributes:
      - name: first
        kind: Text
        unique: true
        order_weight: 3000
      - name: second
        kind: Text
        unique: true
        order_weight: 2000

nodes:
  - name: Stuff
    namespace: Random
    description: Random stuff
    inherit_from:
      - RandomGeneric
```

=> The order in the UI is still the same even tho I changed the order weight. 

### Expected Behavior

I expect the `order_weight` setting for an attribute to be updated when I update the generic.

### Steps to Reproduce

- Spin Infrahub
- Load the first schema from the above section
- Check the attribute order in the UI
- Load the second schema from the above section
- Attributes are still in the same order

### Additional Information

Similar in a way with https://github.com/opsmill/infrahub/issues/2242

If I load the following schema it fixes my issue:

```yaml
# yaml-language-server: $schema=https://schema.infrahub.app/infrahub/schema/latest.json
---
version: "1.0"

generics:
  - name: Generic
    namespace: Random
    description: Random stuff
    attributes:
      - name: first
        kind: Text
        unique: true
        order_weight: 3000
      - name: second
        kind: Text
        unique: true
        order_weight: 2000

nodes:
  - name: Stuff
    namespace: Random
    description: Random stuff
    inherit_from:
      - RandomGeneric
    attributes:
      - name: first
        kind: Text
        unique: true
        order_weight: 3000
```
