### ISSUE TITLE
task: Resource manager doesn't work with node containing mandatory attribute

### ISSUE THREAD

**Issue by BaptisteGi** [opsmill/infrahub#5691]
### Component

Frontend UI, API Server / GraphQL

### Task Description

I have the following schema loaded in Infrahub:

```yml
---
# yaml-language-server: $schema=https://schema.infrahub.app/infrahub/schema/latest.json
version: "1.0"

nodes:
  - name: IPAddress
    namespace: Ipam
    description: IP Address
    label: IP Address
    icon: mdi:ip
    include_in_menu: false
    order_by:
      - address__value
    display_labels:
      - address__value
    inherit_from:
      - BuiltinIPAddress
    uniqueness_constraints:
      - [ip_namespace, address__value]
    human_friendly_id:
      - address__value
      - ip_namespace__name__value
    attributes:
      - name: status
        kind: Dropdown
        optional: false # Moving this one to false
        choices:
          - name: this
          - name: that

  - name: Prefix
    namespace: Ipam
    description: IPv4 or IPv6 network (with mask)
    icon: mdi:ip-network
    include_in_menu: false
    label: Prefix
    order_by:
      - prefix__value
    display_labels:
      - prefix__value
    inherit_from:
      - BuiltinIPPrefix
    uniqueness_constraints:
      - [ip_namespace, prefix__value]
    human_friendly_id:
      - prefix__value
      - ip_namespace__name__value
    attributes:
      - name: status
        kind: Dropdown
        choices:
          - name: active
            label: Active
          - name: deprecated
            label: Deprecated
          - name: reserved
            label: Reserved
      - name: role
        kind: Dropdown
        optional: true
        choices:
          - name: loopback
            label: Loopback
            description: Represents internal communications.
            color: "#B0A8B9"
          - name: management
            label: Management
            description: Handles administrative operations.
            color: "#AEC6CF"
          - name: public
            label: Public
            description: Public facing network.
            color: "#FDFD96"
          - name: server
            label: Server
            description: Dedicated to server functions.
            color: "#77DD77"
          - name: supernet
            label: Supernet
            description: Covers multiple networks
            color: "#FFB347"
          - name: technical
            label: Technical
            description: Focused on technical aspects.
            color: "#9678B6"
          - name: loopback-vtep
            label: Loopback VTEP
            description: Facilitates virtualized network communications within loopback configurations.
            color: "#CDB4DB"

  - name: Device
    namespace: Dcim
    label: Device
    icon: mdi:server
    human_friendly_id:
      - name__value
    order_by:
      - name__value
    display_labels:
      - name__value
    attributes:
      - name: name
        kind: Text
        unique: true
        order_weight: 1000
    relationships:
      - name: primary_address
        peer: IpamIPAddress
        label: Primary IP Address
        optional: true
        cardinality: one
        kind: Attribute
        order_weight: 1700
```

Then using the UI I create a prefix and finally attach a IP address Pool to it.

I now want to create devices and get the management IP assigned from the pool. However I have the following issue:

![Image](https://github.com/user-attachments/assets/81109236-60f5-4688-a7b1-7485fc39725b)

**Here as the `status` attribute of my IP address is mandatory thus resource manager can't instantiate it on the fly**

I can see multiple options to workaround this:
- Do not allow resource manager to be linked to node that has mandatory attribute without default
- Bring that attribute to the form so user can fill in the value
- ...
