### ISSUE TITLE
bug: Jinja computed attribute failure if related node is not found

### ISSUE THREAD

**Issue by BeArchiTek** [opsmill/infrahub#5768]
### Component

API Server / GraphQL

### Infrahub version

1.1.6

### Current Behavior

When a computed_attribute (in jinja2) is using an `optional` related node, and this is one is not set, the API reply with a cryptic "Unable to find the peer"

![Image](https://github.com/user-attachments/assets/8d006b4d-021e-4623-8ebf-271d05f57461)

The schema used for this :
```yaml
  - name: BGPPeerGroup
    namespace: Routing
    menu_placement: RoutingBGPSession
    uniqueness_constraints:
      - ["name__value"]
    human_friendly_id:
      - name__value
    order_by:
      - name__value
    display_labels:
      - description__value
    attributes:
      - name: name
        kind: Text
        optional: false
        order_weight: 1000
      - name: description
        kind: Text
        computed_attribute:
          kind: Jinja2
          jinja2_template: "{% if remote_as__asn__value %}.{{ remote_as__asn__value }}{% endif %}.{{ address_family__value }}"
        read_only: true
        order_weight: 1100
      - name: address_family
        kind: Dropdown
        choices:
          - name: "ipv4"
            label: IPv4
            description: "Policy applies to IPv4 addresses."
            color: "#E6E6FA"  # lavender
          - name: "ipv6"
            label: IPv6
            description: "Policy applies to IPv6 addresses."
            color: "#E6E6FA"  # lavender
        default_value: "ipv4"
        order_weight: 1150
    relationships:
      - name: local_as
        identifier: bgppeergroup__local_as
        peer: RoutingAutonomousSystem
        optional: true
        cardinality: one
        kind: Attribute
      - name: remote_as
        identifier: bgppeergroup__remote_as
        peer: RoutingAutonomousSystem
        optional: true
        cardinality: one
        kind: Attribute
```

### Expected Behavior

The API should provide a better error for the non-creation of the node.

### Steps to Reproduce

1- load the schema above in infrahub as well as this one :
```yaml
  - name: AutonomousSystem
    namespace: Routing
    uniqueness_constraints:
      - ["asn__value"]
    human_friendly_id:
      - "asn__value"
    order_by:
      - asn__value
    display_labels:
      - asn__value
    attributes:
      - name: name
        kind: Text
        computed_attribute:
          kind: Jinja2
          jinja2_template: "AS{{ asn__value }}"
        read_only: true
        description: "Name of the Autonomous System"
        order_weight: 1000
      - name: asn
        kind: Number
        description: "Autonomous System Number"
        order_weight: 1050
```

3 - try creating a RoutingBGPPeerGroup without any remote_as

### Additional Information

A better `if/else` test seems to be
```yaml
jinja2_template: "{% if remote_as__asn__value is defined and remote_as__asn__value %}.{{ remote_as__asn__value }}{% endif %}.{{ address_family__value }}"
```

But I find strange we can't directly use the relationship name like : `if remote_as`
