### ISSUE TITLE
feature: Be able to use other attribute "serialization" on computed attribute

### ISSUE THREAD

**Issue by BeArchiTek** [opsmill/infrahub#5769]
### Component

API Server / GraphQL

### Describe the Feature Request

Right now we can only use `__value` for the different attribute / related node we can use in a jinja2 computed attribute.

I would like to be able to use the others format returned by graphql
example : __ip for IP Address

### Describe the Use Case

I would like to avoid :
```yaml
jinja2_template: "{{ session_type__value | lower }}-{{ remote_ip__address__value.split('/')[0] }}{% endif %}"
```
when I can do
```yaml
jinja2_template: "{{ session_type__value | lower }}-{{ remote_ip__address__ip }}{% endif %}"
```

**Comment by wvandeun** [comment]
Another one that would be really useful is the `label` of a `Dropdown` attribute.

**Comment by ogenstad** [comment]
I wondered why this wasn't working and took a closer look.

This schema works:
```yaml

# yaml-language-server: $schema=https://schema.infrahub.app/develop/schema.schema.json
---
version: '1.0'
nodes:
  - name: Thing
    namespace: Test
    default_filter: name__value
    order_by:
      - name__value
    display_labels:
      - name__value
    attributes:
      - name: name
        kind: Text
        unique: true
      - name: address
        kind: IPHost
      - name: slug
        kind: Text
        description: "Lowercase"
        computed_attribute:
          kind: Jinja2
          jinja2_template: "{{ name__value|lower }}-{{ address__version }}"
        read_only: true
        optional: false
```

The reason is simply that "version" is added as an accepted option here:
https://github.com/opsmill/infrahub/blob/infrahub-v1.2.7/backend/infrahub/core/attribute.py#L953

We should be able to just add "ip" and the other ones to the relevant attributes where this is applicable.
