### ISSUE TITLE
bug: Unable to added/updated `Generic` Relationships with cardinality `many` on IPAM Views

### ISSUE THREAD

**Issue by BeArchiTek** [opsmill/infrahub#5924]
### Component

Frontend UI

### Infrahub version

1.1.7

### Current Behavior

Using the IPAM view, I am unable to add/update nodes on a relationship of kind `Generic` (or `Component`) with a cardinality `many` as this type of relationship is not available in the default creation form.

We normally use the tab system with a "add form"

### Expected Behavior

I can do it :)

### Steps to Reproduce

- load the demo-schema
- create a prefix or  load the demo-data
- update the IpamIPPrefix as follow : 
```yaml
  - name: IPPrefix
    namespace: Ipam
    include_in_menu: false
    inherit_from:
      - "BuiltinIPPrefix"
    description: "IPv4 or IPv6 network"
    icon: "mdi:ip-network"
    label: "IP Prefix"
    relationships:
      - name: attribute_cardinality_one
        peer: InfraVLAN
        optional: true
        cardinality: one
        kind: Attribute
      - name: generic_cardinality_one
        label: Site
        peer: LocationSite
        optional: true
        cardinality: one
        kind: Generic
      - name: generic_cardinality_many
        label: Autonomous System
        peer: InfraAutonomousSystem
        optional: true
        cardinality: many
        kind: Generic
      - name: attribute_cardinality_many
        peer: OrganizationGeneric
        optional: true
        cardinality: many
        kind: Attribute
```
- load the schema into infrahub
- test the different relationships with the form.

### Additional Information

It is possible to do so via Graphql API or via the /objects/IpamIPPrefix view directly
