### ISSUE TITLE
bug: Relationship of cardinality `many` are not properly showing in the IPAM Views

### ISSUE THREAD

**Issue by BeArchiTek** [opsmill/infrahub#5925]
### Component

Frontend UI

### Infrahub version

1.1.7

### Current Behavior

(Split from https://github.com/opsmill/infrahub/issues/5924, found together)

When a relationship of cardinality `many` is present on one of the nodes using the Ipam Views, the related nodes are not properly showing in the view.

![Image](https://github.com/user-attachments/assets/640861d1-9f5e-459f-87b0-98f2e768efaf)

### Expected Behavior

Proper visualization of the related nodes

### Steps to Reproduce

- load the demo-schema
- load the demo-data
- Add those relationships to the node IpamIPPRefix:
```yaml
  - name: IPPrefix
    namespace: Ipam
    include_in_menu: false
    inherit_from:
      - "BuiltinIPPrefix"
    description: "IPv4 or IPv6 network"
    icon: "mdi:ip-network"
    label: "IP Prefix"
    relationships:
      - name: attribute_cardinality_one
        peer: InfraVLAN
        optional: true
        cardinality: one
        kind: Attribute
      - name: generic_cardinality_one
        label: Site
        peer: LocationSite
        optional: true
        cardinality: one
        kind: Generic
      - name: generic_cardinality_many
        label: Autonomous System
        peer: InfraAutonomousSystem
        optional: true
        cardinality: many
        kind: Generic
      - name: attribute_cardinality_many
        peer: OrganizationGeneric
        optional: true
        cardinality: many
        kind: Attribute
```
- load the schema in infrahub
- Add Organization (attribute_cardinality_many) to the Prefix, they will be missing from the UI even if properly set in the form

### Additional Information

You are able to retrieve/see the related nodes via GraphQL API and via the /objects/IpamIPPrefix/ views
