### ISSUE TITLE
bug: not able to clear the value of a list attribute in the frontend

### ISSUE THREAD

**Issue by wvandeun** [opsmill/infrahub#5934]
### Component

Frontend UI

### Infrahub version

1.1.7

### Current Behavior

Clearing the value of a list attribute of an object, in the frontend doesn't work.

### Expected Behavior

The value of the list attribute is cleared.

### Steps to Reproduce

- spin up instance of Infrahub
- load the following schema
```yaml
---
version: "1.0"
nodes:
  - name: Node
    namespace: Some
    label: "A Node"
    attributes:
      - name: name
        kind: Text
        optional: false
      - name: test
        kind: List
        optional: true
```
- create a SomeNode object and add some value to the test attribute
- open the edit form for the object
- delete all values from the test list attribute
- click save
- the old attribute value will still be there for the test attribute

### Additional Information

The mutation send by the frontend is the following:
```graphql
mutation SomeNodeUpdate {
  SomeNodeUpdate(data: {id: "1829da1e-7bd2-ceea-3000-c510406dcf0a", test: null}) {
    ok
    __typename
  }
}
```

The following mutation seems to work correctly:
```graphql
mutation SomeNodeUpdate {
  SomeNodeUpdate(data: {id: "1829da1e-7bd2-ceea-3000-c510406dcf0a", test: {value: null}}) {
    ok
    __typename
  }
}
```
or
```graphql
mutation SomeNodeUpdate {
  SomeNodeUpdate(data: {id: "1829da1e-7bd2-ceea-3000-c510406dcf0a", test: {value: []}}) {
    ok
    __typename
  }
}
```
