### ISSUE TITLE
bug: ancestor and descendants graphql resolvers are broken after you merge a branch with a new hierarchical nodes

### ISSUE THREAD

**Issue by wvandeun** [opsmill/infrahub#6019]
### Component

API Server / GraphQL

### Infrahub version

1.1.8

### Current Behavior

When you create new hierarchical nodes in a branch and then merge that branch, then the ancestor or descendants GraphQL resolver does not return any results for any node that is part of the hierarchy.

### Expected Behavior

The ancestor and/or descendant GraphQL resolvers return the actual ancestors or descendants. 

### Steps to Reproduce

- spin up instance of Infrahub
- load the following schema
```yaml
---
version: "1.0"
generics:
  - name: Generic
    namespace: Location
    hierarchical: true
    attributes:
      - name: name
        kind: Text
        optional: false
        unique: true
nodes:
  - name: Country
    namespace: Location
    inherit_from:
      - LocationGeneric
    parent: ""
    children: LocationSite
  - name: Site
    namespace: Location
    inherit_from:
      - LocationGeneric
    parent: LocationCountry
    children: ""
```
- create a branch in infrahub
- in the branch create a new country `Belgium`
- in the branch create a new site `BXL` and set the parent to be `Belgium`
- in the branch execute this GraphQL query
```graphql
query {
  LocationSite {
    edges {
      node {
        name {
          value
        }
        ancestors {
          edges {
            node {
              name {
                value
              }
            }
          }
        }
      }
    }
  }
}
```
   notice that the site has Belgium as an ancestor
- merge the branch
- re-execute the above graphql query in the main branch
- notice that the ancestor resolver does not return any result

### Additional Information

- the parent/child relationship between the hierarchical node seems to be intact after the merge
- the same issues occurs when querying a country and its descendants
