### ISSUE TITLE
bug: node kind update broken for hierarchical schemas

### ISSUE THREAD

**Issue by ajtmccarty** [opsmill/infrahub#6051]
### Infrahub version

v1.1.9

### Current Behavior

updating our default `LocationContinent` schema, which uses the `LocationGeneric` hierarchy, to use a new name does not migrate existing parent/child relationships
It correctly migrates attributes and other relationships, but parent/children are effectively deleted from the new `LocationContinentNew` nodes

### Expected Behavior

updating a node's kind should correctly migrate its existing parent/children relationships to the new kind if necessary

### Steps to Reproduce

1. load the default location schema in `models/base`
2. create a `LocationContient`
3. create a `LocationCountry` with a parent from step 2 above
4. load this new version of the location schema that makes some updates to the existing one. **you will need to get the IDs for each schema from the schema explorer**
```
---
# yaml-language-server: $schema=https://schema.infrahub.app/infrahub/schema/latest.json
version: "1.0"

nodes:
  - name: ContinentNew  				// update
    id: 182cca2e-eaa5-0540-3a27-c512f1985a96		// update
    namespace: Location
    description: "A continent on planet earth."
    icon: "jam:world"
    inherit_from:
      - "LocationGeneric"
    generate_profile: false
    default_filter: "name__value"
    order_by:
      - "name__value"
    display_labels:
      - "name__value"
    children: "LocationCountry"
    parent: ""
  - name: Country
  	id: "182cca2e-f6de-fc64-3a2c-c5177612336c"	// update
    namespace: Location
    description: "A country within a continent."
    icon: "gis:search-country"
    inherit_from:
      - "LocationGeneric"
    generate_profile: false
    default_filter: "name__value"
    order_by:
      - "name__value"
    display_labels:
      - "name__value"
    children: "LocationSite"
    parent: "LocationContinentNew"			// update
```
5. try to update the relationship between the Country and Continent you created above. Create a new `LocationContinentNew` and edit your existing `LocationCountry` to point at this new Continent. It will fail with an `At most, one relationship expected` error.

### Additional Information

The underlying issue is that parent/child relationships are not correctly duplicated and linked to the new `LocationContinentNew` nodes created during the node kind migration
