### ISSUE TITLE
bug: unable to rename a generic in the schema when a node inherits from the generic

### ISSUE THREAD

**Issue by wvandeun** [opsmill/infrahub#6060]
### Component

API Server / GraphQL

### Infrahub version

1.1.9

### Current Behavior

When you try to rename a generic which is used by one or more node, you get the following error message:

```
Unable to load the schema:
  Node-level 'inherit_from' constraint violation on schema 'SchemaNode'. Node (SchemaNode: 182db35d-32d1-ba40-36c8-c518fcc607f1) is not compliant. 
The error relates to field inherit_from=['TemplateGeneric'].
```

### Expected Behavior

The generic will be renamed and the nodes inheriting from the generic will be updated to point to the new name of the generic.

### Steps to Reproduce

- load instance of Infrahub
- load the following schema
```yaml
---
version: "1.0"
generics:
  - name: Generic
    namespace: Template
    attributes:
      - name: name
        kind: Text
        optional: false
        unique: true
nodes:
  - name: Node
    namespace: Testing
    inherit_from:
      - TemplateGeneric
```
- Update the schema definition to the following, to update the name of the generic. Replace the `id` with the the `id` on your instance of Infrahub
```yaml
---
version: "1.0"
generics:
  - name: Generic
    namespace: Stencil
    id: "182db35d-0562-8344-36c6-c51dc7c19c67"
    attributes:
      - name: name
        kind: Text
        optional: false
        unique: true
nodes:
  - name: Node
    namespace: Testing
    inherit_from:
      - StencilGeneric
```
