### ISSUE TITLE
bug: deleting attr from a generic will delete overridden versions on inheriting schema

### ISSUE THREAD

**Issue by ajtmccarty** [opsmill/infrahub#6073]
### Infrahub version

v1.1.9

### Current Behavior

Say you have this schema in which `NodeB` inherits from `GenericA` and overrides `GenericA.color` with a new default value
```
generics:
  - name: GenericA
    attributes:
    - name: color
      default_value: blue
nodes:
  - name: NodeB
    inherit_from: ["GenericA"]
    attributes:
    - name: color
      default_value: green
```

if you try to delete the attribute `color` from `GenericA`, then all `color` attributes on any instances of `NodeA` will also be deleted

### Expected Behavior

overridden attributes and relationships on node schemas that inherit from a generic should not be affected when an attribute/relationship is deleted from the generic schema

### Steps to Reproduce

1. update the default schema in `models/base` to add  this snippet to `OrganizationManufacturer`
```
    attributes:
      - name: description
        kind: Text
        optional: true
        default_value: "the new description"
        order_weight: 1200
```
2. start infrahub
3. load the updated "default" schema
4. create an `OrganizationManufacturer` instance
5. update the `description` attribute on the `OrganizationGeneric` schema to delete it by adding the following to the schema
```
    attributes:
      - name: description
-->     id: <get it from the schema explorer>
-->     state: absent
```
6. load the latest version of the schema to infrahub
7. the description of the `OrganizationManufacturer` you created in step 4 will still show, but if you attempt to update it, nothing will happen. if you look at your `OrganizationManufacturer` at the database level, you will see that the `description` attribute has been deleted

### Additional Information

this is probably a bug in `NodeAttributeRemoveMigrationQuery01`
I suspect that this cypher query removes all attributes of a given name under a given generic, which would include overridden attributes on inheriting schema. the fix is probably to update this query to explicitly ignore schema that have overridden the attribute in question
