### ISSUE TITLE
bug: 502 error message for invalid generator parameter

### ISSUE THREAD

**Issue by BeArchiTek** [opsmill/infrahub#6184]
### Component

API Server / GraphQL

### Infrahub version

1.2.0

### Current Behavior

When there's a mismatch between parameters defined in the generator declaration (for the query) and those declared in the query itself, the declaration is accepted, but running it will result in a 502.

For example: for a given generator :
```yaml
generator_definitions:
  - name: create_tags
    file_path: "generators/create_tags.py"
    targets: tags_groups
    query: GetTags
    parameters:
      fake_name: "name__value"
```
With this query
```
query GetTags($tag_name: String!) { 
  BuiltinTag(name__value: $tag_name) {
    edges {
      node {
        id
        name {
          value
        }
        description {
          value
        }
      }
    }
  }
}
```

### Expected Behavior

1. The system should validate parameter names at configuration load time
2. Error message should indicate:
   - The parameter name expected by the query (`tag_name`)
   - The parameter name provided in the configuration (`fake_name`)
   - The generator name (`create_tags`)
   - The query name (`GetTags`)

### Steps to Reproduce

1. Reuse the generator declaration and query definition from above
2. Load the configuration 
3. Try to run the generator
4. Observe 502 error instead of helpful parameter mismatch message
