### ISSUE TITLE
bug: cannot merge branch with nodes having unique AND optional attribute

### ISSUE THREAD

**Issue by fatih-acar** [opsmill/infrahub#6191]
### Component

API Server / GraphQL

### Infrahub version

1.2.2

### Current Behavior

When trying to merge a branch that contains new nodes having an attribute that is both unique and optional, but with no value set, the API server throws the following error:

```
infrahub.exceptions.ValidationError: Node-level 'uniqueness_constraints' constraint violation on schema 'LocationRackTest'. Node (LocationRackTest: 1831f6d2-1adc-f75e-1190-c5126d30cf91) is not compliant. The error relates to field facility_id.value='NULL'.,
Node-level 'uniqueness_constraints' constraint violation on schema 'LocationRackTest'. Node (LocationRackTest: 1831f6d3-806c-312f-1190-c51babf9636c) is not compliant. The error relates to field facility_id.value='NULL'.,
Node-level 'uniqueness_constraints' constraint violation on schema 'LocationRackTest'. Node (LocationRackTest: 1831f6d4-a271-f25a-1190-c519fae59fde) is not compliant. The error relates to field facility_id.value='NULL'.,
Attribute-level 'unique' constraint violation on schema 'LocationRackTest'. Node (LocationRackTest: 1831f6d2-1adc-f75e-1190-c5126d30cf91) is not compliant. The error relates to field facility_id='NULL'.,
Attribute-level 'unique' constraint violation on schema 'LocationRackTest'. Node (LocationRackTest: 1831f6d3-806c-312f-1190-c51babf9636c) is not compliant. The error relates to field facility_id='NULL'.,
Attribute-level 'unique' constraint violation on schema 'LocationRackTest'. Node (LocationRackTest: 1831f6d4-a271-f25a-1190-c519fae59fde) is not compliant. The error relates to field facility_id='NULL'.
```

### Expected Behavior

Branch should be successfully merged, as the nodes were successfully created within the source branch...

### Steps to Reproduce

```
# yaml-language-server: $schema=https://schema.infrahub.app/infrahub/schema/latest.json
---
version: "1.0"

nodes:
  # --------------------  Locations  --------------------
  - name: RackTest
    namespace: Location
    include_in_menu: true
    label: RackTest
    display_labels:
      - shortname__value
    icon: "clarity:rack-server-line"
    attributes:
      - name: shortname
        kind: Text
        order_weight: 1100
      - name: facility_id
        kind: Text
        unique: true
        optional: true
        order_weight: 1100
```

Create a new branch.
Create RackTest nodes with no `facility_id` set within that branch. Try merging that same branch.
