### ISSUE TITLE
bug: Template sub-component creation fails when using HFID with generic parent

### ISSUE THREAD

**Issue by BeArchiTek** [opsmill/infrahub#6301]
### Component

API Server / GraphQL

### Infrahub version

1.2.4

### Current Behavior

When creating a template sub-component for a node that has a relationship to an inherited node, using HFID fails because the system tries to resolve the HFID against the parent node type instead of the actual node type.

For example, with this schema:

```yaml
# Test schema to reproduce the issue
---
version: "1.0"
generics:
  - name: Product
    namespace: Catalog
    description: "Product generic"
    default_filter: name__value
    order_by:
      - name__value
    display_labels:
      - name__value
    attributes:
      - name: name
        kind: Text
        label: Name
        optional: false
        order_weight: 1
nodes:
  - name: Software
    namespace: Catalog
    description: "A software product"
    label: "Software Product"
    inherit_from:
      - CatalogProduct
    generate_template: true
    relationships:
      - name: category
        peer: ProductCategory
        optional: true
        kind: Component
        cardinality: many

  - name: ProductCategory
    namespace: Catalog
    attributes:
      - name: name
        kind: Text
        optional: false
        unique: true
    relationships:
      - name: product
        peer: CatalogProduct
        optional: false
        kind: Parent
        cardinality: one
```

When I try to create a template sub-component for `ProductCategory` using HFID:

```graphql
mutation CreateTemplateCategoryWithHFID {
  TemplateCatalogProductCategoryCreate(
    data:{
      template_name:{value:"dev-tools"},
      product: {hfid: "vscode"}
    }
  ) {
    ok
  }
}
```

I get this error:

```
{
  "data": {
    "TemplateCatalogProductCategoryCreate": null
  },
  "errors": [
    {
      "message": "Unable to find the node vscode / TemplateCatalogProduct in the database.",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "TemplateCatalogProductCategoryCreate"
      ]
    }
  ]
}
```

### Expected Behavior

The system should resolve the HFID against the actual node type (`CatalogSoftware`) rather than the parent type (`CatalogProduct`) when creating template sub-components.

This works correctly in the UI because the dropdown selector helps select the right kind, but fails when using the GraphQL API directly.

### Steps to Reproduce

1. Using the schema above
2. Create a node that has a relationship to the parent type (like `ProductCategory` relating to `Product`)
3. Create a `Software` node with a name (e.g., "vscode")
4. Try to create a template sub-component for `ProductCategory` using the HFID of the `Software` node
