### ISSUE TITLE
bug: textarea attributes are not displayed properly in the web interface

### ISSUE THREAD

**Issue by wvandeun** [opsmill/infrahub#6400]
### Component

Frontend UI

### Infrahub version

1.2.8

### Current Behavior

An attribute of kind `TextArea` is not properly displayed in the UI. The value of the attribute is not visible.

![Image](https://github.com/user-attachments/assets/7890f13d-ee92-4164-a872-687b9685e644)
![Image](https://github.com/user-attachments/assets/54be1573-7c85-42a3-a009-e3a9372bbf4a)
![Image](https://github.com/user-attachments/assets/90849b52-f12b-44de-9ad3-3af471e94ddb)

### Expected Behavior

The value of the textarea attribute is displayed properly.

### Steps to Reproduce

- start instance of Infrahub
- load the following schema
```yaml
---
version: "1.0"
nodes:
  - name: Object
    namespace: Testing
    attributes:
      - name: name
        kind: Text
        optional: true
        unique: true
      - name: other
        kind: TextArea
        label: Rack details
        optional: false
```
- Create a TestingObject object and provide a value for the `other` attribute
- Open the newly created object in the node detail view
