### ISSUE TITLE
bug: Confusing error message on mandatory computed attributes with lookup errors

### ISSUE THREAD

**Issue by ogenstad** [opsmill/infrahub#6426]
### Component

API Server / GraphQL

### Infrahub version

1.2.8

### Current Behavior

If we use the demo schema and [InfraDevice](https://github.com/opsmill/infrahub/blob/infrahub-v1.2.8/models/base/dcim.yml#L168-L253) it has a required computed attribute that looks like this:

```yaml
      - name: computed_description
        kind: Text
        description: Combine various attributes to provide a human frendly description of this device.
        computed_attribute:
          kind: Jinja2
          jinja2_template: "{{ type__value }} device used as {{ role__value }} on {{ site__name__value|lower }}"
```

This template would use the "type" and "role" attributes along with the "site" relationship.

The site relationship is marked as optional:

```yaml
      - name: site
        label: Site
        peer: LocationSite
        optional: true
        cardinality: one
        kind: Attribute
        order_weight: 1
```

When creating an InfraDevice without specifying the site, Infrahub will try to render the computed_description as it's required and when doing so we'll encounter a lookup error for the site that [doesn't exist](https://github.com/opsmill/infrahub/blob/infrahub-v1.2.8/backend/infrahub/core/node/__init__.py#L477)

```python
                if attribute_path.is_type_relationship:
                    relationship_attribute: RelationshipManager = getattr(
                        self, attribute_path.active_relationship_schema.name
                    )
                    peer = await relationship_attribute.get_peer(db=db, raise_on_error=True) <-- This "peer not found" error gets raised

                    related_node = await registry.manager.get_one_by_id_or_default_filter(
                        db=db, id=peer.id, kind=attribute_path.active_relationship_schema.peer, branch=self._branch.name
                    )

                    attribute: BaseAttribute = getattr(
                        getattr(related_node, attribute_path.active_attribute_schema.name),
                        attribute_path.active_attribute_property_name,
                    )
                    variables[variable] = attribute
```

The main problem here is that it's impossible for the user to determine what went wrong.

### Expected Behavior

We need some clarifications regarding the expected behaviour here as there are a number of options.

1. Fail to load this schema as invalid
2. Dynamically update the schema to mark site as required
3. Instead of raising a "peer not found" error raise an error specifically saying that we can't fetch the peer for the "site" relationship and as it's required we are unable to create the node because of this
4. Set the value of `site__name__value` to `None` if the peer is missing.

During the daily meeting I got the sense that people were leaning to option 4 which I think I prefer myself too.

If it already worked that way we'd get an error when passing the value to the Jinja2 filter "lower", so we also need to ensure that this error message is properly returned to the user. It could also be that once fixed we should update this computed attribute with a check to see if the relationship is defined.

### Steps to Reproduce

1. Load the demo schema
2. Try to create an InfraDevice object without specifying the "site" relationship
