### ISSUE TITLE
bug: HFID for object template

### ISSUE THREAD

**Issue by BaptisteGi** [opsmill/infrahub#6478]
### Infrahub version

1.2.9

### Current Behavior

At the moment I want to create multiple device templates using the `infrahubctl object load` command.

```yml
---
apiVersion: infrahub.app/v1
kind: Object
spec:
  kind: TemplateDcimDevice
  data:
    - template_name: "Template1"
      interfaces:
        kind: TemplateInterfacePhysical
        data:
          - template_name: "Ethernet1"
            name: "Ethernet1"
          - template_name: "Ethernet2"
            name: "Ethernet2"
    - template_name: "Template2"
      interfaces:
        kind: TemplateInterfacePhysical
        data:
          - template_name: "Ethernet1"
            name: "Ethernet1"
          - template_name: "Ethernet2"
            name: "Ethernet2"

```

When I run that command it moves interfaces from one template to another instead of creating records.

### Expected Behavior

I expect to have `Ethernet1` and `Ethernet2` on both templates.

### Steps to Reproduce

- Run infrahub
- Clone schema library
- Adjust https://github.com/opsmill/schema-library/blob/5ee4805668634bb476123c550bc2c3ebbc48f442/base/dcim.yml#L428 to enable template
- Load base schema
- Create `object.yml` file with yml content above
- Run `infrahubctl object load object.yml`

-> Go to template and check interfaces under device template

### Additional Information

I suspect a HFID issue however it looks fine from a schema standpoint:
<img width="1562" alt="Image" src="https://github.com/user-attachments/assets/72c84b46-5f4f-45bd-868d-c212aac5a5bc" />

Maybe the issue is on sdk side ...
