### ISSUE TITLE
bug: selecting a resource pool in an object template allocates a resource to the template

### ISSUE THREAD

**Issue by wvandeun** [opsmill/infrahub#6551]
### Component

backend, frontend

### Infrahub version

1.2.11

### Current Behavior

When you create an object template for a node that has a relationship to a node for which you can use a resource pool, such as an IP address, you can select a resource pool for that relationship.

This leads to the result that a resource is allocated out of the pool to the template.

As a user of Infrahub, I would expect that when I create a new object using the template, it would allocate a resource out of the pool that I selected in the template.
Instead it seems to propose the resource that was allocated to the template.

After internal discussion this seem to be the expected behavior. A template is meant to be used in a scenario where a copy is created when you create a new node using that template.

### Expected Behavior

The current behavior is not what a user of Infrahub would expect. In this case I think it would be better to not support object templates with resource managers at all.

### Steps to Reproduce

- spin up instance of Infrahub
- load this schema
```yaml
---
version: "1.0"
nodes:
  - name: IPPrefix
    namespace: Ipam
    inherit_from:
      - BuiltinIPPrefix
  - name: IPAddress
    namespace: Ipam
    inherit_from:
      - BuiltinIPAddress
  - name: CustomTag
    namespace: Infra
    generate_template: true
    attributes:
      - name: name
        kind: Text
        optional: false
        unique: true
    relationships:
      - name: ip_address
        peer: IpamIPAddress
        cardinality: one
        optional: false
```
- Create a new prefix
- Create an IP address resource pool using the prefix as resource
- Create an object template for InfraCustomTag, select the resource pool for the ip_address relation
- An IP address will now have been allocated to the template
- Create a new InfraCustomTag object using the template
- The IP address allocated to the template will now be "suggested" for the ip_address relation
