### ISSUE TITLE
bug: Cannot create object in frontend when using only read_only attributes

### ISSUE THREAD

**Issue by FragmentedPacket** [opsmill/infrahub#6627]
### Component

Frontend UI

### Infrahub version

1.3.0bX

### Current Behavior

I have a schema that tracks a service and has two fields that use a `NumberPool` and a Jinja computed attribute that consumes the `NumberPool` attribute.

When we go to the form, we only see `Member of groups` and cannot save/create an object.

<img width="391" alt="Image" src="https://github.com/user-attachments/assets/2454518a-58b5-4051-a946-b54ed4a29010" />

### Expected Behavior

Ability to create the node without defining extra attributes such as `description` for a user to fill in to be able to create the node.

### Steps to Reproduce

1. Start Infrahub
2. Load the following schema
```yaml
# yaml-language-server: $schema=https://schema.infrahub.app/infrahub/schema/latest.json
---
version: "1.0"
generics:
  - name: Generic
    namespace: Service
    attributes:
      - name: service_number
        kind: NumberPool
        unique: false
        optional: false
        read_only: true
        parameters:
          start_range: 1000
          end_range: 1010
      - name: service_identifier
        kind: Text
        unique: true
        optional: false
        read_only: true
        computed_attribute:
          kind: Jinja2
          jinja2_template: "service-{{ service_number__value }}"
nodes:
  - name: Internet
    namespace: Service
    inherit_from:
      - ServiceGeneric
  - name: Pop
    namespace: Service
    inherit_from:
      - ServiceGeneric
    attributes:
      - name: location
        kind: Text
        unique: false
        optional: true
```
3. Attempt to create an `InternetService` in the UI
