### ISSUE TITLE
feature: Context-Aware Relationship Filtering in Forms

### ISSUE THREAD

**Issue by lancamat1** [opsmill/infrahub#6693]
### Describe the Feature Request

This feature enables dynamic filtering of relationship options in UI forms based on:
1. Other field values within the same form (`current_node` source)
2. Fixed business rules (`value` direct comparison)

**Key Capabilities**:
- Filter relationship options by comparing attributes through relationship paths (e.g., `building__name__value`)
- Support logical operators (`equals`, `in`, `gte`, etc.)
- Combine multiple filters (AND logic)
- No parent-component relationship required

## Example Implementation: Campus Booking System

```yaml
# Complete room and equipment filtering for bookings
relationships:
  - name: room
    peer: CampusRoom
    filters:
      # ROOM FILTERS
      - field: building__name__value          # 1a. Same building as selected
        operator: equals
        source: current_node
        source_field: building__name__value
        
      - field: capacity__value                # 1b. Minimum capacity
        operator: gte
        value: 10
        
      - field: status__value                  # 1c. Available rooms only
        operator: equals
        value: "available"

  - name: equipment
    peer: CampusEquipment
    filters:
      # EQUIPMENT FILTERS  
      - field: building__name__value          # 2a. Same building
        operator: equals
        source: current_node
        source_field: building__name__value
        
      - field: status__value                  # 2b. Available equipment
        operator: in
        values: ["available", "reserved_pending_approval"]
        
      - field: allowed_departments__value     # 2c. Department compatibility
        operator: contains
        source: current_node
        source_field: requester__department__value
        
      - field: type__value                    # 2d. Allowed types
        operator: in
        values: ["projector", "teleconference"]
        
      - field: maintenance_status__value      # 2e. Operational status
        operator: equals
        value: "certified"
```

### Describe the Use Case

**When booking campus rooms, users must**:
- Select the same building repeatedly for rooms/equipment
- Manually ensure compatibility between selections
- Avoid rooms/equipment that violate business rules (capacity, maintenance status)

**Solution**:
- Building selected once: All subsequent fields (rooms, equipment) auto-filter to that building
- Smart defaults: Only show available rooms with sufficient capacity
- Error prevention: Hide incompatible equipment (e.g., projectors under maintenance)

### Additional Information

**Future Considerations**:
- Other source types like session (user roles) or parameters (URL pre-filters) could be added later
- Potential operators: contains (lists), regex_match (patterns)

**Schema Impact**:
- Backward compatible (no changes to existing relationships)
- Optional filters key in relationship definitions

**Dependencies**:
- Requires frontend support for reactive form updates

Highlighted different use-case on [discord](https://discord.com/channels/1212332642801025064/1380852112199520266/1380852112199520266)
