### ISSUE TITLE
bug: cannot create a number pool linked to an attribute of a schema node that does not exist in main

### ISSUE THREAD

**Issue by wvandeun** [opsmill/infrahub#6708]
### Component

API Server / GraphQL

### Infrahub version

1.3.0

### Current Behavior

I cannot create a CoreNumberPool that for an attribute of kind Number on a schema node that does not exist in the main branch.
Contradictory this does work when I use an attribute of kind NumberPool.

### Expected Behavior

I can create a CoreNumberPool for an attribute on a schema node that does not exist in main yet, but it does exist in branch.

### Steps to Reproduce

- spin up instance of Infrahub
- create a branch
- load the following schema in the branch
```yaml
---
version: "1.0"
nodes:
  - name: Device
    namespace: Infra
    attributes:
      - name: name
        kind: Text
        optional: false
      - name: device_id
        kind: NumberPool
        read_only: true
        parameters:
          start_range: 100
          end_range: 1000
      - name: testing
        kind: Number
        optional: true
```
- in the branch, try to create a number pool using the following mutation
```graphql
mutation CoreNumberPoolCreate {
  CoreNumberPoolCreate(
    data: {name: {value: "ttt"}, node: {value: "InfraDevice"}, node_attribute: {value: "testing"}, start_range: {value: 1}, end_range: {value: 10}}
  ) {
    object {
      id
      display_label
    }
    ok
  }
}
```
- You receive the following response
```json
{
    "data": {
        "CoreNumberPoolCreate": null
    },
    "errors": [
        {
            "message": "The selected model does not exist",
            "locations": [
                {
                    "line": 2,
                    "column": 3
                }
            ],
            "path": [
                "CoreNumberPoolCreate"
            ]
        }
    ]
}
```
