### ISSUE TITLE
bug: Removing Attribute does not Update Uniqueness Constraint

### ISSUE THREAD

**Issue by ashleytayles** [opsmill/infrahub#6711]
### Infrahub version

1.3.0

### Current Behavior

When a node in the schema is updated to remove an attribute that has "unique: true" configured, you cannot do so as it will result in an error.

The attempted schema change (on a branch):

```
nodes:
  - state: present
    name: Vrf
    label: VRF
    description: Virtual Routing and Forwarding instance.
    icon: mdi:ip-network
    include_in_menu: false
    human_friendly_id:
      - name__value
    namespace: Wan
    inherit_from:
      - IpamGenericVrf
    generate_profile: true
    generate_template: false
    attributes:
      - name: name
        kind: Text
        unique: true
        order_weight: 1000
      - name: description
        kind: Text
        optional: true
        order_weight: 2000
      - name: wan_id
        description: Unique identifier for the WAN VRF
        label: WAN ID
        kind: Number
        unique: true
        state: absent
```

results in:

```
infrahubctl schema load --branch initial gin-schema.yml 
Unable to load the schema:
  WanVrf: Requested unique constraint not found within node. (`wan_id__value`)
```

### Expected Behavior

Attribute should be able to be removed and uniqueness constraint automatically updated. 

### Steps to Reproduce

The attempted schema change (on a branch):

```
nodes:
  - state: present
    name: Vrf
    label: VRF
    description: Virtual Routing and Forwarding instance.
    icon: mdi:ip-network
    include_in_menu: false
    human_friendly_id:
      - name__value
    namespace: Wan
    inherit_from:
      - IpamGenericVrf
    generate_profile: true
    generate_template: false
    attributes:
      - name: name
        kind: Text
        unique: true
        order_weight: 1000
      - name: description
        kind: Text
        optional: true
        order_weight: 2000
      - name: wan_id
        description: Unique identifier for the WAN VRF
        label: WAN ID
        kind: Number
        unique: true
        state: absent
```

results in:

```
infrahubctl schema load --branch initial gin-schema.yml 
Unable to load the schema:
  WanVrf: Requested unique constraint not found within node. (`wan_id__value`)
```

### Additional Information

infrahubctl info
 Connection Status:  ✅                        
 Python Version:     3.13.0                    
 SDK Version:        1.13.0                    
 Infrahub Version:   1.3.0                     
 User:               Admin   

I was able to workaround this by manually defined the uniqueness constraints, pushing to branch, then removing my manual statement.

```
    uniqueness_constraints:
      - ["name__value"]
```
