### ISSUE TITLE
bug: Number attribute min_value/max_value constraints not enforced during node creation

### ISSUE THREAD

**Issue by BeArchiTek** [opsmill/infrahub#6714]
### Component

API Server / GraphQL

### Infrahub version

1.3.0

### Current Behavior

When loading a schema with `Number` attributes that have `min_value` and `max_value` parameters defined, these constraints aren't being enforced during node creation. Users can still create nodes with values outside the specified range.

### Expected Behavior

The system should validate the input against the defined constraints and reject values that fall outside the specified range.

### Steps to Reproduce

1. Load a schema with a `Number` attribute that has `min_value` and `max_value` parameters:
```yaml
nodes:
  - name: Application
    namespace: Random
    include_in_menu: true
    attributes:
    - name: size
      kind: Number
      parameters:
        min_value: 1
        max_value: 4094
      optional: false
```
2. Attempt to create a node with a value outside the specified range (e.g., 0 or 5000)
3. The node is created successfully without validation errors
