### ISSUE TITLE
bug: Number attribute min/max_value constraints are not displayed for a Number attribute in the schema view

### ISSUE THREAD

**Issue by wvandeun** [opsmill/infrahub#6715]
### Component

Frontend UI

### Infrahub version

1.3.0

### Current Behavior

When you define a node in the schema with a number attribute, and you define a min &|| max_value in the parameters. Then the defined parameters do not show up in the schema UI.

### Expected Behavior

The defined parameters for a Number attribute should show in the schema UI, just like we do for Text and NumberPool attributes.

### Steps to Reproduce

- load instance of Infrahub
- load this schema
```yaml
---
version: "1.0"
generics: []
nodes:
  - name: Node
    namespace: Testing
    attributes:
      - name: name
        kind: Text
        optional: false
      - name: test
        kind: Number
        optional: true
        parameters:
          min_value: 1
          max_value: 100
```
- open the schema view for TestingNode and expand the test attribute
