### ISSUE TITLE
bug: Cannot search/filter object template when creating an object

### ISSUE THREAD

**Issue by FragmentedPacket** [opsmill/infrahub#6724]
### Component

Frontend UI

### Infrahub version

1.3.0

### Current Behavior

When creating an object from a template, a list of templates show up, but when you attempt to filter the list, it returns no results.

### Expected Behavior

Filter down list of available templates

### Steps to Reproduce

1. Launch fresh Infrahub instance
2. Load the following schema
```yaml
# yaml-language-server: $schema=https://schema.infrahub.app/infrahub/schema/latest.json
---
version: "1.0"
nodes:
  - name: Device
    namespace: Infra
    generate_template: true
    attributes:
      - name: name
        kind: Text
        unique: true
        optional: false
      - name: description
        kind: Text
        unique: false
        optional: false
```
3. Create a template with any description for `InfraDevice` and template name of `Base Device`
4. Start to create a device using `Start from template` option
5. `Base Device` should show up in the list.
6. Start typing out `Base Device` and the option will disappear after a few characters
