### ISSUE TITLE
bug: Schema load accepts `from` Python keyword and then causes 500s

### ISSUE THREAD

**Issue by FragmentedPacket** [opsmill/infrahub#6730]
### Component

API Server / GraphQL

### Infrahub version

1.3.0

### Current Behavior

We're able to load a schema that uses a Python keyword (`from`), but then we see 500 API errors in the frontend after the schema loads. The API server is unable to generate a GraphQL schema due to a reserved Python keyword as well.

### Expected Behavior

Disallow loading an attribute/relationship with any Python keyword such as `from` due to not being able to generate a GraphQL schema.

### Steps to Reproduce

1. Launch fresh Infrahub instance
2. Check/Load the following schema
```yaml
# yaml-language-server: $schema=https://schema.infrahub.app/infrahub/schema/latest.json
---
version: "1.0"
nodes:
  - name: RoutingPolicy
    namespace: Infra
    attributes:
      - name: name
        kind: Text
        unique: true
        optional: false
      - name: description
        kind: Text
        unique: false
        optional: false
      - name: from
        label: From
        description: "Specifies the match conditions for the policy term."
        kind: Dropdown
        state: absent
        choices:
          - name: "default"
            label: Default
        optional: true
```
3. Attempt to navigate UI to the new schema node and encounter 500 error

### Additional Information

View logs on the docker container.

[server.txt](https://github.com/user-attachments/files/20869165/server.txt)
